// layers/base/pages/products/[slug].vue
<script setup lang="ts">
const route = useRoute();
const slug = route.params.slug as string;

const { data: product } = useLazyFetch(`/api/products/${slug}`) as { data: Ref<Record<string, any> | null> };
const { data: projectsUsing } = useLazyFetch(`/api/products/${slug}/content`) as { data: Ref<any[] | null> };

useSeoMeta({
  title: () => product.value ? `${product.value.name} — ${useSiteName()}` : `Product — ${useSiteName()}`,
  description: () => product.value?.description ?? '',
});
</script>

<template>
  <div v-if="product" class="product-detail">
    <NuxtLink to="/products" class="cpub-back-link"><i class="fa-solid fa-arrow-left"></i> Products</NuxtLink>

    <div class="product-layout">
      <!-- Main -->
      <div class="product-main">
        <div class="product-header">
          <div class="product-icon"><i class="fa-solid fa-microchip"></i></div>
          <div>
            <h1 class="product-name">{{ product.name }}</h1>
            <span v-if="product.category" class="product-category">{{ product.category }}</span>
          </div>
        </div>

        <p v-if="product.description" class="product-desc">{{ product.description }}</p>

        <!-- Specs -->
        <div v-if="product.specs && Object.keys(product.specs).length" class="product-specs">
          <h2 class="product-section-title">Specifications</h2>
          <div class="specs-grid">
            <div v-for="(val, key) in product.specs" :key="key" class="spec-item">
              <span class="spec-key">{{ key }}</span>
              <span class="spec-val">{{ val }}</span>
            </div>
          </div>
        </div>

        <!-- Links -->
        <div class="product-links">
          <a v-if="product.purchaseUrl" :href="product.purchaseUrl" target="_blank" rel="noopener" class="product-link-btn">
            <i class="fa-solid fa-cart-shopping"></i> Purchase
          </a>
          <a v-if="product.datasheetUrl" :href="product.datasheetUrl" target="_blank" rel="noopener" class="product-link-btn">
            <i class="fa-solid fa-file-pdf"></i> Datasheet
          </a>
        </div>

        <!-- Projects using this product -->
        <div v-if="projectsUsing?.length" class="product-projects">
          <h2 class="product-section-title">Projects Using This</h2>
          <div class="product-projects-grid">
            <ContentCard v-for="item in projectsUsing" :key="item.id" :item="item" />
          </div>
        </div>
        <div v-else class="product-projects-empty">
          <p>No projects using this product yet.</p>
        </div>
      </div>

      <!-- Sidebar -->
      <aside class="product-sidebar">
        <div class="product-sb-card">
          <h3 class="product-sb-label">Details</h3>
          <div class="product-sb-row" v-if="product.category">
            <span>Category</span>
            <span class="product-sb-val">{{ product.category }}</span>
          </div>
          <div class="product-sb-row" v-if="product.pricing">
            <span>Price</span>
            <span class="product-sb-val">{{ product.pricing }}</span>
          </div>
          <div class="product-sb-row" v-if="product.hub">
            <span>Hub</span>
            <NuxtLink :to="`/hubs/${product.hub.slug}`" class="product-sb-link">{{ product.hub.name }}</NuxtLink>
          </div>
        </div>
      </aside>
    </div>
  </div>
  <div v-else class="product-not-found">
    <h1>Product not found</h1>
  </div>
</template>

<style scoped>
.product-detail { max-width: 1080px; margin: 0 auto; padding: 32px; }
.cpub-back-link { font-size: 11px; font-family: var(--font-mono); color: var(--text-faint); text-decoration: none; display: inline-flex; align-items: center; gap: 6px; margin-bottom: 20px; }
.cpub-back-link:hover { color: var(--accent); }

.product-layout { display: grid; grid-template-columns: 1fr 280px; gap: 32px; }

.product-header { display: flex; align-items: center; gap: 16px; margin-bottom: 16px; }
.product-icon { width: 56px; height: 56px; border: var(--border-width-default) solid var(--border); background: var(--accent-bg); display: flex; align-items: center; justify-content: center; font-size: 24px; color: var(--accent); }
.product-name { font-size: 24px; font-weight: 700; letter-spacing: -0.02em; }
.product-category { font-size: 11px; font-family: var(--font-mono); color: var(--text-faint); text-transform: capitalize; }
.product-desc { font-size: 14px; color: var(--text-dim); line-height: 1.7; margin-bottom: 24px; }

.product-section-title { font-size: 16px; font-weight: 700; margin-bottom: 12px; display: flex; align-items: center; gap: 8px; }

.specs-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(200px, 1fr)); gap: 8px; margin-bottom: 24px; }
.spec-item { display: flex; justify-content: space-between; padding: 8px 12px; border: var(--border-width-default) solid var(--border2); background: var(--surface); font-size: 12px; }
.spec-key { color: var(--text-dim); font-family: var(--font-mono); font-size: 11px; }
.spec-val { font-weight: 500; }

.product-links { display: flex; gap: 8px; margin-bottom: 32px; }
.product-link-btn { display: inline-flex; align-items: center; gap: 6px; padding: 8px 16px; border: var(--border-width-default) solid var(--border); background: var(--surface); color: var(--text); text-decoration: none; font-size: 13px; font-weight: 500; box-shadow: var(--shadow-md); }
.product-link-btn:hover { box-shadow: var(--shadow-sm); transform: translate(1px, 1px); }

.product-projects-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(260px, 1fr)); gap: 12px; }
.product-projects-empty { color: var(--text-faint); font-size: 13px; padding: 24px 0; }

.product-sidebar { display: flex; flex-direction: column; gap: 16px; }
.product-sb-card { padding: 16px; border: var(--border-width-default) solid var(--border); background: var(--surface); box-shadow: var(--shadow-md); }
.product-sb-label { font-family: var(--font-mono); font-size: 10px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.12em; color: var(--text-faint); margin-bottom: 12px; }
.product-sb-row { display: flex; justify-content: space-between; padding: 6px 0; border-bottom: var(--border-width-default) solid var(--border2); font-size: 13px; color: var(--text-dim); }
.product-sb-row:last-child { border-bottom: none; }
.product-sb-val { font-weight: 500; color: var(--text); }
.product-sb-link { color: var(--accent); text-decoration: none; font-weight: 500; }
.product-sb-link:hover { text-decoration: underline; }

.product-not-found { text-align: center; padding: 64px 0; color: var(--text-dim); }

@media (max-width: 768px) { .product-layout { grid-template-columns: 1fr; } }
</style>

// apps/reference/src/routes/(app)/learn/[slug]/+page.svelte
<script lang="ts">
  import SeoHead from '$lib/components/SeoHead.svelte';
  import CurriculumAccordion from '$lib/components/learning/CurriculumAccordion.svelte';
  import EnrollButton from '$lib/components/learning/EnrollButton.svelte';
  import ProgressBar from '$lib/components/learning/ProgressBar.svelte';
  import type { PageData } from './$types';

  let { data }: { data: PageData } = $props();
  const path = data.path;

  const totalLessons = path.modules.reduce((sum: number, m: { lessons: unknown[] }) => sum + m.lessons.length, 0);
</script>

<SeoHead
  title={path.title}
  description={path.description ?? ''}
  type="Course"
  url={`/learn/${path.slug}`}
  image={path.coverImageUrl}
  authorName={path.author.displayName ?? path.author.username}
/>

<div class="page">
  <!-- Hero -->
  {#if path.coverImageUrl}
    <div class="lp-hero">
      <img src={path.coverImageUrl} alt="" class="lp-hero-img" />
      <div class="lp-hero-overlay"></div>
    </div>
  {/if}

  <div class="grid-sb">
    <!-- Main content -->
    <div class="lp-main">
      <header class="lp-header">
        <div class="tag-row">
          <span class="tag tag-accent">learning path</span>
          {#if path.difficulty}
            <span class="tag"
              class:tag-green={path.difficulty === 'beginner'}
              class:tag-yellow={path.difficulty === 'intermediate'}
              class:tag-red={path.difficulty === 'advanced'}
            >{path.difficulty}</span>
          {/if}
        </div>

        <h1 class="lp-title">{path.title}</h1>

        {#if path.description}
          <p class="lp-description">{path.description}</p>
        {/if}

        <div class="lp-meta">
          <span class="lp-meta-item">By {path.author.displayName ?? path.author.username}</span>
          {#if path.estimatedHours}
            <span class="lp-meta-item">{path.estimatedHours}h estimated</span>
          {/if}
          <span class="lp-meta-item">{totalLessons} lessons</span>
          <span class="lp-meta-item">{path.enrollmentCount} enrolled</span>
        </div>
      </header>

      {#if path.isEnrolled && path.enrollment}
        <div class="lp-progress-section">
          <ProgressBar value={Number(path.enrollment.progress)} label="Path progress" />
        </div>
      {/if}

      <section class="lp-curriculum" aria-label="Curriculum">
        <div class="sec-head">
          <h2>Curriculum</h2>
          <span class="sec-sub">{path.modules.length} modules</span>
        </div>
        <CurriculumAccordion modules={path.modules} pathSlug={path.slug} />
      </section>
    </div>

    <!-- Sidebar -->
    <aside class="lp-sidebar">
      <div class="sb-card">
        <span class="sb-title">Enroll</span>
        <div class="lp-enroll-body">
          <EnrollButton
            isEnrolled={path.isEnrolled}
            progress={path.enrollment ? Number(path.enrollment.progress) : 0}
            pathSlug={path.slug}
          />
        </div>
      </div>

      <div class="sb-card">
        <span class="sb-title">Details</span>
        <div class="lp-detail-rows">
          {#if path.difficulty}
            <div class="lp-detail-row">
              <span class="lp-detail-key">Difficulty</span>
              <span class="lp-detail-val lp-diff-{path.difficulty}">{path.difficulty}</span>
            </div>
          {/if}
          {#if path.estimatedHours}
            <div class="lp-detail-row">
              <span class="lp-detail-key">Duration</span>
              <span class="lp-detail-val">{path.estimatedHours}h</span>
            </div>
          {/if}
          <div class="lp-detail-row">
            <span class="lp-detail-key">Modules</span>
            <span class="lp-detail-val">{path.modules.length}</span>
          </div>
          <div class="lp-detail-row">
            <span class="lp-detail-key">Lessons</span>
            <span class="lp-detail-val">{totalLessons}</span>
          </div>
          <div class="lp-detail-row">
            <span class="lp-detail-key">Enrolled</span>
            <span class="lp-detail-val">{path.enrollmentCount}</span>
          </div>
        </div>
      </div>

      <div class="sb-card">
        <span class="sb-title">Author</span>
        <div class="lp-author-row">
          <div class="av av-sm">{(path.author.displayName ?? path.author.username).charAt(0).toUpperCase()}</div>
          <a href="/u/{path.author.username}" class="lp-author-name">{path.author.displayName ?? path.author.username}</a>
        </div>
      </div>
    </aside>
  </div>
</div>

<style>
  .lp-hero {
    position: relative;
    width: 100%;
    aspect-ratio: 21 / 6;
    overflow: hidden;
    border-radius: var(--radius-sm, 4px);
    margin-bottom: var(--space-6, 1.5rem);
  }

  .lp-hero-img {
    width: 100%;
    height: 100%;
    object-fit: cover;
  }

  .lp-hero-overlay {
    position: absolute;
    inset: 0;
    background: linear-gradient(to top, var(--color-bg, #0c0c0b) 0%, transparent 60%);
  }

  .lp-main {
    display: flex;
    flex-direction: column;
    gap: var(--space-8, 2rem);
  }

  .lp-header {
    display: flex;
    flex-direction: column;
    gap: var(--space-3, 0.75rem);
  }

  .lp-title {
    font-size: var(--text-3xl, 2.25rem);
    font-weight: var(--font-weight-bold, 700);
    color: var(--color-text, #d8d5cf);
    line-height: 1.2;
    margin: 0;
  }

  .lp-description {
    font-size: var(--text-lg, 1.25rem);
    color: var(--color-text-secondary, #888884);
    line-height: 1.6;
    margin: 0;
  }

  .lp-meta {
    display: flex;
    flex-wrap: wrap;
    gap: var(--space-3, 0.75rem);
  }

  .lp-meta-item {
    font-family: var(--font-mono, monospace);
    font-size: var(--text-xs, 0.6875rem);
    text-transform: uppercase;
    letter-spacing: 0.05em;
    color: var(--color-text-muted, #444440);
  }

  .lp-progress-section {
    padding: var(--space-4, 1rem);
    border: 1px solid var(--color-border, #272725);
    border-radius: var(--radius-sm, 4px);
    background: var(--color-surface-alt, #141413);
  }

  .lp-curriculum :global(h2) {
    font-size: var(--text-lg, 1.125rem);
    color: var(--color-text, #d8d5cf);
    margin: 0;
  }

  /* Sidebar */
  .lp-sidebar {
    display: flex;
    flex-direction: column;
    gap: var(--space-4, 1rem);
  }

  .lp-enroll-body {
    padding-top: var(--space-2, 0.5rem);
  }

  .lp-detail-rows {
    display: flex;
    flex-direction: column;
    gap: 0;
  }

  .lp-detail-row {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: var(--space-2, 0.5rem) 0;
    border-bottom: 1px solid var(--color-border, #272725);
  }

  .lp-detail-row:last-child {
    border-bottom: none;
  }

  .lp-detail-key {
    font-family: var(--font-mono, monospace);
    font-size: 10px;
    text-transform: uppercase;
    letter-spacing: 0.06em;
    color: var(--color-text-muted, #444440);
  }

  .lp-detail-val {
    font-size: var(--text-sm, 0.75rem);
    color: var(--color-text-secondary, #888884);
    text-transform: capitalize;
  }

  .lp-diff-beginner { color: var(--color-success, #4ade80); }
  .lp-diff-intermediate { color: var(--color-warning, #fbbf24); }
  .lp-diff-advanced { color: var(--color-error, #f87171); }

  .lp-author-row {
    display: flex;
    align-items: center;
    gap: var(--space-2, 0.5rem);
    padding-top: var(--space-2, 0.5rem);
  }

  .lp-author-name {
    font-size: var(--text-sm, 0.75rem);
    color: var(--color-text, #d8d5cf);
    text-decoration: none;
  }

  .lp-author-name:hover {
    color: var(--color-accent, #5b9cf6);
  }

  @media (max-width: 768px) {
    .lp-hero {
      aspect-ratio: 16 / 9;
    }
  }
</style>
