// apps/reference/src/routes/(app)/communities/[slug]/settings/+page.svelte
<script lang="ts">
  import { enhance } from '$app/forms';
  import { Input, Textarea, Button } from '@snaplify/ui';
  import CommunityHeader from '$lib/components/community/CommunityHeader.svelte';
  import CommunityNav from '$lib/components/community/CommunityNav.svelte';
  import MemberCard from '$lib/components/community/MemberCard.svelte';
  import RoleSelector from '$lib/components/community/RoleSelector.svelte';
  import BanForm from '$lib/components/community/BanForm.svelte';
  import InviteLinkGenerator from '$lib/components/community/InviteLinkGenerator.svelte';
  import type { PageData, ActionData } from './$types';

  let { data, form }: { data: PageData; form: ActionData } = $props();

  let deleteConfirm = $state(false);
  let banTargetId = $state<string | null>(null);
</script>

<svelte:head>
  <title>Settings — {data.community.name} — Snaplify</title>
</svelte:head>

<div class="settings-page">
  <CommunityHeader community={data.community} />
  <CommunityNav
    slug={data.community.slug}
    active="settings"
    role={data.community.currentUserRole}
  />

  {#if form?.error}
    <div class="error-banner" role="alert">{form.error}</div>
  {/if}

  <section class="settings-section">
    <h2>Community Settings</h2>
    <form method="POST" action="?/update" use:enhance class="settings-form">
      <Input id="name" label="Name" name="name" value={data.community.name} />
      <Textarea id="description" label="Description" name="description" rows={3} value={data.community.description ?? ''} />
      <Textarea id="rules" label="Rules" name="rules" rows={5} value={data.community.rules ?? ''} />
      <div class="form-field">
        <label for="joinPolicy">Join Policy</label>
        <select id="joinPolicy" name="joinPolicy">
          <option value="open" selected={data.community.joinPolicy === 'open'}>Open</option>
          <option value="approval" selected={data.community.joinPolicy === 'approval'}
            >Approval</option
          >
          <option value="invite" selected={data.community.joinPolicy === 'invite'}
            >Invite Only</option
          >
        </select>
      </div>
      <Button variant="primary" type="submit">Save Changes</Button>
    </form>
  </section>

  <section class="settings-section">
    <h2>Invites</h2>
    <InviteLinkGenerator slug={data.community.slug} invites={data.invites} />
  </section>

  <section class="settings-section">
    <h2>Members ({data.members.length})</h2>
    <div class="members-list">
      {#each data.members as member (member.userId)}
        <div class="member-row">
          <MemberCard {member} />
          {#if data.community.currentUserRole === 'owner' || data.community.currentUserRole === 'admin'}
            <div class="member-actions">
              <RoleSelector
                slug={data.community.slug}
                userId={member.userId}
                currentRole={member.role}
                actorRole={data.community.currentUserRole ?? 'member'}
              />
              {#if member.role !== 'owner'}
                <form method="POST" action="?/kick" use:enhance class="inline-form">
                  <input type="hidden" name="userId" value={member.userId} />
                  <button
                    type="submit"
                    class="btn btn-small btn-danger-outline"
                    aria-label="Kick {member.user.username}"
                  >
                    Kick
                  </button>
                </form>
                <button
                  class="btn btn-small btn-danger-outline"
                  onclick={() => (banTargetId = member.userId)}
                  aria-label="Ban {member.user.username}"
                >
                  Ban
                </button>
              {/if}
            </div>
          {/if}
        </div>
        {#if banTargetId === member.userId}
          <BanForm
            slug={data.community.slug}
            userId={member.userId}
            oncancel={() => (banTargetId = null)}
          />
        {/if}
      {/each}
    </div>
  </section>

  <section class="settings-section">
    <h2>Bans ({data.bans.length})</h2>
    {#if data.bans.length === 0}
      <p class="empty-text">No banned users.</p>
    {:else}
      <div class="bans-list">
        {#each data.bans as ban (ban.id)}
          <div class="ban-row">
            <div class="ban-info">
              <strong>{ban.user.displayName ?? ban.user.username}</strong>
              {#if ban.reason}
                <span class="ban-reason">— {ban.reason}</span>
              {/if}
              {#if ban.expiresAt}
                <span class="ban-expiry"
                  >Expires: {new Date(ban.expiresAt).toLocaleDateString()}</span
                >
              {/if}
            </div>
            <form method="POST" action="?/unban" use:enhance class="inline-form">
              <input type="hidden" name="userId" value={ban.user.id} />
              <Button variant="secondary" size="sm" type="submit">Unban</Button>
            </form>
          </div>
        {/each}
      </div>
    {/if}
  </section>

  {#if data.community.currentUserRole === 'owner'}
    <section class="settings-section danger-zone">
      <h2>Danger Zone</h2>
      {#if deleteConfirm}
        <form method="POST" action="?/delete" use:enhance>
          <p>This will permanently delete the community and all its data. This cannot be undone.</p>
          <div class="danger-actions">
            <Button variant="danger" type="submit">Delete Community</Button>
            <Button variant="secondary" type="button" onclick={() => (deleteConfirm = false)}>Cancel</Button>
          </div>
        </form>
      {:else}
        <Button variant="danger" onclick={() => (deleteConfirm = true)}>
          Delete Community
        </Button>
      {/if}
    </section>
  {/if}
</div>

<style>
  .settings-page {
    max-width: var(--layout-content-width, 960px);
    margin: 0 auto;
  }

  .settings-section {
    margin-bottom: var(--space-12, 3rem);
    padding: var(--space-6, 2rem);
    border: 1px solid var(--color-border, #272725);
    border-radius: var(--radius-md, 6px);
    background: var(--color-surface, #0c0c0b);
  }

  .settings-section h2 {
    font-size: var(--text-lg, 1.25rem);
    color: var(--color-text, #d8d5cf);
    margin-bottom: var(--space-4, 1rem);
  }

  .settings-form {
    display: flex;
    flex-direction: column;
    gap: var(--space-4, 1rem);
  }

  .form-field {
    display: flex;
    flex-direction: column;
    gap: var(--space-1, 0.25rem);
  }

  .form-field label {
    font-weight: var(--font-weight-medium, 500);
    color: var(--color-text, #d8d5cf);
    font-size: var(--text-sm, 0.875rem);
  }

  .form-field select {
    padding: var(--space-2, 0.5rem) var(--space-4, 1rem);
    border: 1px solid var(--color-border, #272725);
    border-radius: var(--radius-md, 6px);
    font-size: var(--text-md, 1rem);
    background: var(--color-surface, #0c0c0b);
    color: var(--color-text, #d8d5cf);
  }

  .error-banner {
    padding: var(--space-2, 0.5rem) var(--space-4, 1rem);
    background: var(--color-error-bg, #fef2f2);
    color: var(--color-error, #dc2626);
    border-radius: var(--radius-md, 6px);
    margin-bottom: var(--space-4, 1rem);
  }

  .members-list,
  .bans-list {
    display: flex;
    flex-direction: column;
    gap: var(--space-2, 0.5rem);
  }

  .member-row {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: var(--space-2, 0.5rem);
    border-bottom: 1px solid var(--color-border, #272725);
  }

  .member-actions {
    display: flex;
    gap: var(--space-1, 0.25rem);
    align-items: center;
  }

  .ban-row {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: var(--space-2, 0.5rem);
    border-bottom: 1px solid var(--color-border, #272725);
  }

  .ban-info {
    display: flex;
    gap: var(--space-2, 0.5rem);
    align-items: center;
    color: var(--color-text, #d8d5cf);
  }

  .ban-reason,
  .ban-expiry {
    color: var(--color-text-secondary, #888884);
    font-size: var(--text-sm, 0.875rem);
  }

  .empty-text {
    color: var(--color-text-secondary, #888884);
  }

  .inline-form {
    display: inline;
  }

  .danger-zone {
    border-color: var(--color-error, #dc2626);
  }

  .danger-zone h2 {
    color: var(--color-error, #dc2626);
  }

  .danger-actions {
    display: flex;
    gap: var(--space-2, 0.5rem);
    margin-top: var(--space-4, 1rem);
  }

  .btn {
    padding: var(--space-2, 0.5rem) var(--space-4, 1rem);
    border: none;
    border-radius: var(--radius-md, 6px);
    font-size: var(--text-md, 1rem);
    cursor: pointer;
    text-decoration: none;
  }

  .btn-small {
    padding: var(--space-1, 0.25rem) var(--space-2, 0.5rem);
    font-size: var(--text-xs, 0.75rem);
    background: var(--color-surface-alt, #1c1c1a);
    color: var(--color-text, #d8d5cf);
    border: 1px solid var(--color-border, #272725);
  }

  .btn-danger-outline {
    color: var(--color-error, #dc2626);
    border: 1px solid var(--color-error, #dc2626);
    background: transparent;
  }
</style>

// layers/base/pages/hubs/[slug]/settings.vue
<script setup lang="ts">
definePageMeta({ middleware: 'auth' });

const route = useRoute();
const slug = computed(() => route.params.slug as string);
const toast = useToast();

import type { Serialized, HubDetail } from '@commonpub/server';

const { data: hub, refresh: refreshHub } = useLazyFetch<Serialized<HubDetail>>(() => `/api/hubs/${slug.value}`);
const { hubGovernance } = useFeatures();

useSeoMeta({
  title: () => `Settings, ${hub.value?.name ?? 'Hub'}, ${useSiteName()}`,
});

// --- Ownership transfer (owner-only, hub governance) ---
const isOwner = computed(() => hub.value?.currentUserRole === 'owner');
const { data: membersData, refresh: refreshMembers } = useLazyFetch<{ items: { userId: string; role: string; user: { username: string; displayName: string | null } }[] }>(
  () => `/api/hubs/${slug.value}/members`,
  { immediate: false },
);
watch([isOwner, hubGovernance], ([owner, gov]) => {
  if (owner && gov && !membersData.value) refreshMembers();
}, { immediate: true });
const transferTo = ref('');
const transferring = ref(false);
const transferCandidates = computed(() =>
  (membersData.value?.items ?? []).filter((m) => m.role !== 'owner'),
);

async function transferOwnership(): Promise<void> {
  const target = transferCandidates.value.find((m) => m.userId === transferTo.value);
  if (!target) return;
  const label = target.user.displayName || target.user.username;
  if (!confirm(`Make @${target.user.username} the owner of this hub? You will become an admin. This cannot be undone by you.`)) return;
  transferring.value = true;
  try {
    await $fetch(`/api/hubs/${slug.value}/transfer-ownership`, { method: 'POST', body: { userId: transferTo.value } });
    toast.success(`Ownership transferred to ${label}`);
    transferTo.value = '';
    await refreshHub();
  } catch (err: unknown) {
    toast.error(extractError(err));
  } finally {
    transferring.value = false;
  }
}

const form = reactive({
  name: '',
  description: '',
  iconUrl: '',
  bannerUrl: '',
  rules: '',
  joinPolicy: 'open',
  privacy: 'public',
  website: '',
});

watch(hub, (h) => {
  if (!h) return;
  form.name = h.name ?? '';
  form.description = h.description ?? '';
  form.iconUrl = h.iconUrl ?? '';
  form.bannerUrl = h.bannerUrl ?? '';
  form.rules = Array.isArray(h.rules) ? (h.rules as string[]).join('\n') : (h.rules ?? '');
  form.joinPolicy = h.joinPolicy ?? 'open';
  form.privacy = h.privacy ?? 'public';
  form.website = h.website ?? '';
}, { immediate: true });

const saving = ref(false);
const { extract: extractError } = useApiError();

async function handleSave(): Promise<void> {
  saving.value = true;

  try {
    // Plain-string URL forces the generic $fetch overload (the typed hub route
    // narrows method to GET, rejecting PUT).
    const hubUrl: string = `/api/hubs/${slug.value}`;
    await $fetch(hubUrl, {
      method: 'PUT',
      body: {
        name: form.name,
        description: form.description || undefined,
        iconUrl: form.iconUrl || undefined,
        bannerUrl: form.bannerUrl || undefined,
        rules: form.rules || undefined,
        joinPolicy: form.joinPolicy,
        privacy: form.privacy,
        website: form.website || undefined,
      },
    });
    toast.success('Hub settings saved');
  } catch (err: unknown) {
    toast.error(extractError(err));
  } finally {
    saving.value = false;
  }
}
</script>

<template>
  <div v-if="hub" class="cpub-hub-settings">
    <div class="cpub-settings-header">
      <NuxtLink :to="`/hubs/${slug}`" class="cpub-back-link">
        <i class="fa-solid fa-arrow-left"></i> Back to hub
      </NuxtLink>
      <h1 class="cpub-settings-title">Hub Settings</h1>
      <p class="cpub-settings-subtitle">Manage {{ hub.name }}</p>
    </div>

    <form class="cpub-settings-form" @submit.prevent="handleSave">
      <div class="cpub-field">
        <label for="hub-name" class="cpub-field-label">Name</label>
        <input
          id="hub-name"
          v-model="form.name"
          type="text"
          class="cpub-field-input"
          required
          placeholder="Hub name"
        />
      </div>

      <div class="cpub-field">
        <label for="hub-desc" class="cpub-field-label">Description</label>
        <textarea
          id="hub-desc"
          v-model="form.description"
          class="cpub-field-input cpub-field-textarea"
          rows="3"
          placeholder="What is this hub about?"
        />
      </div>

      <div class="cpub-field-row">
        <div class="cpub-field">
          <ImageUpload v-model="form.iconUrl" purpose="avatar" label="Icon / Avatar" hint="Square image, at least 256x256px" />
        </div>
        <div class="cpub-field">
          <ImageUpload v-model="form.bannerUrl" purpose="banner" label="Banner Image" hint="Wide image, at least 1200x300px" />
        </div>
      </div>

      <div class="cpub-field">
        <label for="hub-website" class="cpub-field-label">Website</label>
        <input
          id="hub-website"
          v-model="form.website"
          type="url"
          class="cpub-field-input"
          placeholder="https://example.com"
        />
      </div>

      <div class="cpub-field">
        <label for="hub-rules" class="cpub-field-label">Rules (one per line)</label>
        <textarea
          id="hub-rules"
          v-model="form.rules"
          class="cpub-field-input cpub-field-textarea"
          rows="4"
          placeholder="Be respectful&#10;Stay on topic&#10;No spam"
        />
      </div>

      <div class="cpub-field-row">
        <div class="cpub-field">
          <label for="hub-join" class="cpub-field-label">Join Policy</label>
          <select id="hub-join" v-model="form.joinPolicy" class="cpub-field-input">
            <option value="open">Open, anyone can join</option>
            <option value="approval">Approval, requests must be approved</option>
            <option value="invite">Invite Only</option>
          </select>
        </div>

        <div class="cpub-field">
          <label for="hub-privacy" class="cpub-field-label">Privacy</label>
          <select id="hub-privacy" v-model="form.privacy" class="cpub-field-input">
            <option value="public">Public, visible to everyone</option>
            <option value="private">Private, members only</option>
          </select>
        </div>
      </div>

      <div class="cpub-form-actions">
        <button type="submit" class="cpub-btn cpub-btn-primary" :disabled="saving || !form.name">
          {{ saving ? 'Saving...' : 'Save Settings' }}
        </button>
        <NuxtLink :to="`/hubs/${slug}`" class="cpub-btn">Cancel</NuxtLink>
      </div>
    </form>

    <section v-if="hubGovernance && isOwner" class="cpub-danger-zone">
      <h2 class="cpub-danger-title">Transfer ownership</h2>
      <p class="cpub-danger-desc">
        Hand ownership of this hub to another member. You become an admin. This cannot be undone by you.
      </p>
      <div class="cpub-transfer-row">
        <select v-model="transferTo" class="cpub-field-input" aria-label="New owner">
          <option value="">Select a member...</option>
          <option v-for="m in transferCandidates" :key="m.userId" :value="m.userId">
            {{ m.user.displayName || m.user.username }} (@{{ m.user.username }})
          </option>
        </select>
        <button class="cpub-btn cpub-btn-danger" :disabled="!transferTo || transferring" @click="transferOwnership">
          {{ transferring ? 'Transferring...' : 'Transfer' }}
        </button>
      </div>
    </section>
  </div>

  <div v-else class="cpub-empty-state" style="padding: 64px 24px">
    <p class="cpub-empty-state-title">Hub not found</p>
  </div>
</template>

<style scoped>
.cpub-hub-settings {
  max-width: 640px;
  margin: 0 auto;
  padding: 32px;
}

.cpub-settings-header {
  margin-bottom: 32px;
}

/* cpub-back-link → global components.css */

.cpub-settings-title {
  font-size: 22px;
  font-weight: 700;
  margin-bottom: 4px;
}

.cpub-settings-subtitle {
  font-size: 13px;
  color: var(--text-dim);
}

.cpub-settings-form {
  display: flex;
  flex-direction: column;
  gap: 20px;
}

.cpub-field {
  display: flex;
  flex-direction: column;
  gap: 6px;
}

.cpub-field-label {
  font-size: 11px;
  font-weight: 600;
  font-family: var(--font-mono);
  text-transform: uppercase;
  letter-spacing: 0.06em;
  color: var(--text-dim);
}

.cpub-field-input {
  padding: 8px 12px;
  border: var(--border-width-default) solid var(--border);
  background: var(--surface);
  color: var(--text);
  font-size: 13px;
  font-family: var(--font-sans);
  outline: none;
  transition: border-color 0.15s;
}

.cpub-field-input:focus {
  border-color: var(--accent);
}

.cpub-field-input::placeholder {
  color: var(--text-faint);
}

.cpub-field-textarea {
  resize: vertical;
  min-height: 60px;
  line-height: 1.5;
}

.cpub-field-row {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 16px;
}

.cpub-form-actions {
  display: flex;
  gap: 10px;
  padding-top: 8px;
}

select.cpub-field-input { cursor: pointer; }

.cpub-danger-zone {
  margin-top: 40px;
  padding: 20px;
  border: var(--border-width-default) solid var(--red);
  background: var(--surface);
}
.cpub-danger-title { font-size: 14px; font-weight: 700; color: var(--red-text); margin-bottom: 4px; }
.cpub-danger-desc { font-size: 12px; color: var(--text-dim); margin-bottom: 12px; max-width: 52ch; }
.cpub-transfer-row { display: flex; gap: 10px; align-items: center; }
.cpub-transfer-row .cpub-field-input { flex: 1; }

@media (max-width: 640px) {
  .cpub-hub-settings { padding: 16px; }
  .cpub-field-row { grid-template-columns: 1fr; }
}
</style>
