// apps/reference/src/routes/(app)/admin/audit/+page.svelte
<script lang="ts">
  import AuditLogTable from '$lib/components/admin/AuditLogTable.svelte';
  import { Input, Button } from '@snaplify/ui';
  import type { PageData } from './$types';

  let { data } = $props<{ data: PageData }>();
</script>

<svelte:head>
  <title>Audit Log — Admin</title>
</svelte:head>

<div class="adm-page-header">
  <h1 class="adm-heading">Audit Log</h1>
  <span class="adm-heading-sub">activity tracking</span>
</div>

<form method="get" class="adm-filters">
  <Input
    id="audit-action"
    label="Action"
    name="action"
    value={data.action ?? ''}
    placeholder="Filter by action..."
  />
  <Input
    id="audit-target-type"
    label="Target Type"
    name="targetType"
    value={data.targetType ?? ''}
    placeholder="Filter by target type..."
  />
  <Button type="submit" variant="primary" size="sm">Filter</Button>
</form>

<p class="adm-count">{data.total} log entr{data.total === 1 ? 'y' : 'ies'}</p>

<AuditLogTable logs={data.logs} />

<style>
  .adm-page-header {
    display: flex;
    align-items: baseline;
    gap: var(--space-3, 0.75rem);
    margin-bottom: var(--space-4, 1rem);
    padding-bottom: var(--space-3, 0.75rem);
    border-bottom: 1px solid var(--color-border, #272725);
  }

  .adm-heading {
    font-size: var(--text-xl, 1.25rem);
    font-weight: var(--font-weight-bold, 700);
    color: var(--color-text, #d8d5cf);
    margin: 0;
  }

  .adm-heading-sub {
    font-family: var(--font-mono, monospace);
    font-size: 10px;
    text-transform: uppercase;
    letter-spacing: 0.08em;
    color: var(--color-text-muted, #444440);
  }

  .adm-filters {
    display: flex;
    gap: var(--space-2, 0.5rem);
    margin-bottom: var(--space-4, 1rem);
    flex-wrap: wrap;
    align-items: flex-end;
  }

  .adm-count {
    font-family: var(--font-mono, monospace);
    font-size: 10px;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    color: var(--color-text-muted, #444440);
    margin-bottom: var(--space-3, 0.75rem);
  }
</style>

// apps/reference/pages/admin/audit.vue
<script setup lang="ts">
definePageMeta({ layout: 'admin' });

useSeoMeta({ title: 'Audit Log — Admin — CommonPub' });

const { data: logsData } = await useFetch('/api/admin/audit');

interface AuditEntry {
  id: string;
  action: string;
  actorId: string;
  targetId: string | null;
  metadata: Record<string, unknown> | null;
  createdAt: string;
}

const logs = computed<AuditEntry[]>(() => {
  if (!logsData.value) return [];
  // Handle both { items, total } and array responses
  if (Array.isArray(logsData.value)) return logsData.value as AuditEntry[];
  const data = logsData.value as { items?: AuditEntry[] };
  return data.items ?? [];
});
</script>

<template>
  <div class="admin-audit">
    <h1 class="admin-page-title">Audit Log</h1>

    <table class="admin-table" v-if="logs.length">
      <thead>
        <tr>
          <th>Action</th>
          <th>Actor</th>
          <th>Target</th>
          <th>Time</th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="log in logs" :key="log.id">
          <td class="audit-action">{{ log.action }}</td>
          <td class="audit-id">{{ log.actorId }}</td>
          <td class="audit-id">{{ log.targetId || '—' }}</td>
          <td>{{ new Date(log.createdAt).toLocaleString() }}</td>
        </tr>
      </tbody>
    </table>
    <p class="admin-empty" v-else>No audit log entries.</p>
  </div>
</template>

<style scoped>
.admin-page-title { font-size: var(--text-xl); font-weight: var(--font-weight-bold); margin-bottom: var(--space-6); }
.admin-table { width: 100%; border-collapse: collapse; font-size: var(--text-sm); }
.admin-table th { text-align: left; padding: var(--space-2) var(--space-3); border-bottom: 2px solid var(--border); font-weight: var(--font-weight-semibold); color: var(--text-dim); font-size: var(--text-xs); text-transform: uppercase; letter-spacing: var(--tracking-wide); }
.admin-table td { padding: var(--space-2) var(--space-3); border-bottom: 1px solid var(--border); }
.audit-action { font-weight: var(--font-weight-medium); }
.audit-id { font-family: var(--font-mono); font-size: 11px; color: var(--text-dim); }
.admin-empty { color: var(--text-faint); text-align: center; padding: var(--space-8) 0; }
</style>
