// apps/reference/src/routes/(app)/admin/reports/+page.svelte
<script lang="ts">
  import ReportCard from '$lib/components/admin/ReportCard.svelte';
  import { Textarea, Button } from '@snaplify/ui';
  import type { PageData } from './$types';

  let { data } = $props<{ data: PageData }>();
</script>

<svelte:head>
  <title>Reports — Admin</title>
</svelte:head>

<div class="adm-page-header">
  <h1 class="adm-heading">Reports</h1>
  <span class="adm-heading-sub">moderation</span>
</div>

<form method="get" class="adm-filters">
  <select name="status" aria-label="Filter by status" class="adm-select">
    <option value="">All statuses</option>
    <option value="pending" selected={data.status === 'pending'}>Pending</option>
    <option value="resolved" selected={data.status === 'resolved'}>Resolved</option>
    <option value="dismissed" selected={data.status === 'dismissed'}>Dismissed</option>
  </select>
  <Button type="submit" variant="primary" size="sm">Filter</Button>
</form>

<p class="adm-count">{data.total} report{data.total === 1 ? '' : 's'}</p>

<div class="report-list">
  {#each data.reports as report (report.id)}
    <div class="report-item">
      <ReportCard {report} />
      {#if report.status === 'pending'}
        <form method="post" action="?/resolve" class="resolve-form">
          <input type="hidden" name="reportId" value={report.id} />
          <Textarea
            id={`resolution-${report.id}`}
            label="Resolution"
            name="resolution"
            required
            placeholder="Resolution notes..."
          />
          <div class="resolve-actions">
            <button
              type="submit"
              name="status"
              value="resolved"
              class="resolve-btn resolve-btn--resolve"
            >Resolve</button>
            <button
              type="submit"
              name="status"
              value="dismissed"
              class="resolve-btn resolve-btn--dismiss"
            >Dismiss</button>
          </div>
        </form>
      {/if}
    </div>
  {/each}
  {#if data.reports.length === 0}
    <p class="adm-empty">No reports found.</p>
  {/if}
</div>

<style>
  .adm-page-header {
    display: flex;
    align-items: baseline;
    gap: var(--space-3, 0.75rem);
    margin-bottom: var(--space-4, 1rem);
    padding-bottom: var(--space-3, 0.75rem);
    border-bottom: 1px solid var(--color-border, #272725);
  }

  .adm-heading {
    font-size: var(--text-xl, 1.25rem);
    font-weight: var(--font-weight-bold, 700);
    color: var(--color-text, #d8d5cf);
    margin: 0;
  }

  .adm-heading-sub {
    font-family: var(--font-mono, monospace);
    font-size: 10px;
    text-transform: uppercase;
    letter-spacing: 0.08em;
    color: var(--color-text-muted, #444440);
  }

  .adm-filters {
    display: flex;
    gap: var(--space-2, 0.5rem);
    margin-bottom: var(--space-4, 1rem);
  }

  .adm-select {
    font-family: var(--font-mono, monospace);
    font-size: var(--text-xs, 0.75rem);
    padding: 6px var(--space-2, 0.5rem);
    border: 1px solid var(--color-border, #272725);
    border-radius: var(--radius-sm, 4px);
    background: var(--color-surface, #0c0c0b);
    color: var(--color-text, #d8d5cf);
    cursor: pointer;
  }

  .adm-select:focus {
    outline: none;
    border-color: var(--color-accent, #5b9cf6);
  }

  .adm-count {
    font-family: var(--font-mono, monospace);
    font-size: 10px;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    color: var(--color-text-muted, #444440);
    margin-bottom: var(--space-3, 0.75rem);
  }

  .report-list {
    display: flex;
    flex-direction: column;
    gap: var(--space-3, 0.75rem);
  }

  .report-item {
    display: flex;
    flex-direction: column;
    gap: var(--space-2, 0.5rem);
  }

  .resolve-form {
    display: flex;
    flex-direction: column;
    gap: var(--space-2, 0.5rem);
    padding: var(--space-3, 0.75rem);
    background: var(--color-surface-alt, #141413);
    border: 1px solid var(--color-border, #272725);
    border-radius: var(--radius-sm, 4px);
  }

  .resolve-actions {
    display: flex;
    gap: var(--space-2, 0.5rem);
  }

  .resolve-btn {
    font-family: var(--font-mono, monospace);
    font-size: 10px;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    padding: 4px 12px;
    border: 1px solid var(--color-border, #272725);
    border-radius: var(--radius-sm, 4px);
    cursor: pointer;
  }

  .resolve-btn--resolve {
    background: var(--color-success, #4ade80);
    color: var(--color-bg, #0c0c0b);
    border-color: var(--color-success, #4ade80);
  }

  .resolve-btn--dismiss {
    background: transparent;
    color: var(--color-text-secondary, #888884);
  }

  .resolve-btn--dismiss:hover {
    background: var(--color-surface-alt, #141413);
  }

  .adm-empty {
    font-family: var(--font-mono, monospace);
    font-size: 11px;
    color: var(--color-text-muted, #444440);
    text-align: center;
    padding: var(--space-8, 2rem);
  }
</style>

// apps/reference/pages/admin/reports.vue
<script setup lang="ts">
definePageMeta({ layout: 'admin' });
useSeoMeta({ title: 'Reports — Admin — CommonPub' });

const { data: reportsData, refresh } = await useFetch('/api/admin/reports');
const toast = useToast();

interface Report {
  id: string;
  reason: string;
  description?: string;
  status: string;
  reporterId: string;
  targetType: string;
  targetId: string;
  createdAt: string;
}

const reports = computed<Report[]>(() => {
  if (!reportsData.value) return [];
  if (Array.isArray(reportsData.value)) return reportsData.value as Report[];
  const data = reportsData.value as { items?: Report[] };
  return data.items ?? [];
});

async function resolveReport(id: string, resolution: 'resolved' | 'dismissed'): Promise<void> {
  try {
    await $fetch(`/api/admin/reports/${id}/resolve`, {
      method: 'POST',
      body: { resolution },
    });
    toast.success(`Report ${resolution}`);
    await refresh();
  } catch {
    toast.error('Failed to update report');
  }
}
</script>

<template>
  <div class="admin-reports">
    <h1 class="admin-page-title">Reports</h1>

    <template v-if="reports.length">
      <div class="report-card" v-for="report in reports" :key="report.id">
        <div class="report-header">
          <span class="report-status" :class="`status-${report.status}`">{{ report.status }}</span>
          <span class="report-type">{{ report.targetType }}</span>
          <time class="report-date">{{ new Date(report.createdAt).toLocaleDateString() }}</time>
        </div>
        <p class="report-reason"><strong>{{ report.reason }}</strong></p>
        <p v-if="report.description" class="report-desc">{{ report.description }}</p>
        <div class="report-meta">
          <span class="report-meta-item">Reporter: <code>{{ report.reporterId }}</code></span>
          <span class="report-meta-item">Target: <code>{{ report.targetId }}</code></span>
        </div>
        <div v-if="report.status === 'pending'" class="report-actions">
          <button class="cpub-btn cpub-btn-sm" style="color: var(--green); border-color: var(--green-border);" @click="resolveReport(report.id, 'resolved')">
            <i class="fa-solid fa-check"></i> Resolve
          </button>
          <button class="cpub-btn cpub-btn-sm" @click="resolveReport(report.id, 'dismissed')">
            <i class="fa-solid fa-xmark"></i> Dismiss
          </button>
        </div>
      </div>
    </template>
    <p class="admin-empty" v-else>No reports to review.</p>
  </div>
</template>

<style scoped>
.admin-page-title { font-size: var(--text-xl); font-weight: var(--font-weight-bold); margin-bottom: var(--space-6); }
.report-card { padding: 16px; border: 2px solid var(--border); background: var(--surface); margin-bottom: 12px; box-shadow: 4px 4px 0 var(--border); }
.report-header { display: flex; align-items: center; gap: 10px; margin-bottom: 8px; }
.report-status { font-size: 10px; font-family: var(--font-mono); font-weight: 600; text-transform: uppercase; padding: 2px 8px; }
.status-pending { background: var(--yellow-bg); color: var(--yellow); border: 1px solid var(--yellow-border); }
.status-resolved { background: var(--green-bg); color: var(--green); border: 1px solid var(--green-border); }
.status-dismissed { background: var(--surface2); color: var(--text-faint); border: 1px solid var(--border2); }
.report-type { font-size: 10px; font-family: var(--font-mono); color: var(--accent); background: var(--accent-bg); padding: 2px 6px; border: 1px solid var(--accent-border); }
.report-date { font-size: 11px; color: var(--text-faint); margin-left: auto; font-family: var(--font-mono); }
.report-reason { font-size: 13px; margin-bottom: 4px; }
.report-desc { font-size: 12px; color: var(--text-dim); line-height: 1.5; margin-bottom: 8px; }
.report-meta { display: flex; gap: 16px; margin-bottom: 10px; }
.report-meta-item { font-size: 10px; font-family: var(--font-mono); color: var(--text-faint); }
.report-meta-item code { background: var(--surface2); padding: 1px 4px; }
.report-actions { display: flex; gap: 6px; padding-top: 8px; border-top: 1px solid var(--border2); }
.admin-empty { color: var(--text-faint); text-align: center; padding: var(--space-8) 0; }
</style>
