// apps/reference/src/routes/(app)/create/+page.svelte
<script lang="ts">
  import { enhance } from '$app/forms';
  import ContentEditor from '$lib/components/ContentEditor.svelte';
  import type { ActionData } from './$types';

  let { form }: { form: ActionData } = $props();

  let title = $state(form?.title ?? '');
  let type = $state(form?.type ?? 'project');
  let description = $state(form?.description ?? '');
  let tags = $state('');
  let contentBlocks = $state<unknown[]>([]);

  function handleEditorUpdate(blocks: unknown[]) {
    contentBlocks = blocks;
  }
</script>

<svelte:head>
  <title>Create — Snaplify</title>
</svelte:head>

<div class="create-page">
  <h1>Create Content</h1>

  {#if form?.error}
    <div class="form-error" role="alert">{form.error}</div>
  {/if}

  <form method="POST" use:enhance>
    <div class="form-row">
      <div class="form-field">
        <label for="title">Title</label>
        <input
          id="title"
          name="title"
          type="text"
          bind:value={title}
          required
          maxlength="255"
          placeholder="Give your content a title"
        />
      </div>

      <div class="form-field form-field-type">
        <label for="type">Type</label>
        <select id="type" name="type" bind:value={type}>
          <option value="project">Project</option>
          <option value="article">Article</option>
          <option value="guide">Guide</option>
          <option value="blog">Blog Post</option>
        </select>
      </div>
    </div>

    <div class="form-field">
      <label for="description">Description <span class="optional">(optional)</span></label>
      <textarea
        id="description"
        name="description"
        bind:value={description}
        maxlength="2000"
        rows="2"
        placeholder="A brief summary of your content"
      ></textarea>
    </div>

    <div class="form-field">
      <label for="editor">Content</label>
      <ContentEditor onupdate={handleEditorUpdate} />
      <input type="hidden" name="content" value={JSON.stringify(contentBlocks)} />
    </div>

    <div class="form-field">
      <label for="tags">Tags <span class="optional">(comma-separated)</span></label>
      <input
        id="tags"
        name="tags"
        type="text"
        bind:value={tags}
        placeholder="svelte, electronics, beginner"
      />
    </div>

    <div class="form-actions">
      <button type="submit" name="action" value="draft" class="btn btn-secondary">
        Save Draft
      </button>
      <button type="submit" name="action" value="publish" class="btn btn-primary">
        Publish
      </button>
    </div>
  </form>
</div>

<style>
  .create-page {
    max-width: var(--layout-content-width, 768px);
    margin: 0 auto;
  }

  .create-page h1 {
    font-size: var(--font-size-2xl, 1.875rem);
    margin-bottom: var(--space-lg, 2rem);
    color: var(--color-text, #1a1a1a);
  }

  .form-error {
    padding: var(--space-sm, 0.5rem);
    margin-bottom: var(--space-md, 1rem);
    background: var(--color-error-bg, #fef2f2);
    color: var(--color-error, #dc2626);
    border-radius: var(--radius-sm, 4px);
  }

  .form-row {
    display: flex;
    gap: var(--space-md, 1rem);
  }

  .form-field {
    margin-bottom: var(--space-md, 1rem);
    flex: 1;
  }

  .form-field-type {
    flex: 0 0 180px;
  }

  .form-field label {
    display: block;
    margin-bottom: var(--space-xs, 0.25rem);
    font-size: var(--font-size-sm, 0.875rem);
    font-weight: var(--font-weight-medium, 500);
    color: var(--color-text, #1a1a1a);
  }

  .optional {
    font-weight: var(--font-weight-normal, 400);
    color: var(--color-text-secondary, #666);
  }

  .form-field input,
  .form-field select,
  .form-field textarea {
    width: 100%;
    padding: var(--space-sm, 0.5rem);
    border: 1px solid var(--color-border, #e5e5e5);
    border-radius: var(--radius-sm, 4px);
    font-size: var(--font-size-md, 1rem);
    background: var(--color-surface, #ffffff);
    color: var(--color-text, #1a1a1a);
    box-sizing: border-box;
  }

  .form-actions {
    display: flex;
    gap: var(--space-sm, 0.5rem);
    justify-content: flex-end;
    margin-top: var(--space-lg, 2rem);
  }

  .btn {
    padding: var(--space-sm, 0.5rem) var(--space-lg, 2rem);
    border: none;
    border-radius: var(--radius-md, 6px);
    font-size: var(--font-size-md, 1rem);
    cursor: pointer;
  }

  .btn-primary {
    background: var(--color-primary, #2563eb);
    color: var(--color-on-primary, #ffffff);
  }

  .btn-secondary {
    background: var(--color-surface-secondary, #f5f5f5);
    color: var(--color-text, #1a1a1a);
    border: 1px solid var(--color-border, #e5e5e5);
  }
</style>

// apps/reference/pages/learn/create.vue
<script setup lang="ts">
definePageMeta({ middleware: 'auth' });

useSeoMeta({ title: 'Create Learning Path — CommonPub' });

const title = ref('');
const description = ref('');
const difficulty = ref('beginner');
const saving = ref(false);
const error = ref('');

async function handleCreate(): Promise<void> {
  saving.value = true;
  error.value = '';
  try {
    const result = await $fetch('/api/learn', {
      method: 'POST',
      body: { title: title.value, description: description.value, difficulty: difficulty.value },
    });
    await navigateTo(`/learn/${(result as { slug: string }).slug}`);
  } catch (err: unknown) {
    error.value = (err as { data?: { message?: string } })?.data?.message || 'Failed to create path.';
  } finally {
    saving.value = false;
  }
}
</script>

<template>
  <div class="create-path-page">
    <h1 class="page-title">Create Learning Path</h1>

    <form class="path-form" @submit.prevent="handleCreate" aria-label="Create learning path">
      <div v-if="error" class="form-error" role="alert">{{ error }}</div>

      <div class="form-field">
        <label for="path-title" class="form-label">Title</label>
        <input id="path-title" v-model="title" type="text" class="form-input" required placeholder="Path title" />
      </div>

      <div class="form-field">
        <label for="path-desc" class="form-label">Description</label>
        <textarea id="path-desc" v-model="description" class="form-textarea" rows="3" placeholder="What will learners gain?" />
      </div>

      <div class="form-field">
        <label for="path-diff" class="form-label">Difficulty</label>
        <select id="path-diff" v-model="difficulty" class="form-select">
          <option value="beginner">Beginner</option>
          <option value="intermediate">Intermediate</option>
          <option value="advanced">Advanced</option>
        </select>
      </div>

      <button type="submit" class="cpub-btn-primary" :disabled="saving || !title">
        {{ saving ? 'Creating...' : 'Create Path' }}
      </button>
    </form>
  </div>
</template>

<style scoped>
.create-path-page { max-width: 600px; }
.page-title { font-size: var(--text-xl); font-weight: var(--font-weight-bold); margin-bottom: var(--space-6); }
.path-form { display: flex; flex-direction: column; gap: var(--space-4); }
.form-error { padding: var(--space-3); background: var(--red-bg, var(--surface2)); color: var(--red, var(--text)); border: 1px solid var(--red, var(--border)); font-size: var(--text-sm); }
.form-field { display: flex; flex-direction: column; gap: var(--space-1); }
.form-label { font-size: var(--text-sm); font-weight: var(--font-weight-medium); }
.form-input, .form-textarea, .form-select { padding: var(--space-2) var(--space-3); border: 1px solid var(--border); background: var(--surface); color: var(--text); font-size: var(--text-base); font-family: var(--font-sans); }
.form-input:focus, .form-textarea:focus, .form-select:focus { outline: none; border-color: var(--accent); box-shadow: var(--focus-ring); }
.form-textarea { resize: vertical; }
.cpub-btn-primary { padding: var(--space-2) var(--space-4); background: var(--accent); color: var(--color-on-primary); border: 1px solid var(--border); font-size: var(--text-sm); font-weight: var(--font-weight-medium); font-family: var(--font-sans); cursor: pointer; align-self: flex-start; }
.cpub-btn-primary:disabled { opacity: 0.5; cursor: not-allowed; }
.cpub-btn-primary:focus-visible { outline: 2px solid var(--accent); outline-offset: 2px; }
</style>
