// apps/reference/src/routes/(app)/learn/create/+page.svelte
<script lang="ts">
  import { enhance } from '$app/forms';
  import { Input, Textarea, Button } from '@snaplify/ui';
  import type { ActionData } from './$types';

  let { form }: { form: ActionData & Record<string, unknown> } = $props();
</script>

<svelte:head>
  <title>Create Learning Path — Snaplify</title>
</svelte:head>

<div class="create-page">
  <h1>Create Learning Path</h1>

  {#if form?.error}
    <div class="form-error" role="alert">{form.error}</div>
  {/if}

  <form method="POST" use:enhance>
    <Input id="title" label="Title" name="title" value={String(form?.title ?? '')} required />

    <Textarea id="description" label="Description" name="description" rows={3} value={String(form?.description ?? '')} />

    <div class="form-row">
      <div class="form-field">
        <label for="difficulty">Difficulty</label>
        <select id="difficulty" name="difficulty">
          <option value="">Select...</option>
          <option value="beginner" selected={form?.difficulty === 'beginner'}>Beginner</option>
          <option value="intermediate" selected={form?.difficulty === 'intermediate'}
            >Intermediate</option
          >
          <option value="advanced" selected={form?.difficulty === 'advanced'}>Advanced</option>
        </select>
      </div>

      <Input id="estimatedHours" label="Estimated Hours" name="estimatedHours" type="number" />
    </div>

    <div class="form-actions">
      <Button variant="primary" type="submit">Create & Edit</Button>
    </div>
  </form>
</div>

<style>
  .create-page {
    max-width: var(--layout-content-width, 640px);
    margin: 0 auto;
  }

  .create-page h1 {
    font-size: var(--text-2xl, 1.875rem);
    margin-bottom: var(--space-6, 2rem);
    color: var(--color-text, #d8d5cf);
  }

  .form-error {
    padding: var(--space-2, 0.5rem);
    margin-bottom: var(--space-4, 1rem);
    background: var(--color-error-bg, #fef2f2);
    color: var(--color-error, #dc2626);
    border-radius: var(--radius-sm, 4px);
  }

  .form-field {
    margin-bottom: var(--space-4, 1rem);
  }

  .form-field label {
    display: block;
    margin-bottom: var(--space-1, 0.25rem);
    font-size: var(--text-sm, 0.875rem);
    font-weight: var(--font-weight-medium, 500);
    color: var(--color-text, #d8d5cf);
  }

  .form-field select {
    width: 100%;
    padding: var(--space-2, 0.5rem);
    border: 1px solid var(--color-border, #272725);
    border-radius: var(--radius-sm, 4px);
    font-size: var(--text-md, 1rem);
    background: var(--color-surface, #0c0c0b);
    color: var(--color-text, #d8d5cf);
    box-sizing: border-box;
  }

  .form-row {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: var(--space-4, 1rem);
  }

  .form-actions {
    margin-top: var(--space-6, 2rem);
  }

</style>

// apps/reference/pages/learn/create.vue
<script setup lang="ts">
definePageMeta({ middleware: 'auth' });

useSeoMeta({ title: 'Create Learning Path — CommonPub' });

const toast = useToast();
const { extract: extractError } = useApiError();
const title = ref('');
const description = ref('');
const difficulty = ref('beginner');
const saving = ref(false);

async function handleCreate(): Promise<void> {
  saving.value = true;
  try {
    const result = await $fetch('/api/learn', {
      method: 'POST',
      body: { title: title.value, description: description.value, difficulty: difficulty.value },
    });
    await navigateTo(`/learn/${(result as { slug: string }).slug}/edit`);
  } catch (err: unknown) {
    toast.error(extractError(err));
  } finally {
    saving.value = false;
  }
}
</script>

<template>
  <div class="create-path-page">
    <h1 class="page-title">Create Learning Path</h1>

    <form class="path-form" @submit.prevent="handleCreate" aria-label="Create learning path">
      <div class="form-field">
        <label for="path-title" class="form-label">Title</label>
        <input id="path-title" v-model="title" type="text" class="form-input" required placeholder="Path title" />
      </div>

      <div class="form-field">
        <label for="path-desc" class="form-label">Description</label>
        <textarea id="path-desc" v-model="description" class="form-textarea" rows="3" placeholder="What will learners gain?" />
      </div>

      <div class="form-field">
        <label for="path-diff" class="form-label">Difficulty</label>
        <select id="path-diff" v-model="difficulty" class="form-select">
          <option value="beginner">Beginner</option>
          <option value="intermediate">Intermediate</option>
          <option value="advanced">Advanced</option>
        </select>
      </div>

      <button type="submit" class="cpub-btn cpub-btn-primary" :disabled="saving || !title">
        {{ saving ? 'Creating...' : 'Create Path' }}
      </button>
    </form>
  </div>
</template>

<style scoped>
.create-path-page { max-width: 600px; }
.page-title { font-size: var(--text-xl); font-weight: var(--font-weight-bold); margin-bottom: var(--space-6); }
.path-form { display: flex; flex-direction: column; gap: var(--space-4); }
.form-field { display: flex; flex-direction: column; gap: var(--space-1); }
.form-label { font-size: var(--text-sm); font-weight: var(--font-weight-medium); }
.form-input, .form-textarea, .form-select { padding: var(--space-2) var(--space-3); border: 1px solid var(--border); background: var(--surface); color: var(--text); font-size: var(--text-base); font-family: var(--font-sans); }
.form-input:focus, .form-textarea:focus, .form-select:focus { outline: none; border-color: var(--accent); box-shadow: var(--focus-ring); }
.form-textarea { resize: vertical; }
/* cpub-btn, cpub-btn-primary → global components.css */
</style>
