// packages/ui/src/components/Badge.svelte
<script lang="ts">
  interface Props {
    variant?: 'default' | 'primary' | 'success' | 'warning' | 'danger';
    size?: 'sm' | 'md';
    class?: string;
    text: string;
  }

  let { variant = 'default', size = 'md', class: className = '', text }: Props = $props();
</script>

<span
  class={['snaplify-badge', `snaplify-badge--${variant}`, `snaplify-badge--${size}`, className]
    .filter(Boolean)
    .join(' ')}
>
  {text}
</span>

<style>
  .snaplify-badge {
    display: inline-flex;
    align-items: center;
    font-family: var(--font-body, sans-serif);
    font-weight: var(--font-weight-medium, 500);
    border-radius: var(--radius-full, 9999px);
    line-height: 1;
  }

  .snaplify-badge--sm {
    padding: var(--space-0-5, 0.125rem) var(--space-1-5, 0.375rem);
    font-size: var(--text-xs);
  }

  .snaplify-badge--md {
    padding: var(--space-1, 0.25rem) var(--space-2, 0.5rem);
    font-size: var(--text-sm);
  }

  .snaplify-badge--default {
    background: var(--color-surface-alt);
    color: var(--color-text-secondary, #64748b);
  }

  .snaplify-badge--primary {
    background: var(--color-primary, #3b82f6);
    color: var(--color-primary-text, #fff);
  }

  .snaplify-badge--success {
    background: var(--color-success, #22c55e);
    color: var(--color-success-text, #fff);
  }

  .snaplify-badge--warning {
    background: var(--color-warning, #f59e0b);
    color: var(--color-warning-text, #000);
  }

  .snaplify-badge--danger {
    background: var(--color-error, #ef4444);
    color: var(--color-error-text, #fff);
  }
</style>

// packages/ui/src/components/Badge.vue
<script setup lang="ts">
defineOptions({ name: 'CpubBadge', inheritAttrs: false });

interface Props {
  variant?: 'default' | 'accent' | 'green' | 'red' | 'yellow' | 'purple' | 'teal' | 'pink' | 'outline';
  size?: 'sm' | 'md';
}

const props = withDefaults(defineProps<Props>(), {
  variant: 'default',
  size: 'sm',
});
</script>

<template>
  <span
    v-bind="$attrs"
    :class="[
      'cpub-badge',
      `cpub-badge--${props.variant}`,
      `cpub-badge--${props.size}`,
    ]"
  >
    <slot />
  </span>
</template>

<style scoped>
.cpub-badge {
  display: inline-flex;
  align-items: center;
  font-family: var(--font-mono);
  text-transform: uppercase;
  letter-spacing: var(--tracking-wider);
  font-weight: var(--font-weight-medium);
  border-radius: var(--radius);
  white-space: nowrap;
  line-height: 1;
}

/* Sizes */
.cpub-badge--sm {
  font-size: var(--text-xs);
  padding: var(--space-1) var(--space-2);
}

.cpub-badge--md {
  font-size: var(--text-sm);
  padding: var(--space-1) var(--space-3);
}

/* Variants */
.cpub-badge--default {
  background-color: var(--surface3);
  color: var(--text);
}

.cpub-badge--accent {
  background-color: var(--accent-bg);
  color: var(--accent);
}

.cpub-badge--green {
  background-color: var(--green-bg);
  color: var(--green-text);
}

.cpub-badge--red {
  background-color: var(--red-bg);
  color: var(--red-text);
}

.cpub-badge--yellow {
  background-color: var(--yellow-bg);
  color: var(--yellow-text);
}

.cpub-badge--purple {
  background-color: var(--purple-bg);
  color: var(--purple-text);
}

.cpub-badge--teal {
  background-color: var(--teal-bg);
  color: var(--teal-text);
}

.cpub-badge--pink {
  background-color: var(--pink-bg);
  color: var(--pink-text);
}

.cpub-badge--outline {
  background-color: transparent;
  color: var(--text);
  border: var(--border-width-thin) solid var(--border2);
}
</style>
