// packages/ui/src/components/MenuItem.svelte
<script lang="ts">
  interface Props {
    disabled?: boolean;
    class?: string;
    onclick?: () => void;
    label: string;
  }

  let { disabled = false, class: className = '', onclick, label }: Props = $props();

  function handleClick(): void {
    if (!disabled) onclick?.();
  }

  function handleKeydown(e: KeyboardEvent): void {
    if ((e.key === 'Enter' || e.key === ' ') && !disabled) {
      e.preventDefault();
      onclick?.();
    }
  }
</script>

<div
  class={['snaplify-menu-item', className].filter(Boolean).join(' ')}
  role="menuitem"
  tabindex={disabled ? -1 : 0}
  aria-disabled={disabled}
  onclick={handleClick}
  onkeydown={handleKeydown}
>
  {label}
</div>

<style>
  .snaplify-menu-item {
    padding: var(--space-2, 0.5rem) var(--space-3, 0.75rem);
    font-family: var(--font-body, sans-serif);
    font-size: var(--text-base);
    color: var(--color-text, #1a1a1a);
    cursor: pointer;
    outline: none;
  }

  .snaplify-menu-item:focus-visible {
    background: var(--color-surface-raised);
  }

  .snaplify-menu-item:hover {
    background: var(--color-surface-raised);
  }

  .snaplify-menu-item[aria-disabled='true'] {
    opacity: 0.5;
    cursor: not-allowed;
  }
</style>

// packages/ui/src/components/MenuItem.vue
<script setup lang="ts">
defineOptions({ name: 'CpubMenuItem', inheritAttrs: false });

interface Props {
  disabled?: boolean;
}

const props = withDefaults(defineProps<Props>(), {
  disabled: false,
});

const emit = defineEmits<{
  select: [];
}>();

function handleClick(): void {
  if (!props.disabled) {
    emit('select');
  }
}

function handleKeydown(event: KeyboardEvent): void {
  if (event.key === 'Enter' || event.key === ' ') {
    event.preventDefault();
    handleClick();
  }
}
</script>

<template>
  <div
    v-bind="$attrs"
    :class="['cpub-menu-item', { 'cpub-menu-item--disabled': props.disabled }]"
    role="menuitem"
    :tabindex="props.disabled ? -1 : 0"
    :aria-disabled="props.disabled || undefined"
    @click="handleClick"
    @keydown="handleKeydown"
  >
    <slot />
  </div>
</template>

<style scoped>
.cpub-menu-item {
  display: flex;
  align-items: center;
  gap: var(--space-2);
  padding: var(--space-2) var(--space-3);
  font-family: var(--font-body);
  font-size: var(--text-sm);
  color: var(--text);
  cursor: pointer;
  transition: background-color var(--transition-fast);
  white-space: nowrap;
}

.cpub-menu-item:hover:not(.cpub-menu-item--disabled) {
  background-color: var(--surface2);
}

.cpub-menu-item:focus-visible {
  outline: none;
  box-shadow: var(--shadow-accent);
}

.cpub-menu-item--disabled {
  opacity: 0.5;
  cursor: not-allowed;
}
</style>
