// apps/reference/src/lib/components/learning/ProgressBar.svelte
<script lang="ts">
  let {
    value = 0,
    label = 'Progress',
  }: {
    value?: number;
    label?: string;
  } = $props();

  const clampedValue = Math.min(100, Math.max(0, value));
</script>

<div
  class="progress-bar"
  role="progressbar"
  aria-valuenow={clampedValue}
  aria-valuemin={0}
  aria-valuemax={100}
  aria-label={label}
>
  <div class="progress-fill" style="width: {clampedValue}%"></div>
  <span class="progress-text">{Math.round(clampedValue)}%</span>
</div>

<style>
  .progress-bar {
    position: relative;
    height: 24px;
    background: var(--color-surface-alt, #1c1c1a);
    border-radius: var(--radius-sm, 4px);
    overflow: hidden;
    margin: var(--space-2, 0.5rem) 0;
  }

  .progress-fill {
    height: 100%;
    background: var(--color-primary, #2563eb);
    border-radius: var(--radius-sm, 4px);
    transition: width 0.3s ease;
  }

  .progress-text {
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    font-size: var(--text-xs, 0.75rem);
    font-weight: var(--font-weight-medium, 500);
    color: var(--color-text, #d8d5cf);
  }
</style>

// packages/ui/src/components/ProgressBar.vue
<script setup lang="ts">
import { computed } from 'vue';

defineOptions({ name: 'CpubProgressBar' });

interface Props {
  value: number;
  max?: number;
  variant?: 'accent' | 'green' | 'yellow' | 'red';
}

const props = withDefaults(defineProps<Props>(), {
  max: 100,
  variant: 'accent',
});

const percentage = computed(() => {
  const clamped = Math.min(Math.max(props.value, 0), props.max);
  return (clamped / props.max) * 100;
});
</script>

<template>
  <div
    v-bind="$attrs"
    class="cpub-progress"
    role="progressbar"
    :aria-valuenow="props.value"
    :aria-valuemin="0"
    :aria-valuemax="props.max"
  >
    <div
      :class="['cpub-progress__fill', `cpub-progress__fill--${props.variant}`]"
      :style="{ width: `${percentage}%` }"
    />
  </div>
</template>

<style scoped>
.cpub-progress {
  width: 100%;
  height: 6px;
  background-color: var(--surface3);
  border-radius: var(--radius);
  overflow: hidden;
}

.cpub-progress__fill {
  height: 100%;
  transition: width var(--transition-default);
  border-radius: var(--radius);
}

.cpub-progress__fill--accent {
  background-color: var(--accent);
}

.cpub-progress__fill--green {
  background-color: var(--green);
}

.cpub-progress__fill--yellow {
  background-color: var(--yellow);
}

.cpub-progress__fill--red {
  background-color: var(--red);
}
</style>
