// packages/ui/src/components/Tabs.svelte
<script lang="ts">
  interface Tab {
    id: string;
    label: string;
  }

  interface Props {
    tabs: Tab[];
    activeTab?: string;
    class?: string;
    onchange?: (tabId: string) => void;
  }

  let {
    tabs,
    activeTab = $bindable(tabs[0]?.id ?? ''),
    class: className = '',
    onchange,
  }: Props = $props();

  function selectTab(tabId: string): void {
    activeTab = tabId;
    onchange?.(tabId);
  }

  function handleKeydown(e: KeyboardEvent): void {
    const currentIndex = tabs.findIndex((t) => t.id === activeTab);
    let newIndex = currentIndex;

    switch (e.key) {
      case 'ArrowRight':
        e.preventDefault();
        newIndex = (currentIndex + 1) % tabs.length;
        break;
      case 'ArrowLeft':
        e.preventDefault();
        newIndex = (currentIndex - 1 + tabs.length) % tabs.length;
        break;
      case 'Home':
        e.preventDefault();
        newIndex = 0;
        break;
      case 'End':
        e.preventDefault();
        newIndex = tabs.length - 1;
        break;
      default:
        return;
    }

    const tab = tabs[newIndex];
    if (tab) {
      selectTab(tab.id);
      // Focus the new tab button
      const tabEl = document.getElementById(`tab-${tab.id}`);
      tabEl?.focus();
    }
  }
</script>

<div class={['snaplify-tabs', className].filter(Boolean).join(' ')}>
  <div class="snaplify-tablist" role="tablist" onkeydown={handleKeydown}>
    {#each tabs as tab}
      <button
        id={`tab-${tab.id}`}
        type="button"
        class="snaplify-tab"
        class:snaplify-tab--active={tab.id === activeTab}
        role="tab"
        aria-selected={tab.id === activeTab}
        aria-controls={`panel-${tab.id}`}
        tabindex={tab.id === activeTab ? 0 : -1}
        onclick={() => selectTab(tab.id)}
      >
        {tab.label}
      </button>
    {/each}
  </div>

  {#each tabs as tab}
    <div
      id={`panel-${tab.id}`}
      class="snaplify-tabpanel"
      role="tabpanel"
      aria-labelledby={`tab-${tab.id}`}
      hidden={tab.id !== activeTab}
      tabindex={0}
    ></div>
  {/each}
</div>

<style>
  .snaplify-tabs {
    display: flex;
    flex-direction: column;
  }

  .snaplify-tablist {
    display: flex;
    gap: 0;
    border-bottom: 1px solid var(--color-border, #e2e8f0);
  }

  .snaplify-tab {
    padding: var(--space-2, 0.5rem) var(--space-4, 1rem);
    font-family: var(--font-body, sans-serif);
    font-size: var(--text-base);
    background: transparent;
    border: none;
    border-bottom: 2px solid transparent;
    color: var(--color-text-secondary, #64748b);
    cursor: pointer;
    transition: var(--transition-default, 150ms ease);
    margin-bottom: -1px;
  }

  .snaplify-tab:focus-visible {
    outline: var(--focus-ring, 2px solid currentColor);
    outline-offset: -2px;
  }

  .snaplify-tab--active {
    color: var(--color-primary, #3b82f6);
    border-bottom-color: var(--color-primary, #3b82f6);
    font-weight: var(--font-weight-medium, 500);
  }

  .snaplify-tabpanel {
    padding: var(--space-4, 1rem) 0;
  }

  .snaplify-tabpanel[hidden] {
    display: none;
  }
</style>

// packages/ui/src/components/Tabs.vue
<script setup lang="ts">
defineOptions({ name: 'CpubTabs' });

interface Tab {
  id: string;
  label: string;
}

interface Props {
  tabs: Tab[];
  modelValue: string;
}

const props = defineProps<Props>();

const emit = defineEmits<{
  'update:modelValue': [value: string];
}>();

function selectTab(id: string): void {
  emit('update:modelValue', id);
}

function handleKeydown(event: KeyboardEvent, index: number): void {
  let newIndex = index;

  if (event.key === 'ArrowRight') {
    event.preventDefault();
    newIndex = index < props.tabs.length - 1 ? index + 1 : 0;
  } else if (event.key === 'ArrowLeft') {
    event.preventDefault();
    newIndex = index > 0 ? index - 1 : props.tabs.length - 1;
  } else if (event.key === 'Home') {
    event.preventDefault();
    newIndex = 0;
  } else if (event.key === 'End') {
    event.preventDefault();
    newIndex = props.tabs.length - 1;
  } else {
    return;
  }

  const tab = props.tabs[newIndex]!;
  selectTab(tab.id);

  const tabEl = (event.currentTarget as HTMLElement)
    .parentElement
    ?.querySelectorAll('[role="tab"]')[newIndex] as HTMLElement | undefined;
  tabEl?.focus();
}
</script>

<template>
  <div class="cpub-tabs">
    <div class="cpub-tabs__list" role="tablist">
      <button
        v-for="(tab, index) in props.tabs"
        :key="tab.id"
        role="tab"
        :aria-selected="props.modelValue === tab.id"
        :tabindex="props.modelValue === tab.id ? 0 : -1"
        :class="['cpub-tabs__tab', { 'cpub-tabs__tab--active': props.modelValue === tab.id }]"
        @click="selectTab(tab.id)"
        @keydown="handleKeydown($event, index)"
      >
        {{ tab.label }}
      </button>
    </div>
    <div class="cpub-tabs__panel" role="tabpanel">
      <slot />
    </div>
  </div>
</template>

<style scoped>
.cpub-tabs__list {
  display: flex;
  border-bottom: var(--border-width-default) solid var(--border2);
  gap: 0;
}

.cpub-tabs__tab {
  font-family: var(--font-mono);
  font-size: var(--text-label);
  text-transform: uppercase;
  letter-spacing: var(--tracking-wider);
  color: var(--text-dim);
  background: none;
  border: none;
  border-bottom: var(--border-width-default) solid transparent;
  padding: var(--space-3) var(--space-4);
  cursor: pointer;
  transition: color var(--transition-fast), border-color var(--transition-fast);
  margin-bottom: calc(-1 * var(--border-width-default));
  font-weight: var(--font-weight-medium);
}

.cpub-tabs__tab:hover {
  color: var(--text);
}

.cpub-tabs__tab--active {
  color: var(--text);
  border-bottom-color: var(--accent);
}

.cpub-tabs__tab:focus-visible {
  outline: none;
  box-shadow: var(--shadow-accent);
}

.cpub-tabs__panel {
  padding: var(--space-4) 0;
}
</style>
