// packages/ui/src/components/Textarea.svelte
<script lang="ts">
  interface Props {
    id: string;
    label: string;
    value?: string;
    name?: string;
    placeholder?: string;
    rows?: number;
    maxlength?: number;
    error?: string;
    disabled?: boolean;
    required?: boolean;
    class?: string;
    oninput?: (e: Event) => void;
  }

  let {
    id,
    label,
    value = $bindable(''),
    name,
    placeholder = '',
    rows = 4,
    maxlength,
    error = '',
    disabled = false,
    required = false,
    class: className = '',
    oninput,
  }: Props = $props();

  const errorId = $derived(error ? `${id}-error` : undefined);
</script>

<div class={['snaplify-textarea-group', className].filter(Boolean).join(' ')}>
  <label class="snaplify-textarea-label" for={id}>{label}</label>
  <textarea
    class="snaplify-textarea"
    {id}
    name={name ?? undefined}
    {placeholder}
    {rows}
    maxlength={maxlength ?? undefined}
    {disabled}
    {required}
    bind:value
    aria-invalid={error ? true : undefined}
    aria-describedby={errorId}
    {oninput}
  ></textarea>
  {#if error}
    <p class="snaplify-textarea-error" id={errorId} role="alert">{error}</p>
  {/if}
</div>

<style>
  .snaplify-textarea-group {
    display: flex;
    flex-direction: column;
    gap: var(--space-1, 0.25rem);
  }

  .snaplify-textarea-label {
    font-family: var(--font-body, sans-serif);
    font-size: var(--text-sm);
    font-weight: var(--font-weight-medium, 500);
    color: var(--color-text, #1a1a1a);
  }

  .snaplify-textarea {
    font-family: var(--font-body, sans-serif);
    font-size: var(--text-base);
    padding: var(--space-2, 0.5rem) var(--space-3, 0.75rem);
    border: 1px solid var(--color-border, #e2e8f0);
    border-radius: var(--radius-md, 0.375rem);
    background: var(--color-surface, #fff);
    color: var(--color-text, #1a1a1a);
    resize: vertical;
    transition: var(--transition-default, 150ms ease);
  }

  .snaplify-textarea:focus-visible {
    outline: var(--focus-ring, 2px solid currentColor);
    outline-offset: 2px;
  }

  .snaplify-textarea[aria-invalid='true'] {
    border-color: var(--color-error, #ef4444);
  }

  .snaplify-textarea:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }

  .snaplify-textarea-error {
    font-family: var(--font-body, sans-serif);
    font-size: var(--text-sm);
    color: var(--color-error, #ef4444);
    margin: 0;
  }
</style>

// packages/ui/src/components/Textarea.vue
<script setup lang="ts">
import { computed, useAttrs } from 'vue';

defineOptions({ name: 'CpubTextarea', inheritAttrs: false });

interface Props {
  label?: string;
  error?: string;
  hint?: string;
  modelValue?: string;
  rows?: number;
}

const props = withDefaults(defineProps<Props>(), {
  label: undefined,
  error: undefined,
  hint: undefined,
  modelValue: '',
  rows: 4,
});

const emit = defineEmits<{
  'update:modelValue': [value: string];
}>();

const attrs = useAttrs();

const textareaId = computed(() => (attrs.id as string) || `cpub-textarea-${Math.random().toString(36).slice(2, 9)}`);
const errorId = computed(() => props.error ? `${textareaId.value}-error` : undefined);
const hintId = computed(() => props.hint ? `${textareaId.value}-hint` : undefined);

const describedBy = computed(() => {
  const ids: string[] = [];
  if (errorId.value) ids.push(errorId.value);
  if (hintId.value) ids.push(hintId.value);
  return ids.length ? ids.join(' ') : undefined;
});

function onInput(event: Event): void {
  const target = event.target as HTMLTextAreaElement;
  emit('update:modelValue', target.value);
}
</script>

<template>
  <div :class="['cpub-textarea-group', { 'cpub-textarea-group--error': props.error }]">
    <label
      v-if="props.label"
      :for="textareaId"
      class="cpub-textarea-group__label"
    >
      {{ props.label }}
    </label>
    <textarea
      v-bind="attrs"
      :id="textareaId"
      class="cpub-textarea"
      :value="props.modelValue"
      :rows="props.rows"
      :aria-invalid="props.error ? true : undefined"
      :aria-describedby="describedBy"
      @input="onInput"
    />
    <p v-if="props.error" :id="errorId" class="cpub-textarea-group__error" role="alert">
      {{ props.error }}
    </p>
    <p v-if="props.hint && !props.error" :id="hintId" class="cpub-textarea-group__hint">
      {{ props.hint }}
    </p>
  </div>
</template>

<style scoped>
.cpub-textarea-group {
  display: flex;
  flex-direction: column;
  gap: var(--space-1);
}

.cpub-textarea-group__label {
  font-family: var(--font-mono);
  font-size: var(--text-label);
  text-transform: uppercase;
  letter-spacing: var(--tracking-wider);
  color: var(--text);
  font-weight: var(--font-weight-medium);
}

.cpub-textarea {
  font-family: var(--font-body);
  font-size: var(--text-base);
  color: var(--text);
  background-color: var(--surface);
  border: var(--border-width-default) solid var(--border);
  border-radius: var(--radius);
  padding: var(--space-2) var(--space-3);
  transition: box-shadow var(--transition-fast);
  width: 100%;
  resize: vertical;
}

.cpub-textarea::placeholder {
  color: var(--text-faint);
}

.cpub-textarea:focus {
  outline: none;
  box-shadow: var(--shadow-accent);
}

.cpub-textarea-group--error .cpub-textarea {
  border-color: var(--red);
}

.cpub-textarea-group--error .cpub-textarea:focus {
  box-shadow: 4px 4px 0 var(--red);
}

.cpub-textarea-group__error {
  font-size: var(--text-sm);
  color: var(--red);
  margin: 0;
}

.cpub-textarea-group__hint {
  font-size: var(--text-sm);
  color: var(--text-dim);
  margin: 0;
}
</style>
