// apps/reference/src/routes/(app)/u/[username]/+page.svelte
<script lang="ts">
  import ContentCard from '$lib/components/ContentCard.svelte';
  import { Avatar, Badge, Button } from '@snaplify/ui';
  import type { PageData } from './$types';

  let { data }: { data: PageData } = $props();

  const tabs = [
    { key: 'projects', label: 'Projects', count: data.profile.stats.projects },
    { key: 'guides', label: 'Guides', count: data.profile.stats.guides },
    { key: 'explainers', label: 'Explainers', count: data.profile.stats.explainers },
    { key: 'articles', label: 'Articles', count: data.profile.stats.articles },
  ];
</script>

<svelte:head>
  <title>{data.profile.displayName ?? data.profile.username} — Snaplify</title>
</svelte:head>

<div class="profile-page">
  <header class="profile-header">
    <div class="profile-banner"></div>
    <div class="profile-info">
      <div class="profile-avatar-wrap">
        <Avatar
          src={data.profile.avatarUrl ?? undefined}
          alt={data.profile.displayName ?? data.profile.username ?? ''}
          name={data.profile.displayName ?? data.profile.username ?? '?'}
          size="xl"
        />
      </div>
      <div class="profile-details">
        <div class="profile-name-row">
          <h1 class="profile-name">{data.profile.displayName ?? data.profile.username}</h1>
          {#if data.isOwnProfile}
            <a href="/dashboard/settings"><Button variant="secondary" size="sm">Edit Profile</Button></a>
          {:else}
            <Button variant="primary" size="sm">Follow</Button>
          {/if}
        </div>
        <span class="profile-handle">@{data.profile.username}</span>
        {#if data.profile.bio}
          <p class="profile-bio">{data.profile.bio}</p>
        {/if}
      </div>
    </div>
  </header>

  <div class="profile-stats">
    <div class="stat">
      <span class="stat-value">{data.profile.stats.projects}</span>
      <span class="stat-label">Projects</span>
    </div>
    <div class="stat">
      <span class="stat-value">{data.profile.stats.guides}</span>
      <span class="stat-label">Guides</span>
    </div>
    <div class="stat">
      <span class="stat-value">{data.profile.stats.explainers}</span>
      <span class="stat-label">Explainers</span>
    </div>
    <div class="stat">
      <span class="stat-value">{data.profile.stats.followers}</span>
      <span class="stat-label">Followers</span>
    </div>
    <div class="stat">
      <span class="stat-value">{data.profile.stats.following}</span>
      <span class="stat-label">Following</span>
    </div>
  </div>

  <nav class="profile-tabs" aria-label="Profile content tabs">
    {#each tabs as tab}
      <a
        href="/u/{data.profile.username}?tab={tab.key}"
        class="profile-tab"
        class:profile-tab-active={data.tab === tab.key}
        aria-current={data.tab === tab.key ? 'page' : undefined}
      >
        {tab.label}
        {#if tab.count > 0}
          <span class="tab-count">{tab.count}</span>
        {/if}
      </a>
    {/each}
  </nav>

  {#if data.items.length === 0}
    <div class="empty-state">
      <p>No {data.tab} yet.</p>
    </div>
  {:else}
    <div class="content-grid">
      {#each data.items as item (item.id)}
        <ContentCard {item} />
      {/each}
    </div>
  {/if}
</div>

<style>
  .profile-page {
    max-width: 960px;
    margin: 0 auto;
    display: flex;
    flex-direction: column;
    gap: var(--space-6, 1.5rem);
  }

  .profile-header {
    position: relative;
  }

  .profile-banner {
    height: 160px;
    background: linear-gradient(135deg, var(--color-surface-raised, #1c1c1a), var(--color-surface-alt, #141413));
    border-radius: var(--radius-lg, 0.5rem);
    border: 1px solid var(--color-border, #272725);
  }

  .profile-info {
    display: flex;
    gap: var(--space-4, 1rem);
    padding: 0 var(--space-4, 1rem);
    margin-top: -40px;
  }

  .profile-avatar-wrap {
    flex-shrink: 0;
    border: 3px solid var(--color-surface, #0c0c0b);
    border-radius: var(--radius-full, 50%);
    overflow: hidden;
  }

  .profile-details {
    flex: 1;
    padding-top: 48px;
  }

  .profile-name-row {
    display: flex;
    align-items: center;
    gap: var(--space-3, 0.75rem);
  }

  .profile-name {
    font-size: var(--text-2xl, 1.5rem);
    font-weight: var(--font-weight-bold, 700);
    color: var(--color-text, #d8d5cf);
    margin: 0;
  }

  .profile-handle {
    font-family: var(--font-mono, monospace);
    font-size: var(--text-sm, 0.75rem);
    color: var(--color-text-muted, #444440);
  }

  .profile-bio {
    font-size: var(--text-sm, 0.75rem);
    color: var(--color-text-secondary, #888884);
    margin: var(--space-2, 0.5rem) 0 0;
    line-height: var(--leading-normal, 1.6);
  }

  .profile-stats {
    display: flex;
    gap: var(--space-6, 1.5rem);
    padding: var(--space-4, 1rem);
    border: 1px solid var(--color-border, #272725);
    border-radius: var(--radius-md, 0.25rem);
    background: var(--color-surface-alt, #141413);
  }

  .stat {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: var(--space-1, 0.25rem);
  }

  .stat-value {
    font-size: var(--text-lg, 1.125rem);
    font-weight: var(--font-weight-bold, 700);
    color: var(--color-text, #d8d5cf);
  }

  .stat-label {
    font-family: var(--font-mono, monospace);
    font-size: var(--text-xs, 0.6875rem);
    text-transform: uppercase;
    letter-spacing: 0.05em;
    color: var(--color-text-muted, #444440);
  }

  .profile-tabs {
    display: flex;
    gap: 0;
    border-bottom: 1px solid var(--color-border, #272725);
  }

  .profile-tab {
    padding: var(--space-3, 0.75rem) var(--space-4, 1rem);
    text-decoration: none;
    color: var(--color-text-secondary, #888884);
    border-bottom: 2px solid transparent;
    font-size: var(--text-sm, 0.75rem);
    font-family: var(--font-mono, monospace);
    text-transform: uppercase;
    letter-spacing: 0.05em;
    display: flex;
    align-items: center;
    gap: var(--space-2, 0.5rem);
    transition: color var(--transition-fast, 0.1s ease);
  }

  .profile-tab:hover {
    color: var(--color-text, #d8d5cf);
  }

  .profile-tab-active {
    color: var(--color-primary, #5b9cf6);
    border-bottom-color: var(--color-primary, #5b9cf6);
  }

  .tab-count {
    font-size: var(--text-xs, 0.6875rem);
    background: var(--color-surface-raised, #1c1c1a);
    padding: 0 var(--space-2, 0.5rem);
    border-radius: var(--radius-md, 0.25rem);
    color: var(--color-text-muted, #444440);
  }

  .content-grid {
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    gap: var(--space-4, 1rem);
  }

  .empty-state {
    text-align: center;
    padding: var(--space-12, 3rem);
    color: var(--color-text-secondary, #888884);
  }

  @media (max-width: 768px) {
    .content-grid {
      grid-template-columns: repeat(2, 1fr);
    }

    .profile-stats {
      flex-wrap: wrap;
      justify-content: center;
    }
  }

  @media (max-width: 480px) {
    .content-grid {
      grid-template-columns: 1fr;
    }
  }
</style>

// apps/reference/pages/u/[username]/index.vue
<script setup lang="ts">
const route = useRoute();
const username = route.params.username as string;

useSeoMeta({
  title: `${username} — CommonPub`,
});

import type { Serialized, UserProfile } from '@commonpub/server';

const { data: profile, pending: profilePending, error: profileError, refresh: refreshProfile } = useLazyFetch<Serialized<UserProfile>>(`/api/users/${username}`);
const { data: content } = useLazyFetch(`/api/users/${username}/content`);
const { data: learningData } = useLazyFetch(`/api/users/${username}/learning`);

const activeTab = ref('projects');

const tabDefs = [
  { value: 'projects', label: 'Projects', icon: 'fa-solid fa-folder-open' },
  { value: 'articles', label: 'Articles', icon: 'fa-solid fa-newspaper' },
  { value: 'explainers', label: 'Explainers', icon: 'fa-solid fa-book-open' },
  { value: 'learning', label: 'Learning', icon: 'fa-solid fa-graduation-cap' },
  { value: 'about', label: 'About', icon: 'fa-solid fa-id-card' },
];

const profileStats = computed(() => {
  if (!profile.value) return [];
  const p = profile.value;
  return [
    { value: p.stats?.projects ?? 0, label: 'Projects' },
    { value: p.followerCount ?? p.stats?.followers ?? 0, label: 'Followers' },
    { value: p.followingCount ?? p.stats?.following ?? 0, label: 'Following' },
    { value: p.stats?.articles ?? 0, label: 'Articles' },
    { value: p.viewCount ?? 0, label: 'Total Views' },
    { value: p.likeCount ?? 0, label: 'Likes' },
  ];
});

const filteredContent = computed(() => {
  if (!content.value?.items) return [];
  const typeMap: Record<string, string[]> = {
    projects: ['project'],
    articles: ['article', 'blog'],
    explainers: ['explainer'],
    videos: ['video'],
    about: ['project'], // About tab sidebar shows featured projects
  };
  const types = typeMap[activeTab.value];
  if (!types) return [];
  return content.value.items.filter((i) => types.includes(i.type));
});

const p = computed(() => profile.value);

const { isAuthenticated, user } = useAuth();
const toast = useToast();
const isOwnProfile = computed(() => user.value?.username === username);
const following = ref(false);
const followLoading = ref(false);

// Initialize follow state from API response
watch(() => profile.value, (p) => {
  if (p && 'isFollowing' in p) {
    following.value = (p as Record<string, unknown>).isFollowing as boolean;
  }
}, { immediate: true });

async function toggleFollow(): Promise<void> {
  if (!isAuthenticated.value) {
    await navigateTo(`/auth/login?redirect=/u/${username}`);
    return;
  }
  followLoading.value = true;
  try {
    if (following.value) {
      await $fetch(`/api/users/${username}/follow`, { method: 'DELETE' });
      following.value = false;
      toast.success('Unfollowed');
    } else {
      await $fetch(`/api/users/${username}/follow`, { method: 'POST' });
      following.value = true;
      toast.success('Following!');
    }
  } catch {
    toast.error('Failed to update follow');
  } finally {
    followLoading.value = false;
  }
}

function handleMessage(): void {
  navigateTo('/messages');
}

async function handleShare(): Promise<void> {
  const url = `${window.location.origin}/u/${username}`;
  if (navigator.share) {
    await navigator.share({ title: p.value?.displayName || username, url }).catch(() => {});
  } else {
    await navigator.clipboard.writeText(url);
    toast.success('Link copied to clipboard');
  }
}

const showMenu = ref(false);
function toggleMenu(): void {
  showMenu.value = !showMenu.value;
}
</script>

<template>
  <div v-if="profilePending" class="cpub-loading">Loading profile...</div>
  <div v-else-if="profileError" class="cpub-fetch-error">
    <div class="cpub-fetch-error-icon"><i class="fa-solid fa-triangle-exclamation"></i></div>
    <div class="cpub-fetch-error-msg">Failed to load user profile.</div>
    <button class="cpub-btn cpub-btn-sm" @click="refreshProfile()">Retry</button>
  </div>
  <div v-else-if="p" class="cpub-profile">
    <!-- Hero -->
    <section class="cpub-profile-hero">
      <!-- Banner -->
      <div class="cpub-profile-banner">
        <div class="cpub-profile-banner-grid" />
      </div>

      <div class="cpub-profile-hero-inner">
        <div class="cpub-profile-hero-top">
          <div class="cpub-profile-avatar-wrap">
            <div class="cpub-profile-avatar">
              {{ (p.displayName || p.username || 'U').charAt(0).toUpperCase() }}
            </div>
            <div v-if="p.verified" class="cpub-verified-badge" aria-label="Verified">
              <i class="fa-solid fa-check"></i>
            </div>
          </div>
          <div class="cpub-profile-hero-info">
            <h1 class="cpub-profile-name">{{ p.displayName || p.username }}</h1>
            <div class="cpub-profile-handle">@{{ p.username }}</div>
            <p v-if="p.headline" class="cpub-profile-headline">{{ p.headline }}</p>
            <p v-if="p.bio" class="cpub-profile-bio">{{ p.bio }}</p>
            <div class="cpub-profile-meta">
              <span v-if="p.location" class="cpub-profile-meta-item">
                <i class="fa-solid fa-location-dot"></i> {{ p.location }}
              </span>
              <span v-if="p.website" class="cpub-profile-meta-item">
                <i class="fa-solid fa-globe"></i>
                <a :href="p.website" target="_blank" rel="noopener">{{ p.website.replace(/^https?:\/\//, '') }}</a>
              </span>
              <span class="cpub-profile-meta-item">
                <i class="fa-solid fa-calendar"></i> Joined {{ new Date(p.createdAt).toLocaleDateString('en-US', { month: 'short', year: 'numeric' }) }}
              </span>
            </div>
            <div v-if="p.skills?.length" class="cpub-tag-row" style="margin-bottom: 14px">
              <span v-for="skill in p.skills" :key="skill" class="cpub-tag">{{ skill }}</span>
            </div>
            <div style="display: flex; align-items: center; gap: 16px">
              <div v-if="!isOwnProfile" class="cpub-profile-actions">
                <button
                  :class="['cpub-btn', following ? '' : 'cpub-btn-primary']"
                  :disabled="followLoading"
                  @click="toggleFollow"
                >
                  <i :class="following ? 'fa-solid fa-user-check' : 'fa-solid fa-user-plus'"></i>
                  {{ following ? 'Following' : 'Follow' }}
                </button>
                <button class="cpub-btn" @click="handleMessage"><i class="fa-solid fa-envelope"></i> Message</button>
                <button class="cpub-btn cpub-btn-sm" aria-label="Share profile" @click="handleShare"><i class="fa-solid fa-share-nodes"></i></button>
                <div style="position: relative; display: inline-block;">
                  <button class="cpub-btn cpub-btn-sm" aria-label="More options" @click="toggleMenu"><i class="fa-solid fa-ellipsis"></i></button>
                  <div v-if="showMenu" class="cpub-dropdown" @click="showMenu = false">
                    <button class="cpub-dropdown-item"><i class="fa-solid fa-flag"></i> Report</button>
                    <button class="cpub-dropdown-item"><i class="fa-solid fa-ban"></i> Block</button>
                  </div>
                </div>
              </div>
              <div v-else class="cpub-profile-actions">
                <NuxtLink to="/settings/profile" class="cpub-btn"><i class="fa-solid fa-pen"></i> Edit Profile</NuxtLink>
              </div>
              <div v-if="p.socialLinks" class="cpub-profile-social">
                <a v-if="p.socialLinks.github" :href="p.socialLinks.github" class="cpub-social-btn" target="_blank" rel="noopener" aria-label="GitHub"><i class="fa-brands fa-github"></i></a>
                <a v-if="p.socialLinks.twitter" :href="p.socialLinks.twitter" class="cpub-social-btn" target="_blank" rel="noopener" aria-label="Twitter"><i class="fa-brands fa-x-twitter"></i></a>
                <a v-if="p.socialLinks.linkedin" :href="p.socialLinks.linkedin" class="cpub-social-btn" target="_blank" rel="noopener" aria-label="LinkedIn"><i class="fa-brands fa-linkedin-in"></i></a>
                <a v-if="p.socialLinks.youtube" :href="p.socialLinks.youtube" class="cpub-social-btn" target="_blank" rel="noopener" aria-label="YouTube"><i class="fa-brands fa-youtube"></i></a>
                <a v-if="p.socialLinks.mastodon" :href="p.socialLinks.mastodon" class="cpub-social-btn" target="_blank" rel="noopener" aria-label="Mastodon"><i class="fa-brands fa-mastodon"></i></a>
              </div>
            </div>
          </div>
        </div>
        <!-- Stats -->
        <StatBar :stats="profileStats" />
      </div>
    </section>

    <!-- Tabs -->
    <div class="cpub-profile-tabs">
      <div class="cpub-profile-tabs-inner">
        <button
          v-for="tab in tabDefs"
          :key="tab.value"
          class="cpub-tab-btn"
          :class="{ active: activeTab === tab.value }"
          @click="activeTab = tab.value"
        >
          <i :class="tab.icon" style="font-size: 10px"></i>
          {{ tab.label }}
        </button>
      </div>
    </div>

    <!-- Content -->
    <div class="cpub-profile-main">
      <!-- Projects / Articles / Explainers / Videos tabs -->
      <template v-if="['projects', 'articles', 'explainers'].includes(activeTab)">
        <!-- Section header -->
        <div class="cpub-sec-head">
          <h2>
            <i :class="tabDefs.find(t => t.value === activeTab)?.icon" style="color: var(--accent); margin-right: 6px"></i>
            {{ tabDefs.find(t => t.value === activeTab)?.label }}
          </h2>
        </div>

        <div v-if="filteredContent.length" class="cpub-grid-3">
          <ContentCard v-for="item in filteredContent" :key="item.id" :item="item" />
        </div>
        <div v-else class="cpub-empty-state">
          <p class="cpub-empty-state-title">No {{ activeTab }} yet</p>
        </div>
      </template>

      <!-- Learning tab — Certificates + In-progress paths -->
      <template v-if="activeTab === 'learning'">
        <!-- Certificates -->
        <template v-if="learningData?.certificates?.length">
          <div class="cpub-sec-head">
            <h2><i class="fa-solid fa-medal" style="color: var(--yellow); margin-right: 6px"></i>Certificates</h2>
          </div>
          <div class="cpub-cert-list">
            <NuxtLink
              v-for="cert in learningData.certificates"
              :key="cert.id"
              :to="`/cert/${cert.verificationCode}`"
              class="cpub-cert-card-profile"
            >
              <div class="cpub-cert-card-badge"><i class="fa-solid fa-award"></i></div>
              <div class="cpub-cert-card-info">
                <div class="cpub-cert-card-path">{{ cert.path.title }}</div>
                <div class="cpub-cert-card-date">Completed {{ new Date(cert.issuedAt).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }) }}</div>
              </div>
              <div class="cpub-cert-card-code">{{ cert.verificationCode }}</div>
            </NuxtLink>
          </div>
        </template>

        <!-- In-progress enrollments -->
        <template v-if="learningData?.enrollments?.length">
          <div class="cpub-sec-head" style="margin-top: 24px">
            <h2><i class="fa-solid fa-graduation-cap" style="color: var(--accent); margin-right: 6px"></i>In Progress</h2>
          </div>
          <div class="cpub-enrollment-list">
            <NuxtLink
              v-for="enr in learningData.enrollments"
              :key="enr.id"
              :to="`/learn/${enr.path.slug}`"
              class="cpub-enrollment-card"
            >
              <div class="cpub-enrollment-icon"><i class="fa-solid fa-route"></i></div>
              <div class="cpub-enrollment-info">
                <div class="cpub-enrollment-title">{{ enr.path.title }}</div>
                <div class="cpub-enrollment-progress-row">
                  <div class="cpub-enrollment-bar">
                    <div class="cpub-enrollment-fill" :style="{ width: (enr.progress ?? 0) + '%' }"></div>
                  </div>
                  <span class="cpub-enrollment-pct">{{ Math.round(parseFloat(enr.progress)) }}%</span>
                </div>
              </div>
            </NuxtLink>
          </div>
        </template>

        <div v-if="!learningData?.certificates?.length && !learningData?.enrollments?.length" class="cpub-learning-empty">
          <div class="cpub-empty-icon"><i class="fa-solid fa-graduation-cap"></i></div>
          <p class="cpub-empty-state-title">No learning activity yet</p>
          <p class="cpub-empty-state-sub">Enroll in learning paths to start tracking progress.</p>
        </div>
      </template>

      <!-- About tab — Experience + Awards + Skills with sidebar -->
      <template v-if="activeTab === 'about'">
        <div class="cpub-about-grid">
          <div>
            <!-- Experience -->
            <div style="margin-bottom: 32px">
              <div class="cpub-sec-head">
                <h2><i class="fa-solid fa-briefcase" style="color: var(--accent); margin-right: 6px"></i>Experience</h2>
              </div>
              <div class="cpub-profile-timeline">
                <TimelineItem
                  v-for="(exp, i) in (p.experience || [])"
                  :key="i"
                  :role="exp.role"
                  :company="exp.company"
                  :period="exp.period"
                  :description="exp.description"
                  :current="i === 0"
                />
                <div v-if="!p.experience?.length" class="cpub-empty-state">
                  <p class="cpub-empty-state-title">No experience entries yet</p>
                </div>
              </div>
            </div>

            <!-- Awards -->
            <div style="margin-bottom: 32px">
              <div class="cpub-sec-head">
                <h2><i class="fa-solid fa-trophy" style="color: var(--yellow); margin-right: 6px"></i>Awards &amp; Recognition</h2>
              </div>
              <div class="cpub-awards-grid">
                <div v-for="(award, i) in (p.awards || [])" :key="i" class="cpub-award-card">
                  <div class="cpub-award-icon"><i class="fa-solid fa-medal"></i></div>
                  <div class="cpub-award-title">{{ award.title }}</div>
                  <div class="cpub-award-org">{{ award.organization }}</div>
                  <div class="cpub-award-year">{{ award.year }}</div>
                </div>
              </div>
              <div v-if="!p.awards?.length" class="cpub-empty-state">
                <p class="cpub-empty-state-title">No awards yet</p>
              </div>
            </div>

            <!-- Skills -->
            <div class="cpub-skills-section">
              <div class="cpub-sec-head">
                <h2><i class="fa-solid fa-microchip" style="color: var(--teal); margin-right: 6px"></i>Skills</h2>
              </div>
              <div v-if="p.skills?.length" class="cpub-tag-row" style="flex-wrap: wrap; gap: 6px;">
                <span v-for="skill in p.skills" :key="skill" class="cpub-tag">{{ skill }}</span>
              </div>
              <div v-else class="cpub-empty-state">
                <p class="cpub-empty-state-title">No skills listed yet</p>
              </div>
            </div>
          </div>

          <!-- Sidebar -->
          <div class="cpub-about-sidebar">
            <!-- Activity Heatmap -->
            <div class="cpub-sb-card">
              <div class="cpub-sb-title">Activity</div>
              <HeatmapGrid :weeks="20" />
            </div>

            <!-- Featured Projects -->
            <div class="cpub-sb-card">
              <div class="cpub-sb-title">Featured Projects</div>
              <div v-for="item in filteredContent.slice(0, 3)" :key="item.id" class="cpub-mini-project">
                <div class="cpub-mini-thumb"><i class="fa-solid fa-microchip"></i></div>
                <div>
                  <div class="cpub-mini-title">{{ item.title }}</div>
                  <div class="cpub-mini-meta">{{ item.viewCount ?? 0 }} views</div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </template>
    </div>
  </div>

  <div v-else class="cpub-empty-state">
    <p class="cpub-empty-state-title">User not found</p>
  </div>
</template>

<style scoped>
/* Profile Banner */
.cpub-profile-banner {
  height: 180px;
  background: linear-gradient(135deg, var(--accent) 0%, var(--purple) 50%, var(--teal) 100%);
  position: relative;
  overflow: hidden;
}

.cpub-profile-banner-grid {
  position: absolute;
  inset: 0;
  background-image:
    linear-gradient(rgba(255,255,255,0.1) 1px, transparent 1px),
    linear-gradient(90deg, rgba(255,255,255,0.1) 1px, transparent 1px);
  background-size: 40px 40px;
  opacity: 0.3;
}

/* Profile Hero */
.cpub-profile-hero {
  background: var(--surface2);
  border-bottom: 2px solid var(--border);
  padding: 0;
}

.cpub-profile-hero-inner {
  max-width: 1080px;
  margin: 0 auto;
  padding: 0 32px;
  margin-top: -48px;
  position: relative;
  z-index: 1;
}

.cpub-profile-hero-top {
  display: flex;
  align-items: flex-start;
  gap: 24px;
  margin-bottom: 24px;
  padding-top: 16px;
}

.cpub-profile-avatar-wrap {
  position: relative;
  flex-shrink: 0;
}

.cpub-profile-avatar {
  width: 120px;
  height: 120px;
  border-radius: 50%;
  background: var(--surface);
  border: 4px solid var(--surface);
  box-shadow: 0 0 0 2px var(--border);
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 40px;
  font-weight: 700;
  color: var(--accent);
  font-family: var(--font-mono);
}

.cpub-verified-badge {
  position: absolute;
  bottom: 2px;
  right: 2px;
  width: 20px;
  height: 20px;
  border-radius: 50%;
  background: var(--accent);
  border: 2px solid var(--bg);
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 9px;
  color: var(--color-text-inverse);
}

.cpub-profile-hero-info {
  flex: 1;
  min-width: 0;
}

.cpub-profile-name {
  font-size: 22px;
  font-weight: 700;
  letter-spacing: -0.02em;
  margin-bottom: 2px;
}

.cpub-profile-handle {
  font-size: 13px;
  color: var(--text-dim);
  font-family: var(--font-mono);
  margin-bottom: 6px;
}

.cpub-profile-headline {
  font-size: 14px;
  font-weight: 500;
  color: var(--text);
  margin-bottom: 10px;
}

.cpub-profile-bio {
  font-size: 12px;
  color: var(--text-dim);
  line-height: 1.6;
  max-width: 560px;
  margin-bottom: 12px;
}

.cpub-profile-meta {
  display: flex;
  align-items: center;
  gap: 16px;
  font-size: 11px;
  color: var(--text-dim);
  margin-bottom: 12px;
  font-family: var(--font-mono);
}

.cpub-profile-meta-item {
  display: flex;
  align-items: center;
  gap: 5px;
}

.cpub-profile-meta-item a {
  color: var(--accent);
  text-decoration: none;
}

.cpub-profile-meta-item a:hover {
  text-decoration: underline;
}

.cpub-profile-actions {
  display: flex;
  align-items: center;
  gap: 8px;
  margin-bottom: 20px;
}

.cpub-profile-social {
  display: flex;
  align-items: center;
  gap: 6px;
  margin-left: 8px;
}

.cpub-social-btn {
  width: 28px;
  height: 28px;
  background: var(--surface);
  border: 2px solid var(--border);
  color: var(--text-dim);
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 12px;
  text-decoration: none;
}

.cpub-social-btn:hover {
  background: var(--surface2);
  color: var(--text);
}

/* Profile Stats */
.cpub-profile-stats {
  display: flex;
  gap: 0;
  border-top: 2px solid var(--border);
  margin-top: 16px;
}

.cpub-profile-stat {
  flex: 1;
  padding: 14px 20px;
  border-right: 2px solid var(--border);
  cursor: pointer;
}

.cpub-profile-stat:last-child {
  border-right: none;
}

.cpub-profile-stat:hover {
  background: var(--surface2);
}

.cpub-profile-stat-val {
  font-size: 18px;
  font-weight: 700;
  color: var(--text);
  font-family: var(--font-mono);
  margin-bottom: 2px;
  display: block;
}

.cpub-profile-stat-label {
  font-size: 10px;
  color: var(--text-faint);
  text-transform: uppercase;
  letter-spacing: 0.1em;
  font-family: var(--font-mono);
}

/* Profile Tabs */
.cpub-profile-tabs {
  background: var(--surface);
  border-bottom: 2px solid var(--border);
  position: sticky;
  top: 48px;
  z-index: 90;
}

.cpub-profile-tabs-inner {
  max-width: 1080px;
  margin: 0 auto;
  padding: 0 32px;
  display: flex;
  gap: 2px;
}

.cpub-tab-btn {
  font-size: 12px;
  color: var(--text-dim);
  padding: 10px 14px;
  border: none;
  background: none;
  cursor: pointer;
  border-bottom: 3px solid transparent;
  font-family: system-ui, -apple-system, sans-serif;
  display: flex;
  align-items: center;
  gap: 6px;
  position: relative;
  top: 2px;
}

.cpub-tab-btn:hover { color: var(--text); }

.cpub-tab-btn.active {
  color: var(--text);
  border-bottom-color: var(--accent);
}

/* Main Content */
.cpub-profile-main {
  max-width: 1080px;
  margin: 0 auto;
  padding: 32px;
}

/* Timeline */
.cpub-profile-timeline {
  position: relative;
  padding-left: 20px;
}

.cpub-profile-timeline::before {
  content: '';
  position: absolute;
  left: 3px;
  top: 6px;
  bottom: 6px;
  width: 2px;
  background: var(--border2);
}

/* Awards */
.cpub-awards-grid {
  display: grid;
  grid-template-columns: repeat(2, 1fr);
  gap: 10px;
}

.cpub-award-card {
  background: var(--surface);
  border: 2px solid var(--border);
  padding: 12px;
  box-shadow: var(--shadow-md);
}

.cpub-award-icon {
  font-size: 18px;
  margin-bottom: 6px;
  color: var(--accent);
}

.cpub-award-title {
  font-size: 11px;
  font-weight: 600;
  margin-bottom: 2px;
}

.cpub-award-org {
  font-size: 10px;
  color: var(--text-faint);
  font-family: var(--font-mono);
}

.cpub-award-year {
  font-size: 9px;
  color: var(--text-faint);
  font-family: var(--font-mono);
  margin-top: 4px;
}

/* Skills */
.cpub-skills-group {
  margin-bottom: 16px;
}

.cpub-skills-group-label {
  font-size: 10px;
  font-weight: 600;
  text-transform: uppercase;
  letter-spacing: 0.1em;
  color: var(--text-faint);
  font-family: var(--font-mono);
  margin-bottom: 8px;
}

/* About grid */
.cpub-about-grid {
  display: grid;
  grid-template-columns: 1fr 280px;
  gap: 32px;
  align-items: start;
}

/* Timeline */
.cpub-tl-item {
  position: relative;
  margin-bottom: 24px;
}

.cpub-tl-item:last-child { margin-bottom: 0; }

.cpub-tl-dot {
  position: absolute;
  left: -17px;
  top: 4px;
  width: 7px;
  height: 7px;
  background: var(--border2);
  border: 1px solid var(--border);
}

.cpub-tl-dot.active {
  background: var(--accent);
  border-color: var(--accent);
}

.cpub-tl-header {
  display: flex;
  align-items: flex-start;
  justify-content: space-between;
  gap: 8px;
  margin-bottom: 4px;
}

.cpub-tl-role { font-size: 13px; font-weight: 600; }
.cpub-tl-period { font-size: 10px; color: var(--text-faint); font-family: var(--font-mono); white-space: nowrap; margin-top: 2px; }
.cpub-tl-company { font-size: 11px; color: var(--accent); font-family: var(--font-mono); margin-bottom: 4px; }
.cpub-tl-desc { font-size: 11px; color: var(--text-dim); line-height: 1.55; }

/* Skill bars */
.cpub-skill-bar-row {
  display: flex;
  align-items: center;
  gap: 10px;
  margin-bottom: 6px;
}

.cpub-skill-name {
  font-size: 11px;
  color: var(--text-dim);
  width: 130px;
  flex-shrink: 0;
  font-family: var(--font-mono);
}

.cpub-skill-bar {
  flex: 1;
  height: 4px;
  background: var(--surface3);
  overflow: hidden;
  border: 1px solid var(--border2);
}

.cpub-skill-fill { height: 100%; background: var(--accent); }

.cpub-skill-pct {
  font-size: 9px;
  color: var(--text-faint);
  font-family: var(--font-mono);
  width: 28px;
  text-align: right;
}

.cpub-mini-project {
  display: flex;
  gap: 10px;
  margin-bottom: 10px;
  padding-bottom: 10px;
  border-bottom: 1px solid var(--border2);
}

.cpub-mini-project:last-child { margin-bottom: 0; padding-bottom: 0; border-bottom: none; }

.cpub-mini-thumb {
  width: 44px;
  height: 36px;
  background: var(--surface2);
  flex-shrink: 0;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 14px;
  border: 2px solid var(--border);
  color: var(--accent);
}

.cpub-learning-empty { text-align: center; padding: 48px 0; }
.cpub-empty-icon { font-size: 32px; color: var(--text-faint); margin-bottom: 12px; }
.cpub-empty-state-sub { font-size: 12px; color: var(--text-dim); margin-top: 4px; }

/* Certificates list */
.cpub-cert-list { display: flex; flex-direction: column; gap: 8px; }
.cpub-cert-card-profile { display: flex; align-items: center; gap: 14px; padding: 14px 16px; border: 2px solid var(--border); background: var(--surface); text-decoration: none; color: var(--text); box-shadow: 4px 4px 0 var(--border); transition: box-shadow 0.15s, transform 0.15s; }
.cpub-cert-card-profile:hover { box-shadow: 2px 2px 0 var(--border); transform: translate(1px, 1px); }
.cpub-cert-card-badge { width: 40px; height: 40px; border-radius: 50%; border: 2px solid var(--yellow); background: var(--yellow-bg); display: flex; align-items: center; justify-content: center; font-size: 18px; color: var(--yellow); flex-shrink: 0; }
.cpub-cert-card-info { flex: 1; }
.cpub-cert-card-path { font-size: 14px; font-weight: 600; margin-bottom: 2px; }
.cpub-cert-card-date { font-size: 11px; font-family: var(--font-mono); color: var(--text-faint); }
.cpub-cert-card-code { font-size: 10px; font-family: var(--font-mono); color: var(--accent); background: var(--accent-bg); padding: 2px 8px; border: 1px solid var(--accent-border); flex-shrink: 0; }

/* Enrollment list */
.cpub-enrollment-list { display: flex; flex-direction: column; gap: 8px; }
.cpub-enrollment-card { display: flex; align-items: center; gap: 14px; padding: 14px 16px; border: 2px solid var(--border); background: var(--surface); text-decoration: none; color: var(--text); box-shadow: 4px 4px 0 var(--border); transition: box-shadow 0.15s, transform 0.15s; }
.cpub-enrollment-card:hover { box-shadow: 2px 2px 0 var(--border); transform: translate(1px, 1px); }
.cpub-enrollment-icon { width: 40px; height: 40px; border: 2px solid var(--border); background: var(--surface2); display: flex; align-items: center; justify-content: center; font-size: 16px; color: var(--accent); flex-shrink: 0; }
.cpub-enrollment-info { flex: 1; }
.cpub-enrollment-title { font-size: 14px; font-weight: 600; margin-bottom: 6px; }
.cpub-enrollment-progress-row { display: flex; align-items: center; gap: 8px; }
.cpub-enrollment-bar { flex: 1; height: 4px; background: var(--surface3); border: 1px solid var(--border2); }
.cpub-enrollment-fill { height: 100%; background: var(--accent); }
.cpub-enrollment-pct { font-size: 11px; font-family: var(--font-mono); color: var(--accent); flex-shrink: 0; }

.cpub-mini-title { font-size: 11px; font-weight: 500; margin-bottom: 2px; line-height: 1.3; }
.cpub-mini-meta { font-size: 10px; color: var(--text-faint); font-family: var(--font-mono); }

/* Grid */
.cpub-grid-3 {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 16px;
}

.cpub-dropdown {
  position: absolute;
  top: calc(100% + 4px);
  right: 0;
  background: var(--surface);
  border: 2px solid var(--border);
  box-shadow: 4px 4px 0 var(--border);
  z-index: 100;
  min-width: 140px;
}

.cpub-dropdown-item {
  display: flex;
  align-items: center;
  gap: 8px;
  width: 100%;
  padding: 8px 12px;
  background: none;
  border: none;
  color: var(--text-dim);
  font-size: 12px;
  cursor: pointer;
  text-align: left;
}

.cpub-dropdown-item:hover {
  background: var(--surface2);
  color: var(--text);
}

@media (max-width: 768px) {
  .cpub-profile-hero-top {
    flex-direction: column;
    align-items: center;
    text-align: center;
  }
  .cpub-profile-meta {
    justify-content: center;
    flex-wrap: wrap;
  }
  .cpub-profile-actions {
    justify-content: center;
  }
  .cpub-profile-stats {
    flex-wrap: wrap;
  }
  .cpub-profile-stat {
    min-width: 50%;
    border-bottom: 2px solid var(--border);
  }
  .cpub-awards-grid {
    grid-template-columns: 1fr;
  }
  .cpub-about-grid {
    grid-template-columns: 1fr;
  }
  .cpub-grid-3 {
    grid-template-columns: 1fr;
  }
}
</style>
