// apps/reference/src/routes/(app)/admin/+page.svelte
<script lang="ts">
  import StatCard from '$lib/components/admin/StatCard.svelte';
  import type { PageData } from './$types';

  let { data } = $props<{ data: PageData }>();
</script>

<svelte:head>
  <title>Admin Dashboard</title>
</svelte:head>

<div class="adm-page-header">
  <h1 class="adm-heading">Dashboard</h1>
  <span class="adm-heading-sub">system overview</span>
</div>

<div class="adm-stats-grid">
  <StatCard label="Total Users" value={data.stats.users.total} />
  <StatCard label="Total Content" value={data.stats.content.total} />
  <StatCard label="Communities" value={data.stats.communities.total} />
  <StatCard
    label="Pending Reports"
    value={data.stats.reports.pending}
    description={`${data.stats.reports.total} total`}
  />
</div>

<div class="adm-breakdown">
  <section>
    <div class="adm-section-head">
      <span class="adm-section-label">Users by Role</span>
    </div>
    <div class="adm-stats-grid">
      {#each Object.entries(data.stats.users.byRole) as [role, count]}
        <StatCard label={role} value={count as number} />
      {/each}
    </div>
  </section>

  <section>
    <div class="adm-section-head">
      <span class="adm-section-label">Content by Type</span>
    </div>
    <div class="adm-stats-grid">
      {#each Object.entries(data.stats.content.byType) as [type, count]}
        <StatCard label={type} value={count as number} />
      {/each}
    </div>
  </section>
</div>

<style>
  .adm-page-header {
    display: flex;
    align-items: baseline;
    gap: var(--space-3, 0.75rem);
    margin-bottom: var(--space-6, 1.5rem);
    padding-bottom: var(--space-3, 0.75rem);
    border-bottom: 1px solid var(--color-border, #272725);
  }

  .adm-heading {
    font-size: var(--text-xl, 1.25rem);
    font-weight: var(--font-weight-bold, 700);
    color: var(--color-text, #d8d5cf);
    margin: 0;
  }

  .adm-heading-sub {
    font-family: var(--font-mono, monospace);
    font-size: 10px;
    text-transform: uppercase;
    letter-spacing: 0.08em;
    color: var(--color-text-muted, #444440);
  }

  .adm-stats-grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(160px, 1fr));
    gap: var(--space-3, 0.75rem);
  }

  .adm-breakdown {
    margin-top: var(--space-6, 1.5rem);
    display: flex;
    flex-direction: column;
    gap: var(--space-4, 1rem);
  }

  .adm-section-head {
    border-bottom: 1px solid var(--color-border, #272725);
    padding-bottom: var(--space-2, 0.5rem);
    margin-bottom: var(--space-3, 0.75rem);
  }

  .adm-section-label {
    font-family: var(--font-mono, monospace);
    font-size: 10px;
    text-transform: uppercase;
    letter-spacing: 0.1em;
    color: var(--color-text-secondary, #888884);
  }
</style>

// layers/base/pages/admin/index.vue
<script setup lang="ts">
definePageMeta({ layout: 'admin', middleware: 'auth' });
useSeoMeta({ title: `Admin Dashboard — ${useSiteName()}` });

const { data: stats } = await useFetch('/api/admin/stats');
</script>

<template>
  <div class="cpub-admin-dashboard">
    <h1 class="cpub-admin-title">Platform Dashboard</h1>

    <div class="cpub-stats-grid" v-if="stats">
      <div class="cpub-stat-card" v-for="stat in [
        { label: 'Users', value: stats.users?.total ?? 0, icon: 'fa-solid fa-users' },
        { label: 'Content', value: stats.content?.total ?? 0, icon: 'fa-solid fa-file-lines' },
        { label: 'Communities', value: stats.hubs?.total ?? 0, icon: 'fa-solid fa-people-group' },
        { label: 'Reports', value: stats.reports?.pending ?? 0, icon: 'fa-solid fa-flag' },
      ]" :key="stat.label">
        <i :class="[stat.icon, 'cpub-stat-icon']"></i>
        <span class="cpub-stat-value">{{ stat.value }}</span>
        <span class="cpub-stat-label">{{ stat.label }}</span>
      </div>
    </div>

    <div class="cpub-admin-quick-links">
      <h2 class="cpub-admin-section-title">Quick Actions</h2>
      <div class="cpub-admin-actions-grid">
        <NuxtLink to="/admin/users" class="cpub-admin-action">
          <i class="fa-solid fa-user-gear cpub-admin-action-icon"></i>
          <span class="cpub-admin-action-label">Manage Users</span>
        </NuxtLink>
        <NuxtLink to="/admin/reports" class="cpub-admin-action">
          <i class="fa-solid fa-flag cpub-admin-action-icon"></i>
          <span class="cpub-admin-action-label">Review Reports</span>
        </NuxtLink>
        <NuxtLink to="/admin/content" class="cpub-admin-action">
          <i class="fa-solid fa-newspaper cpub-admin-action-icon"></i>
          <span class="cpub-admin-action-label">Manage Content</span>
        </NuxtLink>
        <NuxtLink to="/admin/settings" class="cpub-admin-action">
          <i class="fa-solid fa-gear cpub-admin-action-icon"></i>
          <span class="cpub-admin-action-label">Instance Settings</span>
        </NuxtLink>
      </div>
    </div>
  </div>
</template>

<style scoped>
.cpub-admin-title { font-size: var(--text-xl); font-weight: var(--font-weight-bold); margin-bottom: var(--space-6); }
.cpub-stats-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(140px, 1fr)); gap: var(--space-4); margin-bottom: var(--space-8); }
.cpub-stat-card { padding: var(--space-5); background: var(--surface); border: var(--border-width-default) solid var(--border); box-shadow: var(--shadow-md); display: flex; flex-direction: column; align-items: center; gap: var(--space-2); }
.cpub-stat-icon { font-size: var(--text-xl); color: var(--text-dim); margin-bottom: var(--space-1); }
.cpub-stat-value { font-size: var(--text-3xl); font-weight: var(--font-weight-bold); font-family: var(--font-mono); }
.cpub-stat-label { font-family: var(--font-mono); font-size: 10px; font-weight: var(--font-weight-semibold); text-transform: uppercase; letter-spacing: var(--tracking-widest); color: var(--text-dim); }
.cpub-admin-section-title { font-size: var(--text-lg); font-weight: var(--font-weight-bold); margin-bottom: var(--space-4); }
.cpub-admin-actions-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(140px, 1fr)); gap: var(--space-3); }
.cpub-admin-action { display: flex; flex-direction: column; align-items: center; gap: var(--space-3); padding: var(--space-5); background: var(--surface); border: var(--border-width-default) solid var(--border); text-decoration: none; color: var(--text); transition: all 0.15s; }
.cpub-admin-action:hover { background: var(--surface2); box-shadow: var(--shadow-md); transform: translate(-1px, -1px); }
.cpub-admin-action-icon { font-size: var(--text-xl); color: var(--text-dim); }
.cpub-admin-action-label { font-family: var(--font-mono); font-size: 10px; text-transform: uppercase; letter-spacing: var(--tracking-wide); color: var(--text-dim); }
</style>
