// layers/base/pages/docs/index.vue
<script setup lang="ts">
useSeoMeta({
  title: 'Documentation — CommonPub',
  description: 'Browse documentation sites.',
});

const { data: sites, pending, error, refresh } = useLazyFetch('/api/docs');
const { isAuthenticated, user } = useAuth();

const mySites = computed(() => {
  if (!sites.value?.items || !user.value) return [];
  return sites.value.items.filter((s: { ownerId: string }) => s.ownerId === user.value!.id);
});

const otherSites = computed(() => {
  if (!sites.value?.items) return sites.value?.items ?? [];
  if (!user.value) return sites.value.items;
  return sites.value.items.filter((s: { ownerId: string }) => s.ownerId !== user.value!.id);
});
</script>

<template>
  <div class="docs-index">
    <div v-if="pending" class="cpub-loading">Loading documentation...</div>
    <div v-else-if="error" class="cpub-fetch-error">
      <div class="cpub-fetch-error-icon"><i class="fa-solid fa-triangle-exclamation"></i></div>
      <div class="cpub-fetch-error-msg">Failed to load documentation sites.</div>
      <button class="cpub-btn cpub-btn-sm" @click="refresh()">Retry</button>
    </div>
    <div v-else-if="!sites?.items?.length && !isAuthenticated" class="cpub-empty-state">
      <div class="cpub-empty-state-icon"><i class="fa-solid fa-book"></i></div>
      <div class="cpub-empty-state-title">No documentation sites yet</div>
    </div>
    <template v-else>
    <div class="docs-header">
      <div>
        <h1 class="docs-title">Documentation</h1>
        <p class="docs-subtitle">Browse documentation sites and knowledge bases.</p>
      </div>
      <NuxtLink v-if="isAuthenticated" to="/docs/create" class="cpub-btn cpub-btn-primary">
        <i class="fa-solid fa-plus"></i> Create Docs Site
      </NuxtLink>
    </div>

    <!-- My Docs -->
    <template v-if="isAuthenticated && mySites.length">
      <div class="docs-section-head">
        <h2 class="docs-section-title"><i class="fa-solid fa-user"></i> My Docs</h2>
        <span class="docs-section-count">{{ mySites.length }}</span>
      </div>
      <div class="docs-grid">
        <NuxtLink v-for="site in mySites" :key="site.id" :to="`/docs/${site.slug}`" class="docs-card">
          <div class="docs-card-icon"><i class="fa-solid fa-book"></i></div>
          <h2 class="docs-card-name">{{ site.name }}</h2>
          <p class="docs-card-desc" v-if="site.description">{{ site.description }}</p>
          <div class="docs-card-meta">
            <span class="docs-card-meta-item">
              <i class="fa-solid fa-user"></i> {{ site.owner?.displayName || site.owner?.username || 'Unknown' }}
            </span>
            <span class="docs-card-meta-item">
              <i class="fa-solid fa-clock"></i> {{ new Date(site.updatedAt).toLocaleDateString('en-US', { month: 'short', day: 'numeric' }) }}
            </span>
          </div>
        </NuxtLink>
      </div>
      <hr class="docs-divider" />
    </template>

    <!-- All Docs -->
    <template v-if="otherSites.length || (!isAuthenticated && sites?.items?.length)">
      <div class="docs-section-head" v-if="isAuthenticated && mySites.length">
        <h2 class="docs-section-title">All Documentation</h2>
      </div>
      <div class="docs-grid">
        <NuxtLink v-for="site in otherSites" :key="site.id" :to="`/docs/${site.slug}`" class="docs-card">
          <div class="docs-card-icon"><i class="fa-solid fa-book"></i></div>
          <h2 class="docs-card-name">{{ site.name }}</h2>
          <p class="docs-card-desc" v-if="site.description">{{ site.description }}</p>
          <div class="docs-card-meta">
            <span class="docs-card-meta-item">
              <i class="fa-solid fa-user"></i> {{ site.owner?.displayName || site.owner?.username || 'Unknown' }}
            </span>
          </div>
        </NuxtLink>
      </div>
    </template>

    <div v-if="!sites?.items?.length" class="docs-empty">
      <div class="docs-empty-icon"><i class="fa-solid fa-book-open"></i></div>
      <p class="docs-empty-title">No documentation sites yet</p>
      <p class="docs-empty-sub">Create your first docs site to get started.</p>
    </div>
    </template>
  </div>
</template>

<style scoped>
.docs-index { max-width: 960px; margin: 0 auto; padding: 32px; }

.docs-header {
  display: flex;
  align-items: flex-start;
  justify-content: space-between;
  margin-bottom: 32px;
}

.docs-title { font-size: 24px; font-weight: 700; letter-spacing: -0.02em; margin-bottom: 4px; }
.docs-subtitle { font-size: 13px; color: var(--text-dim); }

.docs-section-head {
  display: flex;
  align-items: center;
  gap: 8px;
  margin-bottom: 16px;
}

.docs-section-title {
  font-size: 14px;
  font-weight: 700;
  display: flex;
  align-items: center;
  gap: 8px;
}

.docs-section-title i { font-size: 12px; color: var(--accent); }

.docs-section-count {
  font-size: 10px;
  font-family: var(--font-mono);
  background: var(--surface2);
  border: 2px solid var(--border);
  padding: 1px 6px;
  color: var(--text-faint);
}

.docs-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
  gap: 12px;
}

.docs-card {
  border: 2px solid var(--border);
  background: var(--surface);
  padding: 20px;
  text-decoration: none;
  color: var(--text);
  box-shadow: var(--shadow-md);
  transition: box-shadow 0.15s, transform 0.15s;
}

.docs-card:hover {
  box-shadow: var(--shadow-sm);
  transform: translate(1px, 1px);
}

.docs-card-icon { font-size: 18px; color: var(--accent); margin-bottom: 12px; }
.docs-card-name { font-size: 15px; font-weight: 600; margin-bottom: 6px; }
.docs-card-desc { font-size: 12px; color: var(--text-dim); line-height: 1.55; margin-bottom: 12px; }

.docs-card-meta {
  display: flex;
  gap: 12px;
  font-size: 10px;
  font-family: var(--font-mono);
  color: var(--text-faint);
}

.docs-card-meta-item { display: flex; align-items: center; gap: 4px; }

.docs-divider { border: none; border-top: 2px solid var(--border); margin: 32px 0; }

.docs-empty {
  text-align: center;
  padding: 64px 0;
}

.docs-empty-icon { font-size: 32px; color: var(--text-faint); margin-bottom: 12px; }
.docs-empty-title { font-size: 15px; font-weight: 600; margin-bottom: 4px; }
.docs-empty-sub { font-size: 12px; color: var(--text-dim); }
</style>

// apps/reference/src/routes/(app)/docs/+page.svelte
<script lang="ts">
  import type { PageData } from './$types';

  let { data }: { data: PageData } = $props();
</script>

<svelte:head>
  <title>Documentation — Snaplify</title>
  <meta name="description" content="Browse documentation sites." />
</svelte:head>

<section class="docs-list-page">
  <h1 class="page-title">Documentation</h1>

  {#if data.sites.length === 0}
    <div class="empty-state">
      <p>No documentation sites yet.</p>
    </div>
  {:else}
    <div class="docs-grid">
      {#each data.sites as site (site.id)}
        <a href="/docs/{site.slug}" class="docs-card">
          <h2 class="docs-card-title">{site.name}</h2>
          {#if site.description}
            <p class="docs-card-desc">{site.description}</p>
          {/if}
          <span class="docs-card-owner">by {site.owner.displayName ?? site.owner.username}</span>
        </a>
      {/each}
    </div>
  {/if}
</section>

<style>
  .docs-list-page {
    max-width: var(--layout-max-width, 1200px);
    margin: 0 auto;
    padding: var(--space-4, 1rem);
  }

  .page-title {
    font-size: var(--text-2xl, 1.875rem);
    margin-bottom: var(--space-6, 2rem);
    color: var(--color-text, inherit);
  }

  .docs-grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
    gap: var(--space-4, 1rem);
  }

  .docs-card {
    display: block;
    padding: var(--space-4, 1rem);
    border: 1px solid var(--color-border, #e5e7eb);
    border-radius: var(--radius-md, 0.375rem);
    text-decoration: none;
    color: var(--color-text, inherit);
  }

  .docs-card:hover {
    border-color: var(--color-primary, #3b82f6);
    background: var(--color-bg-hover, #f9fafb);
  }

  .docs-card-title {
    font-size: var(--text-lg, 1.125rem);
    font-weight: var(--font-weight-semibold, 600);
    margin-bottom: var(--space-1, 0.25rem);
  }

  .docs-card-desc {
    font-size: var(--text-sm, 0.875rem);
    color: var(--color-text-secondary, #6b7280);
    margin-bottom: var(--space-2, 0.5rem);
  }

  .docs-card-owner {
    font-size: var(--text-xs, 0.75rem);
    color: var(--color-text-muted, #9ca3af);
  }

  .empty-state {
    text-align: center;
    padding: var(--space-12, 3rem);
    color: var(--color-text-secondary, #6b7280);
  }
</style>
