// apps/reference/src/routes/(app)/[type]/[slug]/edit/+page.svelte
<script lang="ts">
  import { enhance } from '$app/forms';
  import ContentEditor from '$lib/components/ContentEditor.svelte';
  import type { PageData, ActionData } from './$types';

  let { data, form }: { data: PageData; form: ActionData } = $props();

  let title = $state(data.item.title);
  let description = $state(data.item.description ?? '');
  let seoDescription = $state(data.item.seoDescription ?? '');
  let tags = $state(data.item.tags.map((t) => t.name).join(', '));
  let contentBlocks = $state<unknown[]>(
    Array.isArray(data.item.content) ? (data.item.content as unknown[]) : [],
  );

  function handleEditorUpdate(blocks: unknown[]) {
    contentBlocks = blocks;
  }
</script>

<svelte:head>
  <title>Edit: {data.item.title} — Snaplify</title>
</svelte:head>

<div class="edit-page">
  {#if form?.error}
    <div class="form-error" role="alert">{form.error}</div>
  {/if}

  <form method="POST" use:enhance class="edit-form">
    <input type="hidden" name="content" value={JSON.stringify(contentBlocks)} />

    <div class="edit-topbar">
      <span class="topbar-status">{data.item.status}</span>
      <div class="topbar-actions">
        <button type="submit" name="action" value="save" class="topbar-btn topbar-btn-ghost">
          {data.item.status === 'published' ? 'Update' : 'Save Draft'}
        </button>
        {#if data.item.status !== 'published'}
          <button type="submit" name="action" value="publish" class="topbar-btn topbar-btn-primary">
            Publish
          </button>
        {/if}
      </div>
    </div>

    <div class="edit-body">
      <input
        class="title-input"
        name="title"
        type="text"
        bind:value={title}
        required
        placeholder="Title"
        maxlength="255"
      />

      <input
        class="description-input"
        name="description"
        type="text"
        bind:value={description}
        placeholder="Add a short description..."
        maxlength="2000"
      />

      <div class="editor-area">
        <ContentEditor content={data.item.content} onupdate={handleEditorUpdate} />
      </div>

      <div class="meta-section">
        <div class="meta-row">
          <label class="meta-label" for="tags">Tags</label>
          <input
            class="meta-input"
            id="tags"
            name="tags"
            type="text"
            bind:value={tags}
            placeholder="comma-separated"
          />
        </div>
        <div class="meta-row">
          <label class="meta-label" for="seo">SEO</label>
          <input
            class="meta-input"
            id="seo"
            name="seoDescription"
            type="text"
            bind:value={seoDescription}
            placeholder="Search engine description"
            maxlength="320"
          />
        </div>
      </div>
    </div>
  </form>
</div>

<style>
  .edit-page {
    max-width: 780px;
    margin: 0 auto;
    min-height: 80vh;
    display: flex;
    flex-direction: column;
  }

  .form-error {
    padding: var(--space-3, 0.75rem);
    background: rgba(248, 113, 113, 0.08);
    border: 1px solid var(--color-error, #f87171);
    color: var(--color-error, #f87171);
    border-radius: var(--radius-md, 0.25rem);
    font-size: var(--text-sm, 0.875rem);
    margin-bottom: var(--space-4, 1rem);
  }

  .edit-form {
    display: flex;
    flex-direction: column;
    flex: 1;
  }

  .edit-topbar {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: var(--space-2, 0.5rem) 0;
    margin-bottom: var(--space-4, 1rem);
    border-bottom: 1px solid var(--color-border, #272725);
  }

  .topbar-status {
    font-family: var(--font-mono, monospace);
    font-size: var(--text-xs, 0.6875rem);
    text-transform: uppercase;
    letter-spacing: 0.05em;
    color: var(--color-text-muted, #444440);
  }

  .topbar-actions {
    display: flex;
    gap: var(--space-2, 0.5rem);
  }

  .topbar-btn {
    padding: var(--space-1, 0.25rem) var(--space-4, 1rem);
    border-radius: var(--radius-md, 0.25rem);
    font-size: var(--text-sm, 0.875rem);
    font-family: var(--font-body, sans-serif);
    cursor: pointer;
    border: 1px solid var(--color-border, #272725);
    transition: background var(--transition-fast, 0.1s ease);
  }

  .topbar-btn-ghost {
    background: transparent;
    color: var(--color-text-secondary, #888884);
  }

  .topbar-btn-ghost:hover {
    background: var(--color-surface-alt, #141413);
    color: var(--color-text, #d8d5cf);
  }

  .topbar-btn-primary {
    background: var(--color-primary, #5b9cf6);
    border-color: var(--color-primary, #5b9cf6);
    color: var(--color-on-primary, #0c0c0b);
    font-weight: var(--font-weight-medium, 500);
  }

  .topbar-btn-primary:hover {
    opacity: 0.9;
  }

  .edit-body {
    flex: 1;
    display: flex;
    flex-direction: column;
  }

  .title-input {
    font-size: var(--text-3xl, 2rem);
    font-weight: var(--font-weight-bold, 700);
    font-family: var(--font-heading, sans-serif);
    color: var(--color-text, #d8d5cf);
    background: transparent;
    border: none;
    outline: none;
    padding: 0;
    margin-bottom: var(--space-2, 0.5rem);
    width: 100%;
  }

  .title-input::placeholder {
    color: var(--color-text-muted, #444440);
  }

  .description-input {
    font-size: var(--text-md, 1rem);
    color: var(--color-text-secondary, #888884);
    background: transparent;
    border: none;
    outline: none;
    padding: 0;
    margin-bottom: var(--space-6, 2rem);
    width: 100%;
  }

  .description-input::placeholder {
    color: var(--color-text-muted, #444440);
  }

  .editor-area {
    flex: 1;
    min-height: 400px;
  }

  .editor-area :global(.content-editor) {
    min-height: 400px;
  }

  .editor-area :global(.editor-wrapper) {
    border: none;
    border-radius: 0;
    padding: 0;
    background: transparent;
    min-height: 400px;
  }

  .editor-area :global(.ProseMirror) {
    padding: 0 !important;
  }

  .meta-section {
    margin-top: var(--space-6, 2rem);
    padding-top: var(--space-4, 1rem);
    border-top: 1px solid var(--color-border, #272725);
    display: flex;
    flex-direction: column;
    gap: var(--space-3, 0.75rem);
  }

  .meta-row {
    display: flex;
    align-items: center;
    gap: var(--space-3, 0.75rem);
  }

  .meta-label {
    font-family: var(--font-mono, monospace);
    font-size: var(--text-xs, 0.6875rem);
    text-transform: uppercase;
    letter-spacing: 0.05em;
    color: var(--color-text-muted, #444440);
    min-width: 40px;
  }

  .meta-input {
    flex: 1;
    font-size: var(--text-sm, 0.875rem);
    color: var(--color-text-secondary, #888884);
    background: transparent;
    border: none;
    outline: none;
    padding: 0;
    font-family: var(--font-mono, monospace);
  }

  .meta-input::placeholder {
    color: var(--color-text-muted, #444440);
  }
</style>

// layers/base/pages/events/[slug]/edit.vue
<script setup lang="ts">
import type { EventDetail } from '@commonpub/server';

definePageMeta({ middleware: 'auth' });

const route = useRoute();
const slug = route.params.slug as string;
const toast = useToast();
const router = useRouter();
const { user } = useAuth();

const { data: event } = await useFetch<EventDetail>(`/api/events/${slug}`);

if (!event.value) {
  throw createError({ statusCode: 404, statusMessage: 'Event not found' });
}

const isOwner = computed(() => user.value?.id === event.value?.createdById);
const isAdmin = computed(() => user.value?.role === 'admin');
if (!isOwner.value && !isAdmin.value) {
  throw createError({ statusCode: 403, statusMessage: 'Unauthorized' });
}

useSeoMeta({ title: `Edit ${event.value.title} — Events — ${useSiteName()}` });

const saving = ref(false);
const form = reactive({
  title: event.value.title,
  description: event.value.description ?? '',
  eventType: event.value.eventType,
  status: event.value.status,
  startDate: new Date(event.value.startDate).toISOString().slice(0, 16),
  endDate: new Date(event.value.endDate).toISOString().slice(0, 16),
  timezone: event.value.timezone,
  location: event.value.location ?? '',
  locationUrl: event.value.locationUrl ?? '',
  onlineUrl: event.value.onlineUrl ?? '',
  capacity: event.value.capacity ?? undefined as number | undefined,
  isFeatured: event.value.isFeatured,
});

async function submit(): Promise<void> {
  if (!form.title || !form.startDate || !form.endDate) {
    toast.error('Title, start date, and end date are required');
    return;
  }
  if (new Date(form.startDate) >= new Date(form.endDate)) {
    toast.error('End date must be after start date');
    return;
  }

  saving.value = true;
  try {
    const body: Record<string, unknown> = {
      title: form.title,
      status: form.status,
      eventType: form.eventType,
      startDate: new Date(form.startDate).toISOString(),
      endDate: new Date(form.endDate).toISOString(),
      timezone: form.timezone,
      isFeatured: form.isFeatured,
    };
    if (form.description) body.description = form.description;
    if (form.location) body.location = form.location;
    if (form.locationUrl) body.locationUrl = form.locationUrl;
    if (form.onlineUrl) body.onlineUrl = form.onlineUrl;
    if (form.capacity) body.capacity = form.capacity;

    await $fetch(`/api/events/${slug}`, { method: 'PUT', body });
    toast.success('Event updated');
    router.push(`/events/${slug}`);
  } catch {
    toast.error('Failed to update event');
  } finally {
    saving.value = false;
  }
}
</script>

<template>
  <div class="cpub-edit-event">
    <SectionHeader :title="`Edit: ${form.title}`" large />

    <form class="cpub-form" @submit.prevent="submit">
      <div class="cpub-form-field">
        <label class="cpub-form-label">Title *</label>
        <input v-model="form.title" class="cpub-form-input" required />
      </div>

      <div class="cpub-form-field">
        <label class="cpub-form-label">Description</label>
        <textarea v-model="form.description" class="cpub-form-textarea" rows="4" />
      </div>

      <div class="cpub-form-row">
        <div class="cpub-form-field">
          <label class="cpub-form-label">Type</label>
          <select v-model="form.eventType" class="cpub-form-input">
            <option value="in-person">In-Person</option>
            <option value="online">Online</option>
            <option value="hybrid">Hybrid</option>
          </select>
        </div>
        <div class="cpub-form-field">
          <label class="cpub-form-label">Status</label>
          <select v-model="form.status" class="cpub-form-input">
            <option value="draft">Draft</option>
            <option value="published">Published</option>
            <option value="active">Active</option>
            <option value="completed">Completed</option>
            <option value="cancelled">Cancelled</option>
          </select>
        </div>
      </div>

      <div class="cpub-form-row">
        <div class="cpub-form-field">
          <label class="cpub-form-label">Start Date *</label>
          <input v-model="form.startDate" type="datetime-local" class="cpub-form-input" required />
        </div>
        <div class="cpub-form-field">
          <label class="cpub-form-label">End Date *</label>
          <input v-model="form.endDate" type="datetime-local" class="cpub-form-input" required />
        </div>
      </div>

      <div class="cpub-form-row">
        <div class="cpub-form-field">
          <label class="cpub-form-label">Capacity</label>
          <input v-model.number="form.capacity" type="number" min="1" class="cpub-form-input" placeholder="Unlimited" />
        </div>
        <div class="cpub-form-field">
          <label class="cpub-form-label cpub-form-checkbox-label">
            <input type="checkbox" v-model="form.isFeatured" /> Featured Event
          </label>
        </div>
      </div>

      <div v-if="form.eventType !== 'online'" class="cpub-form-row">
        <div class="cpub-form-field">
          <label class="cpub-form-label">Location</label>
          <input v-model="form.location" class="cpub-form-input" placeholder="Venue name / address" />
        </div>
        <div class="cpub-form-field">
          <label class="cpub-form-label">Location URL</label>
          <input v-model="form.locationUrl" type="url" class="cpub-form-input" placeholder="Map link" />
        </div>
      </div>

      <div v-if="form.eventType !== 'in-person'" class="cpub-form-field">
        <label class="cpub-form-label">Online URL</label>
        <input v-model="form.onlineUrl" type="url" class="cpub-form-input" placeholder="Meeting link" />
      </div>

      <div class="cpub-form-actions">
        <NuxtLink :to="`/events/${slug}`" class="cpub-btn cpub-btn-sm">Cancel</NuxtLink>
        <button type="submit" class="cpub-btn cpub-btn-primary cpub-btn-sm" :disabled="saving">
          <i :class="saving ? 'fa-solid fa-circle-notch fa-spin' : 'fa-solid fa-check'"></i>
          Save Changes
        </button>
      </div>
    </form>
  </div>
</template>

<style scoped>
.cpub-edit-event { max-width: 640px; margin: 0 auto; padding: 32px; }
.cpub-form { display: flex; flex-direction: column; gap: var(--space-4); margin-top: 24px; }
.cpub-form-field { display: flex; flex-direction: column; gap: 4px; }
.cpub-form-label { font-family: var(--font-mono); font-size: 10px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.06em; color: var(--text-dim); }
.cpub-form-input { font-size: 13px; padding: 8px 12px; border: var(--border-width-default) solid var(--border); background: var(--surface); color: var(--text); outline: none; }
.cpub-form-input:focus { border-color: var(--accent); }
.cpub-form-textarea { font-size: 13px; padding: 8px 12px; border: var(--border-width-default) solid var(--border); background: var(--surface); color: var(--text); outline: none; resize: vertical; font-family: inherit; }
.cpub-form-row { display: grid; grid-template-columns: 1fr 1fr; gap: var(--space-4); }
.cpub-form-checkbox-label { display: flex; align-items: center; gap: 6px; margin-top: 18px; }
.cpub-form-actions { display: flex; gap: var(--space-3); justify-content: flex-end; padding-top: var(--space-4); border-top: var(--border-width-default) solid var(--border2); }

@media (max-width: 768px) {
  .cpub-edit-event { padding: 16px; }
  .cpub-form-row { grid-template-columns: 1fr; }
}
</style>
