// packages/explainer/vue/components/ExplainerViewer.vue
<script setup lang="ts">
/**
 * ExplainerViewer — standalone section-by-section viewer.
 *
 * No Nuxt dependencies. Works in any Vue 3 app.
 * Engagement actions (like, bookmark, share) are optional callbacks via props.
 */
import { ref, computed, watch, onMounted, onUnmounted } from 'vue';
import { useExplainerSections } from '../composables/useExplainerSections.js';
import { useExplainerProgress } from '../composables/useExplainerProgress.js';

type BlockTuple = [string, Record<string, unknown>];

export interface ExplainerContent {
  title: string;
  description?: string | null;
  coverImageUrl?: string | null;
  content: BlockTuple[];
  author?: {
    displayName?: string | null;
    username?: string;
    avatarUrl?: string | null;
  } | null;
  publishedAt?: string | null;
  createdAt?: string;
}

const props = withDefaults(defineProps<{
  content: ExplainerContent;
  /** Show engagement buttons (like, bookmark, share) */
  showEngagement?: boolean;
  /** Callback when user clicks edit */
  onEdit?: () => void;
}>(), {
  showEngagement: false,
});

const blocks = computed<BlockTuple[]>(() => {
  const raw = props.content?.content;
  if (!Array.isArray(raw)) return [];
  return raw as BlockTuple[];
});

const { sections, ranges } = useExplainerSections(blocks, props.content.title);
const totalSections = computed(() => sections.value.length);
const {
  activeSection,
  completedSections,
  progressPct,
  goToSection,
  prevSection,
  nextSection,
  markComplete,
} = useExplainerProgress(totalSections);

// Checkpoint animation state
const checkpointVisible = ref(false);

watch(activeSection, () => {
  checkpointVisible.value = false;
  const viewport = document.querySelector('.cpub-section-viewport');
  if (viewport) viewport.scrollTop = 0;
});

const currentSection = computed(() => sections.value[activeSection.value]);
const currentRange = computed(() => ranges.value[activeSection.value]);

const authorName = computed(() =>
  props.content.author?.displayName || props.content.author?.username || '',
);

const publishDate = computed(() => {
  const d = props.content.publishedAt || props.content.createdAt;
  if (!d) return '';
  return new Date(d).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
});

// Keyboard navigation
function onKeydown(e: KeyboardEvent): void {
  if (e.key === 'ArrowLeft') { prevSection(); e.preventDefault(); }
  if (e.key === 'ArrowRight') { nextSection(); e.preventDefault(); }
}

onMounted(() => document.addEventListener('keydown', onKeydown));
onUnmounted(() => document.removeEventListener('keydown', onKeydown));

function onQuizAnswered(_idx: number, correct: boolean): void {
  if (correct) {
    markComplete(activeSection.value);
    checkpointVisible.value = true;
  }
}

function onCheckpointReached(): void {
  markComplete(activeSection.value);
  checkpointVisible.value = true;
}
</script>

<template>
  <div class="cpub-explainer-view">
    <!-- PROGRESS BAR -->
    <div class="cpub-progress-line">
      <div class="cpub-progress-line-fill" :style="{ width: progressPct + '%' }"></div>
    </div>

    <!-- TOPBAR -->
    <header class="cpub-explainer-topbar">
      <div class="cpub-explainer-badge">EXPLAINER</div>
      <span class="cpub-topbar-title">{{ content.title }}</span>
      <div class="cpub-topbar-spacer"></div>
      <span class="cpub-progress-text">Section {{ activeSection + 1 }} of {{ totalSections }}</span>
      <div class="cpub-topbar-divider"></div>
      <div class="cpub-nav-btn-group">
        <button class="cpub-icon-btn" :disabled="activeSection === 0" aria-label="Previous section" @click="prevSection">
          &larr;
        </button>
        <button class="cpub-icon-btn" :disabled="activeSection === totalSections - 1" aria-label="Next section" @click="nextSection">
          &rarr;
        </button>
      </div>
      <button v-if="onEdit" class="cpub-icon-btn" title="Edit" aria-label="Edit explainer" @click="onEdit">
        &#9998;
      </button>
    </header>

    <!-- MAIN LAYOUT -->
    <div class="cpub-explainer-layout">
      <!-- SIDEBAR TOC -->
      <nav class="cpub-explainer-sidebar">
        <div class="cpub-toc-header">Contents</div>
        <ul class="cpub-toc-list">
          <li
            v-for="(section, i) in sections"
            :key="i"
            class="cpub-toc-item"
            :class="{ completed: completedSections.has(i), active: activeSection === i }"
          >
            <button type="button" :aria-label="`Go to section ${i + 1}: ${section.title}`" @click="goToSection(i)">
              <span class="cpub-toc-icon">
                <template v-if="completedSections.has(i)">&#10003;</template>
                <template v-else-if="activeSection === i">&rarr;</template>
              </span>
              <span class="cpub-toc-num">{{ String(i + 1).padStart(2, '0') }}</span>
              <span class="cpub-toc-label">{{ section.title }}</span>
            </button>
          </li>
        </ul>

        <!-- Author info -->
        <div v-if="content.author" class="cpub-sidebar-author">
          <div class="cpub-sidebar-author-avatar">
            <img v-if="content.author.avatarUrl" :src="content.author.avatarUrl" :alt="authorName" />
            <span v-else class="cpub-sidebar-author-initials">{{ authorName.charAt(0).toUpperCase() }}</span>
          </div>
          <div class="cpub-sidebar-author-info">
            <span class="cpub-sidebar-author-name">{{ authorName }}</span>
            <time v-if="publishDate" class="cpub-sidebar-author-date">{{ publishDate }}</time>
          </div>
        </div>
      </nav>

      <!-- MAIN CONTENT -->
      <main class="cpub-explainer-main">
        <div class="cpub-section-viewport">
          <div class="cpub-content-wrap" :key="activeSection">
            <!-- Cover image (first section only) -->
            <div v-if="activeSection === 0 && content.coverImageUrl" class="cpub-explainer-cover">
              <img :src="content.coverImageUrl" :alt="content.title" />
            </div>

            <!-- Section header -->
            <div v-if="currentSection?.tag" class="cpub-section-tag">{{ currentSection.tag }}</div>
            <h1 class="cpub-section-title">{{ currentSection?.title || content.title }}</h1>

            <!-- Mobile author -->
            <div v-if="activeSection === 0 && content.author" class="cpub-mobile-author">
              <span class="cpub-mobile-author-name">{{ authorName }}</span>
              <span class="cpub-mobile-author-sep">&middot;</span>
              <time v-if="publishDate">{{ publishDate }}</time>
            </div>

            <p v-if="currentSection?.body" class="cpub-section-intro">{{ currentSection.body }}</p>

            <!-- Section body blocks -->
            <div class="cpub-body-text">
              <template v-if="currentRange && currentRange.start < currentRange.end">
                <BlockRenderer
                  :blocks="blocks"
                  :start-index="currentRange.start"
                  :end-index="currentRange.end"
                  @quiz-answered="onQuizAnswered"
                  @checkpoint-reached="onCheckpointReached"
                />
              </template>
              <p v-else class="cpub-empty-section">This section has no content blocks yet.</p>
            </div>

            <!-- CHECKPOINT -->
            <div class="cpub-checkpoint" :class="{ visible: checkpointVisible }">
              <span>&#10003;</span>
              <span class="cpub-checkpoint-text">Section {{ activeSection + 1 }} complete</span>
              <span class="cpub-checkpoint-sub">+1 section &middot; {{ totalSections - activeSection - 1 }} remaining</span>
            </div>

            <!-- SECTION NAV FOOTER -->
            <div class="cpub-section-nav">
              <button v-if="activeSection > 0" class="cpub-prev-btn" @click="prevSection">
                &larr; {{ sections[activeSection - 1]?.title }}
              </button>
              <div v-else></div>

              <div class="cpub-progress-dots" role="group" aria-label="Section progress">
                <button
                  v-for="(_, i) in totalSections"
                  :key="i"
                  type="button"
                  class="cpub-dot"
                  :class="{ done: completedSections.has(i), active: i === activeSection }"
                  :aria-label="`Section ${i + 1}`"
                  :aria-current="i === activeSection ? 'step' : undefined"
                  @click="goToSection(i)"
                ></button>
              </div>

              <button v-if="activeSection < totalSections - 1" class="cpub-next-btn" @click="nextSection">
                Next: {{ sections[activeSection + 1]?.title }} &rarr;
              </button>
              <div v-else></div>
            </div>
          </div>
        </div>
      </main>
    </div>
  </div>
</template>

<style scoped>
/* Progress bar */
.cpub-progress-line { position: fixed; top: 0; left: 0; right: 0; height: 3px; background: var(--surface3); z-index: 200; }
.cpub-progress-line-fill { height: 100%; background: var(--accent); transition: width 0.4s ease; }

/* Topbar */
.cpub-explainer-topbar { position: fixed; top: 3px; left: 0; right: 0; height: 48px; background: var(--surface); border-bottom: var(--border-width-default, 2px) solid var(--border); display: flex; align-items: center; gap: 10px; padding: 0 16px; z-index: 100; }
.cpub-explainer-badge { font-family: var(--font-mono); font-size: 10px; font-weight: 600; letter-spacing: 0.08em; color: var(--accent); background: var(--accent-bg); border: var(--border-width-default) solid var(--accent-border); padding: 3px 8px; white-space: nowrap; flex-shrink: 0; }
.cpub-topbar-title { font-size: 13px; font-weight: 600; color: var(--text); white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
.cpub-topbar-spacer { flex: 1; }
.cpub-progress-text { font-family: var(--font-mono); font-size: 11px; color: var(--text-dim); white-space: nowrap; flex-shrink: 0; }
.cpub-topbar-divider { width: 2px; height: 20px; background: var(--border); flex-shrink: 0; }
.cpub-icon-btn { width: 30px; height: 30px; display: flex; align-items: center; justify-content: center; background: var(--surface); border: var(--border-width-default, 2px) solid var(--border); color: var(--text-dim); cursor: pointer; font-size: 12px; transition: background 0.1s, color 0.1s; flex-shrink: 0; }
.cpub-icon-btn:hover:not(:disabled) { background: var(--surface2); color: var(--text); }
.cpub-icon-btn:disabled { opacity: 0.3; cursor: not-allowed; }
.cpub-nav-btn-group { display: flex; gap: 4px; flex-shrink: 0; }

/* Layout */
.cpub-explainer-layout { display: flex; margin-top: 51px; height: calc(100vh - 51px); overflow: hidden; }

/* Sidebar */
.cpub-explainer-sidebar { width: 200px; flex-shrink: 0; background: var(--surface); border-right: var(--border-width-default, 2px) solid var(--border); display: flex; flex-direction: column; overflow-y: auto; }
.cpub-toc-header { padding: 14px 14px 10px; font-family: var(--font-mono); font-size: 9px; letter-spacing: 0.12em; color: var(--text-faint); text-transform: uppercase; border-bottom: var(--border-width-default, 2px) solid var(--border); }
.cpub-toc-list { list-style: none; padding: 6px 0; margin: 0; }
.cpub-toc-item button { display: flex; align-items: center; gap: 8px; padding: 8px 14px; width: 100%; background: none; border: none; text-align: left; color: var(--text-dim); font-size: 12px; font-family: inherit; line-height: 1.4; border-left: 3px solid transparent; transition: background 0.1s, color 0.1s, border-color 0.1s; cursor: pointer; }
.cpub-toc-item button:hover { background: var(--surface2); color: var(--text); }
.cpub-toc-item.active button { background: var(--accent-bg); border-left-color: var(--accent); color: var(--accent); font-weight: 500; }
.cpub-toc-item.completed button { color: var(--text-dim); }
.cpub-toc-icon { width: 14px; font-size: 10px; flex-shrink: 0; text-align: center; }
.cpub-toc-item.completed .cpub-toc-icon { color: var(--green); }
.cpub-toc-item.active .cpub-toc-icon { color: var(--accent); }
.cpub-toc-num { font-family: var(--font-mono); font-size: 9px; color: var(--text-faint); flex-shrink: 0; }
.cpub-toc-item.active .cpub-toc-num { color: var(--accent-border); }
.cpub-toc-item.completed .cpub-toc-num { color: var(--green-border); }
.cpub-toc-label { flex: 1; font-size: 12px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }

/* Sidebar author */
.cpub-sidebar-author { display: flex; align-items: center; gap: 8px; padding: 12px 14px; border-top: var(--border-width-default, 2px) solid var(--border); margin-top: auto; }
.cpub-sidebar-author-avatar { width: 24px; height: 24px; border-radius: var(--radius-full); background: var(--surface3); border: var(--border-width-default, 2px) solid var(--border); display: flex; align-items: center; justify-content: center; overflow: hidden; flex-shrink: 0; }
.cpub-sidebar-author-avatar img { width: 100%; height: 100%; object-fit: cover; }
.cpub-sidebar-author-initials { font-family: var(--font-mono); font-size: 9px; font-weight: 600; color: var(--text-dim); }
.cpub-sidebar-author-info { display: flex; flex-direction: column; min-width: 0; }
.cpub-sidebar-author-name { font-size: 11px; font-weight: 500; color: var(--text); white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
.cpub-sidebar-author-date { font-size: 10px; color: var(--text-faint); font-family: var(--font-mono); }

/* Mobile author (hidden on desktop) */
.cpub-mobile-author { display: none; align-items: center; gap: 6px; font-size: 12px; color: var(--text-faint); margin-bottom: 20px; }
.cpub-mobile-author-name { color: var(--text-dim); font-weight: 500; }
.cpub-mobile-author-sep { color: var(--text-faint); }
.cpub-mobile-author time { font-family: var(--font-mono); font-size: 11px; }

/* Main content */
.cpub-explainer-main { flex: 1; overflow: hidden; background: var(--bg); }
.cpub-section-viewport { height: 100%; overflow-y: auto; }
.cpub-content-wrap { max-width: 720px; margin: 0 auto; padding: 44px 36px 80px; min-height: calc(100vh - 51px - 80px); }

/* Cover */
.cpub-explainer-cover { width: 100%; max-height: 320px; overflow: hidden; margin-bottom: 20px; border: var(--border-width-default) solid var(--border); }
.cpub-explainer-cover img { width: 100%; height: 100%; max-height: 320px; object-fit: cover; display: block; }

/* Section tag */
.cpub-section-tag { font-family: var(--font-mono); font-size: 10px; letter-spacing: 0.12em; color: var(--text-faint); margin-bottom: 14px; display: flex; align-items: center; gap: 6px; }
.cpub-section-tag::before { content: ''; display: inline-block; width: 24px; height: 2px; background: var(--border); }

/* Section title */
.cpub-section-title { font-size: 30px; font-weight: 700; color: var(--text); line-height: 1.25; margin-bottom: 24px; letter-spacing: -0.02em; }
.cpub-section-intro { font-size: 15px; color: var(--text-dim); line-height: 1.75; margin-bottom: 24px; max-width: 560px; }

/* Body */
.cpub-body-text { font-size: 15px; line-height: 1.75; color: var(--text); margin-bottom: 20px; }
.cpub-empty-section { color: var(--text-faint); font-style: italic; padding: 40px 0; text-align: center; }

/* Checkpoint */
.cpub-checkpoint { display: flex; align-items: center; gap: 10px; padding: 12px 16px; background: var(--green-bg); border: var(--border-width-default) solid var(--green); margin-top: 24px; font-size: 13px; color: var(--green); opacity: 0; transform: translateY(8px); transition: opacity 0.4s ease, transform 0.4s ease; }
.cpub-checkpoint.visible { opacity: 1; transform: translateY(0); }
.cpub-checkpoint-text { font-weight: 600; }
.cpub-checkpoint-sub { margin-left: auto; font-size: 11px; font-family: var(--font-mono); color: var(--green-border); }

/* Section nav footer */
.cpub-section-nav { display: flex; align-items: center; justify-content: space-between; margin-top: 48px; padding-top: 24px; border-top: var(--border-width-default, 2px) solid var(--border); }
.cpub-progress-dots { display: flex; align-items: center; gap: 5px; }
.cpub-dot { width: 7px; height: 7px; padding: 0; border: none; border-radius: 50%; background: var(--border2); transition: background 0.15s, transform 0.15s; cursor: pointer; }
.cpub-dot.done { background: var(--green); }
.cpub-dot.active { background: var(--accent); transform: scale(1.3); }
.cpub-dot:hover { transform: scale(1.4); }
.cpub-next-btn { display: flex; align-items: center; gap: 8px; padding: 10px 18px; background: var(--accent); border: var(--border-width-default, 2px) solid var(--border); color: var(--color-on-accent); font-size: 13px; font-weight: 600; cursor: pointer; box-shadow: var(--shadow-sm); transition: box-shadow 0.1s, transform 0.1s; }
.cpub-next-btn:hover { box-shadow: var(--shadow-sm); transform: translate(1px, 1px); }
.cpub-prev-btn { display: flex; align-items: center; gap: 8px; padding: 10px 18px; background: var(--surface); border: var(--border-width-default, 2px) solid var(--border); color: var(--text); font-size: 13px; font-weight: 500; cursor: pointer; transition: box-shadow 0.1s; }
.cpub-prev-btn:hover { box-shadow: var(--shadow-sm); }

/* Responsive */
@media (max-width: 768px) {
  .cpub-explainer-sidebar { display: none; }
  .cpub-mobile-author { display: flex; }
  .cpub-content-wrap { padding: 24px 16px 48px; }
  .cpub-section-nav { flex-direction: column; gap: 16px; }
  .cpub-section-title { font-size: 24px; }
}
</style>

// apps/reference/src/lib/components/explainer/ExplainerViewer.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import {
    createProgressState,
    markSectionCompleted,
    canAccessSection,
    getCompletionPercentage,
    generateToc,
    type ExplainerSection,
    type ExplainerProgressState,
  } from '@snaplify/explainer';
  import ExplainerProgress from './ExplainerProgress.svelte';
  import ExplainerToc from './ExplainerToc.svelte';
  import ExplainerSectionComponent from './ExplainerSection.svelte';
  import ExplainerNav from './ExplainerNav.svelte';

  let {
    sections,
    title,
    storageKey,
  }: {
    sections: ExplainerSection[];
    title: string;
    storageKey: string;
  } = $props();

  let progress = $state<ExplainerProgressState>(createProgressState(sections));
  let activeSectionIndex = $state(0);
  let activeSectionId = $derived(sections[activeSectionIndex]?.id ?? '');

  let tocItems = $derived(generateToc(sections, progress, activeSectionId));
  let percentage = $derived(getCompletionPercentage(progress));

  onMount(() => {
    loadProgress();
    setupKeyboardNav();
    setupScrollObserver();
  });

  function loadProgress() {
    try {
      const saved = localStorage.getItem(storageKey);
      if (saved) {
        const parsed = JSON.parse(saved) as ExplainerProgressState;
        const merged = createProgressState(sections);
        for (const [id, p] of Object.entries(parsed.sections)) {
          if (merged.sections[id]) {
            merged.sections[id] = p;
          }
        }
        merged.startedAt = parsed.startedAt;
        merged.lastAccessedAt = new Date().toISOString();
        progress = merged;
      }
    } catch {
      // Ignore corrupt localStorage
    }
  }

  function saveProgress() {
    try {
      localStorage.setItem(storageKey, JSON.stringify(progress));
    } catch {
      // Ignore full localStorage
    }
  }

  function handleSectionComplete(sectionId: string, quizScore?: number) {
    progress = markSectionCompleted(progress, sectionId, quizScore);
    saveProgress();
  }

  function scrollToSection(anchor: string) {
    const el = document.getElementById(anchor);
    if (el) {
      el.scrollIntoView({ behavior: 'smooth' });
    }
  }

  function handleTocSelect(anchor: string) {
    scrollToSection(anchor);
  }

  function handlePrevious() {
    if (activeSectionIndex > 0) {
      const prevSection = sections[activeSectionIndex - 1];
      if (prevSection) scrollToSection(prevSection.anchor);
    }
  }

  function handleNext() {
    if (activeSectionIndex < sections.length - 1) {
      const nextSection = sections[activeSectionIndex + 1];
      if (nextSection && canAccessSection(progress, sections, nextSection.id)) {
        scrollToSection(nextSection.anchor);
      }
    }
  }

  function setupKeyboardNav() {
    function handleKey(e: KeyboardEvent) {
      if (e.target instanceof HTMLInputElement || e.target instanceof HTMLTextAreaElement) return;

      if (e.key === 'ArrowDown' || e.key === 'ArrowRight') {
        e.preventDefault();
        handleNext();
      } else if (e.key === 'ArrowUp' || e.key === 'ArrowLeft') {
        e.preventDefault();
        handlePrevious();
      }
    }

    document.addEventListener('keydown', handleKey);
    return () => document.removeEventListener('keydown', handleKey);
  }

  function setupScrollObserver() {
    const observer = new IntersectionObserver(
      (entries) => {
        for (const entry of entries) {
          if (entry.isIntersecting) {
            const el = entry.target as HTMLElement;
            const sectionId = el.dataset.sectionId;
            const sectionType = el.dataset.sectionType;
            if (sectionId) {
              const idx = sections.findIndex((s) => s.id === sectionId);
              if (idx >= 0) activeSectionIndex = idx;

              if (sectionType === 'text' && !progress.sections[sectionId]?.completed) {
                handleSectionComplete(sectionId);
              }
            }
          }
        }
      },
      { threshold: 0.5 },
    );

    setTimeout(() => {
      const sectionEls = document.querySelectorAll('.explainer-section');
      sectionEls.forEach((el) => observer.observe(el));
    }, 0);

    return () => observer.disconnect();
  }
</script>

<div class="exp-layout">
  <!-- Sidebar with TOC + progress -->
  <aside class="exp-sidebar">
    <div class="exp-sidebar-header">
      <span class="exp-sidebar-label">Explainer</span>
      <span class="exp-sidebar-pct">{percentage}%</span>
    </div>

    <div class="exp-progress-bar">
      <div class="exp-progress-fill" style="width: {percentage}%;"></div>
    </div>

    <nav class="exp-nav" aria-label="Section navigation">
      {#each sections as section, i}
        {@const sectionProgress = progress.sections[section.id]}
        {@const isActive = activeSectionId === section.id}
        {@const isCompleted = sectionProgress?.completed ?? false}
        {@const isLocked = !canAccessSection(progress, sections, section.id)}
        <button
          class="exp-nav-item"
          class:exp-nav-active={isActive}
          class:exp-nav-completed={isCompleted}
          class:exp-nav-locked={isLocked}
          onclick={() => !isLocked && scrollToSection(section.anchor)}
          disabled={isLocked}
          aria-current={isActive ? 'step' : undefined}
        >
          <span class="exp-nav-dot">
            {#if isCompleted}
              <svg width="10" height="10" viewBox="0 0 10 10" fill="none" aria-hidden="true">
                <path d="M2 5l2 2 4-4" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
              </svg>
            {:else}
              <span class="exp-nav-num">{i + 1}</span>
            {/if}
          </span>
          <span class="exp-nav-title">{section.title}</span>
          {#if section.type !== 'text'}
            <span class="exp-nav-tag">{section.type}</span>
          {/if}
        </button>
      {/each}
    </nav>
  </aside>

  <!-- Main content area -->
  <main class="exp-main">
    <header class="exp-header">
      <h1 class="exp-title">{title}</h1>
      <ExplainerProgress {percentage} />
    </header>

    {#each sections as section, i}
      <div
        class="exp-section"
        class:exp-section-alt={i % 2 === 1}
        id={section.anchor}
      >
        <span class="exp-section-num" aria-hidden="true">{String(i + 1).padStart(2, '0')}</span>

        {#if section.type !== 'text'}
          <span class="exp-section-tag">{section.type}</span>
        {/if}

        <ExplainerSectionComponent
          {section}
          locked={!canAccessSection(progress, sections, section.id)}
          completed={progress.sections[section.id]?.completed ?? false}
          onsectioncomplete={handleSectionComplete}
        />

        <!-- Interactive embed zone -->
        {#if section.type === 'interactive'}
          <div class="exp-embed">
            <span class="exp-embed-label">Interactive: {section.title}</span>
          </div>
        {/if}
      </div>
    {/each}

    <!-- Bottom nav -->
    <div class="exp-bottom-nav">
      <div class="exp-dots">
        {#each sections as section, i}
          <button
            class="exp-dot"
            class:exp-dot-active={i === activeSectionIndex}
            class:exp-dot-done={progress.sections[section.id]?.completed}
            onclick={() => scrollToSection(section.anchor)}
            aria-label="Go to section {i + 1}"
          ></button>
        {/each}
      </div>

      <ExplainerNav
        hasPrevious={activeSectionIndex > 0}
        hasNext={activeSectionIndex < sections.length - 1 &&
          canAccessSection(progress, sections, sections[activeSectionIndex + 1]?.id ?? '')}
        onprevious={handlePrevious}
        onnext={handleNext}
      />
    </div>
  </main>
</div>

<style>
  /* Full-height explainer layout */
  .exp-layout {
    display: grid;
    grid-template-columns: 200px 1fr;
    min-height: 100vh;
  }

  /* Sidebar */
  .exp-sidebar {
    position: sticky;
    top: 0;
    height: 100vh;
    overflow-y: auto;
    border-right: 1px solid var(--color-border, #272725);
    background: var(--color-surface, #0c0c0b);
    padding: var(--space-4, 1rem) 0;
  }

  .exp-sidebar-header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 0 var(--space-3, 0.75rem) var(--space-3, 0.75rem);
  }

  .exp-sidebar-label {
    font-family: var(--font-mono, monospace);
    font-size: 9px;
    text-transform: uppercase;
    letter-spacing: 0.1em;
    color: var(--color-text-muted, #444440);
  }

  .exp-sidebar-pct {
    font-family: var(--font-mono, monospace);
    font-size: 11px;
    color: var(--color-accent, #5b9cf6);
    font-weight: 700;
  }

  .exp-progress-bar {
    height: 2px;
    background: var(--color-border, #272725);
    margin: 0 var(--space-3, 0.75rem) var(--space-3, 0.75rem);
  }

  .exp-progress-fill {
    height: 100%;
    background: var(--color-accent, #5b9cf6);
    transition: width 0.3s ease;
  }

  /* Nav items */
  .exp-nav {
    display: flex;
    flex-direction: column;
    gap: 1px;
  }

  .exp-nav-item {
    display: flex;
    align-items: center;
    gap: var(--space-2, 0.5rem);
    padding: var(--space-2, 0.5rem) var(--space-3, 0.75rem);
    border: none;
    background: transparent;
    cursor: pointer;
    text-align: left;
    color: var(--color-text-secondary, #888884);
    width: 100%;
  }

  .exp-nav-item:hover:not(:disabled) {
    background: var(--color-surface-alt, #141413);
    color: var(--color-text, #d8d5cf);
  }

  .exp-nav-active {
    background: var(--color-surface-alt, #141413);
    color: var(--color-text, #d8d5cf);
    border-left: 2px solid var(--color-accent, #5b9cf6);
  }

  .exp-nav-completed {
    color: var(--color-success, #4ade80);
  }

  .exp-nav-locked {
    opacity: 0.4;
    cursor: not-allowed;
  }

  .exp-nav-dot {
    width: 18px;
    height: 18px;
    border-radius: var(--radius-full, 50%);
    border: 1px solid var(--color-border-strong, #333330);
    display: flex;
    align-items: center;
    justify-content: center;
    flex-shrink: 0;
    font-size: 9px;
    font-family: var(--font-mono, monospace);
  }

  .exp-nav-active .exp-nav-dot {
    border-color: var(--color-accent, #5b9cf6);
    color: var(--color-accent, #5b9cf6);
  }

  .exp-nav-completed .exp-nav-dot {
    border-color: var(--color-success, #4ade80);
    background: rgba(74, 222, 128, 0.1);
    color: var(--color-success, #4ade80);
  }

  .exp-nav-num {
    font-size: 9px;
    color: inherit;
  }

  .exp-nav-title {
    font-size: 11px;
    flex: 1;
    min-width: 0;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }

  .exp-nav-tag {
    font-family: var(--font-mono, monospace);
    font-size: 8px;
    text-transform: uppercase;
    letter-spacing: 0.06em;
    color: var(--color-accent, #5b9cf6);
    flex-shrink: 0;
  }

  /* Main content */
  .exp-main {
    overflow-y: auto;
  }

  .exp-header {
    padding: var(--space-8, 2rem) var(--space-10, 3rem);
    max-width: 720px;
    margin: 0 auto;
  }

  .exp-title {
    font-size: 30px;
    font-weight: 700;
    color: var(--color-text, #d8d5cf);
    line-height: 1.2;
    margin: 0 0 var(--space-4, 1rem);
  }

  /* Sections */
  .exp-section {
    position: relative;
    min-height: 80vh;
    padding: var(--space-12, 3rem) var(--space-10, 3rem);
    max-width: 720px;
    margin: 0 auto;
  }

  .exp-section-alt {
    background: var(--color-surface-alt, #141413);
    max-width: none;
    padding-left: calc((100% - 720px) / 2 + 3rem);
    padding-right: calc((100% - 720px) / 2 + 3rem);
  }

  .exp-section-num {
    position: absolute;
    top: var(--space-8, 2rem);
    right: var(--space-4, 1rem);
    font-family: var(--font-mono, monospace);
    font-size: 80px;
    font-weight: 700;
    color: var(--color-text-muted, #444440);
    opacity: 0.08;
    line-height: 1;
    pointer-events: none;
    user-select: none;
  }

  .exp-section-tag {
    display: inline-block;
    font-family: var(--font-mono, monospace);
    font-size: 10px;
    text-transform: uppercase;
    letter-spacing: 0.1em;
    color: var(--color-accent, #5b9cf6);
    margin-bottom: var(--space-3, 0.75rem);
  }

  /* Interactive embed zone */
  .exp-embed {
    margin-top: var(--space-6, 1.5rem);
    padding: var(--space-8, 2rem);
    border: 1px dashed var(--color-border, #272725);
    border-radius: var(--radius-sm, 4px);
    background: var(--color-surface, #0c0c0b);
    text-align: center;
  }

  .exp-embed-label {
    font-family: var(--font-mono, monospace);
    font-size: 11px;
    color: var(--color-text-muted, #444440);
    text-transform: uppercase;
    letter-spacing: 0.06em;
  }

  /* Bottom nav */
  .exp-bottom-nav {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: var(--space-4, 1rem);
    padding: var(--space-8, 2rem) var(--space-10, 3rem);
    border-top: 1px solid var(--color-border, #272725);
    max-width: 720px;
    margin: 0 auto;
  }

  .exp-dots {
    display: flex;
    gap: 6px;
  }

  .exp-dot {
    width: 8px;
    height: 8px;
    border-radius: var(--radius-full, 50%);
    border: 1px solid var(--color-border-strong, #333330);
    background: transparent;
    cursor: pointer;
    padding: 0;
  }

  .exp-dot:hover {
    border-color: var(--color-text-secondary, #888884);
  }

  .exp-dot-active {
    background: var(--color-accent, #5b9cf6);
    border-color: var(--color-accent, #5b9cf6);
  }

  .exp-dot-done {
    background: var(--color-success, #4ade80);
    border-color: var(--color-success, #4ade80);
  }

  /* Responsive */
  @media (max-width: 768px) {
    .exp-layout {
      grid-template-columns: 1fr;
    }

    .exp-sidebar {
      display: none;
    }

    .exp-section {
      min-height: auto;
      padding: var(--space-8, 2rem) var(--space-4, 1rem);
    }

    .exp-section-alt {
      padding-left: var(--space-4, 1rem);
      padding-right: var(--space-4, 1rem);
    }

    .exp-section-num {
      font-size: 48px;
    }

    .exp-header {
      padding: var(--space-6, 1.5rem) var(--space-4, 1rem);
    }

    .exp-title {
      font-size: 24px;
    }
  }
</style>
