// packages/explainer/vue/components/editor-v2/SectionList.vue
<script setup lang="ts">
import { ref, computed } from 'vue';
import type { ExplainerDocSection } from '@commonpub/explainer';
import { getModule } from '../../../modules/registry';

const props = defineProps<{
  sections: ExplainerDocSection[];
  selectedId: string | null;
}>();

const emit = defineEmits<{
  select: [sectionId: string];
  add: [];
  move: [fromIndex: number, toIndex: number];
  delete: [sectionId: string];
  duplicate: [sectionId: string];
}>();

function getModuleColor(section: ExplainerDocSection): string {
  const mod = section.module ? getModule(section.module.type) : getModule('text-only');
  return mod?.meta.color ?? '#6b7280';
}

function getModuleName(section: ExplainerDocSection): string {
  const mod = section.module ? getModule(section.module.type) : getModule('text-only');
  return mod?.meta.name ?? 'Text';
}

// Drag state
const dragIdx = ref<number | null>(null);
const dropIdx = ref<number | null>(null);

function onDragStart(idx: number, e: DragEvent): void {
  dragIdx.value = idx;
  if (e.dataTransfer) {
    e.dataTransfer.effectAllowed = 'move';
    e.dataTransfer.setData('text/plain', String(idx));
  }
}

function onDragOver(idx: number, e: DragEvent): void {
  if (dragIdx.value === idx) return;
  e.preventDefault();
  dropIdx.value = idx;
}

function onDrop(idx: number): void {
  if (dragIdx.value !== null && dragIdx.value !== idx) {
    emit('move', dragIdx.value, idx);
  }
  dragIdx.value = null;
  dropIdx.value = null;
}

function onDragEnd(): void {
  dragIdx.value = null;
  dropIdx.value = null;
}
</script>

<template>
  <div class="cpub-section-list">
    <div
      v-for="(section, idx) in sections"
      :key="section.id"
      class="cpub-section-item"
      :class="{
        'cpub-section-item-selected': selectedId === section.id,
        'cpub-section-item-dragging': dragIdx === idx,
        'cpub-section-item-drop': dropIdx === idx,
      }"
      draggable="true"
      @click="emit('select', section.id)"
      @dragstart="onDragStart(idx, $event)"
      @dragover="onDragOver(idx, $event)"
      @dragleave="dropIdx = null"
      @drop.prevent="onDrop(idx)"
      @dragend="onDragEnd"
    >
      <div
        class="cpub-section-num"
        :class="{ 'cpub-section-num-active': selectedId === section.id }"
      >
        {{ idx + 1 }}
      </div>
      <div class="cpub-section-info">
        <span class="cpub-section-title">{{ section.heading || 'Untitled' }}</span>
        <span class="cpub-section-badge" :style="{ color: getModuleColor(section) }">
          <span class="cpub-section-badge-dot" :style="{ background: getModuleColor(section) }" />
          {{ getModuleName(section) }}
        </span>
      </div>
    </div>

    <button class="cpub-section-add-btn" @click="emit('add')">
      <i class="fa-solid fa-plus" /> Add Section
    </button>
  </div>
</template>

<style scoped>
.cpub-section-list {
  display: flex;
  flex-direction: column;
  padding: 4px 0;
}

.cpub-section-item {
  display: flex;
  align-items: flex-start;
  gap: 8px;
  padding: 8px 10px 8px 12px;
  cursor: pointer;
  border-left: 2px solid transparent;
  transition: all 0.1s;
}

.cpub-section-item:hover {
  background: var(--surface2, rgba(255, 255, 255, 0.04));
}

.cpub-section-item-selected {
  background: var(--accent-bg, rgba(224, 64, 48, 0.06));
  border-left-color: var(--accent, #e04030);
}

.cpub-section-item-dragging {
  opacity: 0.4;
}

.cpub-section-item-drop {
  border-top: 2px solid var(--accent, #e04030);
}

.cpub-section-num {
  width: 18px;
  height: 18px;
  display: flex;
  align-items: center;
  justify-content: center;
  font-family: var(--font-ui, monospace);
  font-size: 9px;
  font-weight: 700;
  background: rgba(255, 255, 255, 0.06);
  color: var(--text-faint, #666);
  flex-shrink: 0;
  margin-top: 1px;
}

.cpub-section-num-active {
  background: var(--accent, #e04030);
  color: #fff;
}

.cpub-section-info {
  flex: 1;
  min-width: 0;
}

.cpub-section-title {
  display: block;
  font-size: 11px;
  font-weight: 500;
  color: var(--text, #ccc);
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}

.cpub-section-item-selected .cpub-section-title {
  color: #fff;
}

.cpub-section-badge {
  display: inline-flex;
  align-items: center;
  gap: 4px;
  font-family: var(--font-ui, monospace);
  font-size: 9px;
  margin-top: 2px;
}

.cpub-section-badge-dot {
  width: 5px;
  height: 5px;
  border-radius: 50%;
  flex-shrink: 0;
}

.cpub-section-add-btn {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 6px;
  width: 100%;
  padding: 8px;
  margin-top: 4px;
  background: none;
  border: 2px dashed var(--border, rgba(255, 255, 255, 0.1));
  color: var(--text-faint, #666);
  font-family: var(--font-ui, monospace);
  font-size: 10px;
  text-transform: uppercase;
  letter-spacing: 0.06em;
  cursor: pointer;
}

.cpub-section-add-btn:hover {
  border-color: var(--accent, #e04030);
  color: var(--accent, #e04030);
}
</style>

// apps/reference/src/lib/components/explainer/SectionList.svelte
<script lang="ts">
  import type { ExplainerSection } from '@snaplify/explainer';

  let {
    sections = [],
    activeIndex = 0,
    onselect,
    onadd,
    onremove,
    onmoveup,
    onmovedown,
  }: {
    sections: ExplainerSection[];
    activeIndex: number;
    onselect?: (index: number) => void;
    onadd?: (type: string) => void;
    onremove?: (index: number) => void;
    onmoveup?: (index: number) => void;
    onmovedown?: (index: number) => void;
  } = $props();

  let addType = $state<string>('text');
</script>

<div class="section-list">
  <h3 class="section-list__title">Sections</h3>

  <ol class="section-list__items">
    {#each sections as section, i}
      <li class="section-list__item" class:section-list__item--active={i === activeIndex}>
        <button
          class="section-list__select"
          onclick={() => onselect?.(i)}
          aria-label="Edit section: {section.title}"
          aria-current={i === activeIndex ? 'step' : undefined}
        >
          <span class="section-list__type">{section.type}</span>
          <span class="section-list__name">{section.title || 'Untitled'}</span>
        </button>
        <div class="section-list__actions">
          <button
            class="section-list__action"
            onclick={() => onmoveup?.(i)}
            disabled={i === 0}
            aria-label="Move section up">&uarr;</button
          >
          <button
            class="section-list__action"
            onclick={() => onmovedown?.(i)}
            disabled={i === sections.length - 1}
            aria-label="Move section down">&darr;</button
          >
          <button
            class="section-list__action section-list__action--delete"
            onclick={() => onremove?.(i)}
            aria-label="Remove section">&times;</button
          >
        </div>
      </li>
    {/each}
  </ol>

  <div class="section-list__add">
    <select bind:value={addType} aria-label="Section type to add">
      <option value="text">Text</option>
      <option value="quiz">Quiz</option>
      <option value="checkpoint">Checkpoint</option>
    </select>
    <button class="section-list__add-btn" onclick={() => onadd?.(addType)}> + Add Section </button>
  </div>
</div>

<style>
  .section-list {
    padding: var(--space-4, 1rem);
  }

  .section-list__title {
    font-size: var(--text-sm, 0.875rem);
    font-weight: var(--font-weight-semibold, 600);
    text-transform: uppercase;
    letter-spacing: 0.05em;
    color: var(--color-text-secondary, #888884);
    margin-bottom: var(--space-4, 1rem);
  }

  .section-list__items {
    list-style: none;
    padding: 0;
    margin: 0 0 var(--space-4, 1rem);
  }

  .section-list__item {
    display: flex;
    align-items: center;
    gap: var(--space-1, 0.25rem);
    margin-bottom: var(--space-1, 0.25rem);
    border-radius: var(--radius-sm, 4px);
  }

  .section-list__item--active {
    background: var(--color-primary-light, #eff6ff);
  }

  .section-list__select {
    flex: 1;
    display: flex;
    flex-direction: column;
    align-items: flex-start;
    padding: var(--space-1, 0.25rem) var(--space-2, 0.5rem);
    border: none;
    background: none;
    cursor: pointer;
    text-align: left;
    color: var(--color-text, #d8d5cf);
  }

  .section-list__type {
    font-size: var(--text-xs, 0.75rem);
    color: var(--color-text-secondary, #888884);
    text-transform: uppercase;
    letter-spacing: 0.05em;
  }

  .section-list__name {
    font-size: var(--text-sm, 0.875rem);
  }

  .section-list__actions {
    display: flex;
    gap: 2px;
  }

  .section-list__action {
    width: 24px;
    height: 24px;
    border: none;
    background: var(--color-surface-alt, #1c1c1a);
    border-radius: var(--radius-sm, 4px);
    cursor: pointer;
    font-size: var(--text-sm, 0.875rem);
    color: var(--color-text, #d8d5cf);
  }

  .section-list__action:disabled {
    opacity: 0.3;
    cursor: not-allowed;
  }

  .section-list__action--delete {
    color: var(--color-error, #dc2626);
  }

  .section-list__add {
    display: flex;
    gap: var(--space-1, 0.25rem);
  }

  .section-list__add select {
    flex: 1;
    padding: var(--space-1, 0.25rem);
    border: 1px solid var(--color-border, #272725);
    border-radius: var(--radius-sm, 4px);
    font-size: var(--text-sm, 0.875rem);
    background: var(--color-surface, #0c0c0b);
    color: var(--color-text, #d8d5cf);
  }

  .section-list__add-btn {
    padding: var(--space-1, 0.25rem) var(--space-2, 0.5rem);
    background: var(--color-primary, #2563eb);
    color: var(--color-on-primary, #ffffff);
    border: none;
    border-radius: var(--radius-sm, 4px);
    font-size: var(--text-sm, 0.875rem);
    cursor: pointer;
    white-space: nowrap;
  }
</style>
