// apps/reference/src/routes/(app)/search/+page.svelte
<script lang="ts">
  import SearchResult from '$lib/components/SearchResult.svelte';
  import Pagination from '$lib/components/Pagination.svelte';
  import { typeToUrlSegment } from '$lib/utils/content-helpers';
  import type { PageData } from './$types';

  let { data }: { data: PageData } = $props();

  const typeFilters = ['all', 'project', 'guide', 'explainer', 'article', 'blog'];

  function buildUrl(params: Record<string, string>): string {
    const sp = new URLSearchParams();
    const q = params.q ?? data.query;
    const type = params.type ?? data.type;
    if (q) sp.set('q', q);
    if (type && type !== 'all') sp.set('type', type);
    if (params.page && params.page !== '1') sp.set('page', params.page);
    return `/search?${sp.toString()}`;
  }
</script>

<svelte:head>
  <title>{data.query ? `${data.query} — Search` : 'Search'} — Snaplify</title>
</svelte:head>

<div class="page">
  <div class="search-bar">
    <form action="/search" method="GET" style="width:100%;">
      <input
        type="search"
        name="q"
        value={data.query}
        placeholder="Search projects, guides, articles..."
        class="search-input"
        autofocus
      />
      {#if data.type && data.type !== 'all'}
        <input type="hidden" name="type" value={data.type} />
      {/if}
    </form>
    {#if data.query}
      <div class="search-type-row">
        <span class="type-label">type:</span>
        {#each typeFilters as t}
          <a
            href={buildUrl({ type: t, page: '1' })}
            class="fchip"
            class:active={data.type === t}
          >
            {t}
          </a>
        {/each}
        <span class="result-count">{data.total} result{data.total !== 1 ? 's' : ''}</span>
      </div>
    {/if}
  </div>

  {#if data.query && data.items.length > 0}
    {#each data.items as item (item.id)}
      <SearchResult
        type={item.type}
        title={item.title}
        excerpt={item.description ?? ''}
        author={item.author.displayName ?? item.author.username ?? ''}
        href={`/${typeToUrlSegment(item.type)}/${item.slug}`}
      />
    {/each}

    <Pagination
      page={data.page}
      totalPages={data.totalPages}
      buildUrl={(p) => buildUrl({ page: String(p) })}
    />
  {:else if data.query}
    <div class="empty-state">No results found for "{data.query}"</div>
  {:else}
    <div class="empty-state">Search for projects, guides, articles, and more.</div>
  {/if}
</div>

<style>
  .search-bar {
    margin-bottom: 20px;
  }

  .search-input {
    width: 100%;
    background: var(--color-surface-alt, #141413);
    border: 1px solid var(--color-border-strong, #333330);
    border-radius: var(--radius-md, 0.25rem);
    padding: 10px 16px;
    font-size: 14px;
    color: var(--color-text);
    outline: none;
    font-family: inherit;
  }

  .search-input:focus {
    border-color: var(--color-accent, #5b9cf6);
  }

  .search-input::placeholder {
    color: var(--color-text-muted, #444440);
  }

  .search-type-row {
    display: flex;
    gap: 8px;
    margin-top: 10px;
    align-items: center;
    flex-wrap: wrap;
  }

  .type-label {
    font-size: 11px;
    font-family: var(--font-mono, monospace);
    color: var(--color-text-muted, #444440);
  }

  .result-count {
    margin-left: auto;
    font-size: 11px;
    font-family: var(--font-mono, monospace);
    color: var(--color-text-muted, #444440);
  }

  .empty-state {
    text-align: center;
    padding: var(--space-12, 3rem);
    color: var(--color-text-secondary, #888884);
  }
</style>

// apps/reference/pages/search.vue
<script setup lang="ts">
useSeoMeta({
  title: 'Search — CommonPub',
  description: 'Search for projects, tutorials, and community content.',
});

const query = ref('');
const activeFilter = ref('all');
const filters = ['all', 'project', 'article', 'guide', 'blog'] as const;

const searchQuery = computed(() => ({
  q: query.value,
  type: activeFilter.value === 'all' ? undefined : activeFilter.value,
  limit: 20,
}));

const { data: results, status } = await useFetch('/api/search', {
  query: searchQuery,
  watch: [searchQuery],
  lazy: true,
});
</script>

<template>
  <div class="search-page">
    <h1 class="search-title">Search</h1>

    <div class="search-bar">
      <input
        v-model="query"
        type="search"
        class="search-input"
        placeholder="Search content..."
        aria-label="Search content"
      />
    </div>

    <div class="search-filters" role="tablist" aria-label="Content type filters">
      <button
        v-for="filter in filters"
        :key="filter"
        role="tab"
        :aria-selected="activeFilter === filter"
        :class="['filter-btn', { active: activeFilter === filter }]"
        @click="activeFilter = filter"
      >
        {{ filter }}
      </button>
    </div>

    <div class="search-results">
      <p class="search-placeholder" v-if="!query">
        Enter a search term to find content across the community.
      </p>
      <p class="search-loading" v-else-if="status === 'pending'">Searching...</p>
      <template v-else-if="results?.items?.length">
        <div class="result-card" v-for="item in results.items" :key="item.id">
          <span class="result-type">{{ item.type }}</span>
          <h2 class="result-title">
            <NuxtLink :to="`/${item.type}/${item.slug}`">{{ item.title }}</NuxtLink>
          </h2>
          <p class="result-desc" v-if="item.description">{{ item.description }}</p>
          <div class="result-meta">
            <span>by {{ item.author.displayName || item.author.username }}</span>
            <span>{{ item.viewCount }} views</span>
          </div>
        </div>
      </template>
      <p class="search-placeholder" v-else>
        No results found for "{{ query }}".
      </p>
    </div>
  </div>
</template>

<style scoped>
.search-page {
  max-width: var(--content-max-width);
}

.search-title {
  font-size: var(--text-xl);
  font-weight: var(--font-weight-bold);
  margin-bottom: var(--space-4);
}

.search-bar {
  margin-bottom: var(--space-4);
}

.search-input {
  width: 100%;
  padding: var(--space-3) var(--space-4);
  border: 1px solid var(--border);
  border-radius: var(--radius-md);
  background: var(--surface);
  color: var(--text);
  font-size: var(--text-base);
  font-family: var(--font-sans);
}

.search-input:focus {
  outline: none;
  border-color: var(--accent);
  box-shadow: var(--focus-ring);
}

.search-filters {
  display: flex;
  gap: var(--space-2);
  margin-bottom: var(--space-6);
  border-bottom: 1px solid var(--border);
  padding-bottom: var(--space-2);
}

.filter-btn {
  padding: var(--space-1) var(--space-3);
  background: none;
  border: none;
  border-radius: var(--radius-sm);
  color: var(--text-dim);
  font-size: var(--text-sm);
  font-family: var(--font-sans);
  cursor: pointer;
  text-transform: capitalize;
}

.filter-btn:hover {
  color: var(--text);
  background: var(--surface2);
}

.filter-btn.active {
  color: var(--accent);
  font-weight: var(--font-weight-medium);
}

.search-placeholder {
  color: var(--text-faint);
  font-size: var(--text-sm);
  text-align: center;
  padding: var(--space-10) 0;
}

.search-loading {
  color: var(--text-faint);
  font-size: var(--text-sm);
  text-align: center;
  padding: var(--space-6) 0;
}

.result-card {
  padding: var(--space-4);
  border: 1px solid var(--border);
  border-radius: var(--radius-md);
  background: var(--surface);
  margin-bottom: var(--space-3);
}

.result-type {
  font-size: var(--text-xs);
  text-transform: capitalize;
  color: var(--accent);
  font-weight: var(--font-weight-medium);
}

.result-title {
  font-size: var(--text-md);
  font-weight: var(--font-weight-semibold);
  margin: var(--space-1) 0;
}

.result-title a {
  color: var(--text);
  text-decoration: none;
}

.result-title a:hover {
  color: var(--accent);
}

.result-desc {
  font-size: var(--text-sm);
  color: var(--text-dim);
  line-height: var(--leading-relaxed);
}

.result-meta {
  display: flex;
  gap: var(--space-3);
  margin-top: var(--space-2);
  font-size: var(--text-xs);
  color: var(--text-faint);
}
</style>
