// apps/reference/components/CommentSection.vue
<script setup lang="ts">
const props = defineProps<{
  contentId: string;
}>();

const { user } = useAuth();

const { data: comments, refresh } = await useFetch('/api/social/comments', {
  query: { contentId: props.contentId },
  lazy: true,
});

const newComment = ref('');
const submitting = ref(false);

async function submitComment(): Promise<void> {
  if (!newComment.value.trim()) return;
  submitting.value = true;
  try {
    await $fetch('/api/social/comments', {
      method: 'POST',
      body: { contentId: props.contentId, body: newComment.value },
    });
    newComment.value = '';
    await refresh();
  } finally {
    submitting.value = false;
  }
}

async function deleteComment(id: string): Promise<void> {
  await $fetch(`/api/social/comments/${id}`, { method: 'DELETE' });
  await refresh();
}
</script>

<template>
  <section class="cpub-comments" aria-label="Comments">
    <h3 class="cpub-comments-title">
      Comments
      <span v-if="comments?.length" class="cpub-comments-count">{{ comments.length }}</span>
    </h3>

    <!-- New comment form -->
    <div v-if="user" class="cpub-comment-form">
      <textarea
        v-model="newComment"
        class="cpub-textarea"
        placeholder="Write a comment..."
        rows="3"
        aria-label="Write a comment"
      ></textarea>
      <button
        class="cpub-btn cpub-btn-primary cpub-btn-sm"
        :disabled="!newComment.trim() || submitting"
        @click="submitComment"
      >
        {{ submitting ? 'Posting...' : 'Post Comment' }}
      </button>
    </div>
    <p v-else class="cpub-comment-login">
      <NuxtLink to="/auth/login" class="cpub-link">Log in</NuxtLink> to comment.
    </p>

    <!-- Comments list -->
    <div class="cpub-comment-list">
      <div v-for="comment in (comments || [])" :key="(comment as any).id" class="cpub-comment">
        <div class="cpub-comment-avatar">
          {{ ((comment as any).author?.displayName || (comment as any).author?.username || 'U').charAt(0).toUpperCase() }}
        </div>
        <div class="cpub-comment-body">
          <div class="cpub-comment-header">
            <NuxtLink :to="`/u/${(comment as any).author?.username}`" class="cpub-comment-author">
              {{ (comment as any).author?.displayName || (comment as any).author?.username }}
            </NuxtLink>
            <time class="cpub-comment-time">
              {{ new Date((comment as any).createdAt).toLocaleDateString('en-US', { month: 'short', day: 'numeric' }) }}
            </time>
          </div>
          <p class="cpub-comment-text">{{ (comment as any).body }}</p>
          <button
            v-if="(user as any)?.id === (comment as any).authorId"
            class="cpub-comment-delete"
            @click="deleteComment((comment as any).id)"
            aria-label="Delete comment"
          >
            Delete
          </button>
        </div>
      </div>
      <p v-if="!comments?.length" class="cpub-comments-empty">No comments yet. Be the first!</p>
    </div>
  </section>
</template>

<style scoped>
.cpub-comments {
  margin-top: var(--space-8);
  padding-top: var(--space-6);
  border-top: 2px solid var(--border);
}

.cpub-comments-title {
  font-size: 14px;
  font-weight: 600;
  margin-bottom: var(--space-4);
  display: flex;
  align-items: center;
  gap: 8px;
}

.cpub-comments-count {
  font-family: var(--font-mono);
  font-size: 10px;
  color: var(--text-faint);
  background: var(--surface2);
  padding: 1px 6px;
  border: 1px solid var(--border2);
}

.cpub-comment-form {
  margin-bottom: var(--space-6);
  display: flex;
  flex-direction: column;
  gap: var(--space-2);
  align-items: flex-end;
}

.cpub-comment-form .cpub-textarea {
  width: 100%;
}

.cpub-comment-login {
  font-size: 13px;
  color: var(--text-dim);
  margin-bottom: var(--space-6);
}

.cpub-comment-list {
  display: flex;
  flex-direction: column;
  gap: var(--space-4);
}

.cpub-comment {
  display: flex;
  gap: 10px;
}

.cpub-comment-avatar {
  width: 28px;
  height: 28px;
  border-radius: 50%;
  background: var(--surface3);
  border: 2px solid var(--border);
  display: flex;
  align-items: center;
  justify-content: center;
  font-family: var(--font-mono);
  font-size: 10px;
  font-weight: 600;
  color: var(--text-dim);
  flex-shrink: 0;
}

.cpub-comment-body {
  flex: 1;
  min-width: 0;
}

.cpub-comment-header {
  display: flex;
  align-items: center;
  gap: 8px;
  margin-bottom: 4px;
}

.cpub-comment-author {
  font-size: 12px;
  font-weight: 600;
  color: var(--text);
  text-decoration: none;
}

.cpub-comment-author:hover {
  color: var(--accent);
}

.cpub-comment-time {
  font-size: 10px;
  color: var(--text-faint);
  font-family: var(--font-mono);
}

.cpub-comment-text {
  font-size: 13px;
  color: var(--text-dim);
  line-height: 1.6;
}

.cpub-comment-delete {
  font-size: 10px;
  color: var(--text-faint);
  background: none;
  border: none;
  cursor: pointer;
  margin-top: 4px;
  padding: 0;
}

.cpub-comment-delete:hover {
  color: var(--red);
}

.cpub-comments-empty {
  color: var(--text-faint);
  font-size: 13px;
  text-align: center;
  padding: var(--space-6) 0;
}
</style>

// apps/reference/src/lib/components/CommentSection.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import type { CommentItem } from '$lib/types';

  let {
    targetType,
    targetId,
  }: {
    targetType: string;
    targetId: string;
  } = $props();

  let comments = $state<CommentItem[]>([]);
  let newComment = $state('');
  let loading = $state(false);
  let submitting = $state(false);

  onMount(async () => {
    loading = true;
    try {
      const res = await fetch(
        `/api/social/comments?targetType=${encodeURIComponent(targetType)}&targetId=${encodeURIComponent(targetId)}`,
      );
      if (res.ok) {
        const data = await res.json();
        comments = data.comments;
      }
    } finally {
      loading = false;
    }
  });

  async function submitComment() {
    if (!newComment.trim() || submitting) return;
    submitting = true;

    try {
      const res = await fetch('/api/social/comments', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ targetType, targetId, content: newComment.trim() }),
      });

      if (res.ok) {
        const data = await res.json();
        comments = [data.comment, ...comments];
        newComment = '';
      }
    } finally {
      submitting = false;
    }
  }

  async function handleDelete(commentId: string) {
    const res = await fetch(`/api/social/comments?id=${encodeURIComponent(commentId)}`, {
      method: 'DELETE',
    });
    if (res.ok) {
      comments = comments.filter((c) => c.id !== commentId);
    }
  }
</script>

<section class="comments" aria-label="Comments">
  <h2>Comments</h2>

  <form
    class="comment-form"
    onsubmit={(e) => {
      e.preventDefault();
      submitComment();
    }}
  >
    <textarea
      bind:value={newComment}
      placeholder="Write a comment..."
      rows="3"
      maxlength="10000"
      aria-label="Comment text"
    ></textarea>
    <button type="submit" class="btn btn-primary" disabled={submitting || !newComment.trim()}>
      {submitting ? 'Posting...' : 'Post Comment'}
    </button>
  </form>

  {#if loading}
    <p class="comments-loading">Loading comments...</p>
  {:else if comments.length === 0}
    <p class="comments-empty">No comments yet. Be the first!</p>
  {:else}
    <div class="comments-list">
      {#each comments as comment (comment.id)}
        <div class="comment">
          <div class="comment-header">
            {#if comment.author.avatarUrl}
              <img
                src={comment.author.avatarUrl}
                alt=""
                class="comment-avatar"
                width="32"
                height="32"
              />
            {:else}
              <span class="comment-avatar-placeholder">
                {comment.author.displayName?.[0] ?? comment.author.username[0]}
              </span>
            {/if}
            <div>
              <span class="comment-author"
                >{comment.author.displayName ?? comment.author.username}</span
              >
              <time class="comment-date" datetime={comment.createdAt.toString()}>
                {new Date(comment.createdAt).toLocaleDateString()}
              </time>
            </div>
          </div>
          <p class="comment-content">{comment.content}</p>
          {#if comment.replies?.length}
            <div class="comment-replies">
              {#each comment.replies as reply (reply.id)}
                <div class="comment reply">
                  <div class="comment-header">
                    <span class="comment-author"
                      >{reply.author.displayName ?? reply.author.username}</span
                    >
                    <time class="comment-date"
                      >{new Date(reply.createdAt).toLocaleDateString()}</time
                    >
                  </div>
                  <p class="comment-content">{reply.content}</p>
                </div>
              {/each}
            </div>
          {/if}
        </div>
      {/each}
    </div>
  {/if}
</section>

<style>
  .comments {
    margin-top: var(--space-6, 2rem);
  }

  .comments h2 {
    font-size: var(--text-lg, 1.25rem);
    margin-bottom: var(--space-4, 1rem);
    color: var(--color-text, #d8d5cf);
  }

  .comment-form {
    margin-bottom: var(--space-6, 2rem);
  }

  .comment-form textarea {
    width: 100%;
    padding: var(--space-2, 0.5rem);
    border: 1px solid var(--color-border, #272725);
    border-radius: var(--radius-sm, 4px);
    font-size: var(--text-md, 1rem);
    background: var(--color-surface, #0c0c0b);
    color: var(--color-text, #d8d5cf);
    resize: vertical;
    box-sizing: border-box;
    margin-bottom: var(--space-2, 0.5rem);
  }

  .btn {
    padding: var(--space-1, 0.25rem) var(--space-4, 1rem);
    border: none;
    border-radius: var(--radius-md, 6px);
    cursor: pointer;
    font-size: var(--text-sm, 0.875rem);
  }

  .btn-primary {
    background: var(--color-primary, #5b9cf6);
    color: var(--color-on-primary, #0c0c0b);
  }

  .btn-primary:disabled {
    opacity: 0.6;
    cursor: not-allowed;
  }

  .comments-loading,
  .comments-empty {
    color: var(--color-text-secondary, #888884);
    font-size: var(--text-sm, 0.875rem);
  }

  .comments-list {
    display: flex;
    flex-direction: column;
    gap: var(--space-4, 1rem);
  }

  .comment {
    padding: var(--space-4, 1rem);
    border: 1px solid var(--color-border, #272725);
    border-radius: var(--radius-md, 6px);
    background: var(--color-surface, #0c0c0b);
  }

  .comment-header {
    display: flex;
    align-items: center;
    gap: var(--space-2, 0.5rem);
    margin-bottom: var(--space-1, 0.25rem);
  }

  .comment-avatar {
    border-radius: 50%;
    object-fit: cover;
  }

  .comment-avatar-placeholder {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    width: 32px;
    height: 32px;
    border-radius: 50%;
    background: var(--color-primary, #5b9cf6);
    color: var(--color-on-primary, #0c0c0b);
    font-weight: var(--font-weight-bold, 700);
    font-size: var(--text-sm, 0.875rem);
  }

  .comment-author {
    font-weight: var(--font-weight-medium, 500);
    color: var(--color-text, #d8d5cf);
  }

  .comment-date {
    font-size: var(--text-xs, 0.75rem);
    color: var(--color-text-secondary, #888884);
    margin-left: var(--space-1, 0.25rem);
  }

  .comment-content {
    margin: var(--space-1, 0.25rem) 0 0;
    color: var(--color-text, #d8d5cf);
    line-height: 1.5;
    white-space: pre-wrap;
  }

  .comment-replies {
    margin-top: var(--space-2, 0.5rem);
    padding-left: var(--space-6, 2rem);
    display: flex;
    flex-direction: column;
    gap: var(--space-2, 0.5rem);
  }

  .reply {
    border-color: var(--color-border, #272725);
    background: var(--color-surface-alt, #141413);
  }
</style>
