// apps/reference/pages/docs/create.vue
<script setup lang="ts">
definePageMeta({ middleware: 'auth' });

useSeoMeta({ title: 'Create Docs Site — CommonPub' });

const toast = useToast();
const { extract: extractError } = useApiError();
const name = ref('');
const description = ref('');
const saving = ref(false);

async function handleCreate(): Promise<void> {
  saving.value = true;
  try {
    const result = await $fetch('/api/docs', {
      method: 'POST',
      body: { name: name.value, description: description.value },
    });
    await navigateTo(`/docs/${(result as { slug: string }).slug}`);
  } catch (err: unknown) {
    toast.error(extractError(err));
  } finally {
    saving.value = false;
  }
}
</script>

<template>
  <div class="create-docs-page">
    <h1 class="page-title">Create Docs Site</h1>

    <form class="docs-form" @submit.prevent="handleCreate" aria-label="Create docs site">
      <div class="form-field">
        <label for="docs-name" class="form-label">Name</label>
        <input id="docs-name" v-model="name" type="text" class="form-input" required placeholder="Documentation site name" />
      </div>

      <div class="form-field">
        <label for="docs-desc" class="form-label">Description</label>
        <textarea id="docs-desc" v-model="description" class="form-textarea" rows="3" placeholder="What is this documentation about?" />
      </div>

      <button type="submit" class="cpub-btn cpub-btn-primary" :disabled="saving || !name">
        {{ saving ? 'Creating...' : 'Create Docs Site' }}
      </button>
    </form>
  </div>
</template>

<style scoped>
.create-docs-page { max-width: 600px; }
.page-title { font-size: var(--text-xl); font-weight: var(--font-weight-bold); margin-bottom: var(--space-6); }
.docs-form { display: flex; flex-direction: column; gap: var(--space-4); }
.form-field { display: flex; flex-direction: column; gap: var(--space-1); }
.form-label { font-size: var(--text-sm); font-weight: var(--font-weight-medium); }
.form-input, .form-textarea { padding: var(--space-2) var(--space-3); border: 1px solid var(--border); background: var(--surface); color: var(--text); font-size: var(--text-base); font-family: var(--font-sans); }
.form-input:focus, .form-textarea:focus { outline: none; border-color: var(--accent); box-shadow: var(--focus-ring); }
.form-textarea { resize: vertical; }
</style>

// apps/reference/src/routes/(app)/docs/create/+page.svelte
<script lang="ts">
  import { Input, Textarea, Button } from '@snaplify/ui';
  import type { ActionData } from './$types';

  let { form }: { form: ActionData } = $props();
</script>

<svelte:head>
  <title>Create Documentation Site — Snaplify</title>
</svelte:head>

<section class="create-docs-page">
  <h1 class="page-title">Create Documentation Site</h1>

  {#if form?.error}
    <div class="error-message" role="alert">{form.error}</div>
  {/if}

  <form method="POST" class="create-form">
    <Input id="name" name="name" label="Name" required />

    <Textarea id="description" name="description" label="Description (optional)" rows={3} />

    <Button variant="primary" size="md" type="submit">Create Site</Button>
  </form>
</section>

<style>
  .create-docs-page {
    max-width: var(--layout-narrow-width, 640px);
    margin: 0 auto;
    padding: var(--space-4, 1rem);
  }

  .page-title {
    font-size: var(--text-2xl, 1.875rem);
    margin-bottom: var(--space-6, 2rem);
    color: var(--color-text, inherit);
  }

  .error-message {
    padding: var(--space-2, 0.5rem);
    margin-bottom: var(--space-4, 1rem);
    border: 1px solid var(--color-danger, #ef4444);
    border-radius: var(--radius-sm, 0.25rem);
    color: var(--color-danger, #ef4444);
    font-size: var(--text-sm, 0.875rem);
  }

  .create-form {
    display: flex;
    flex-direction: column;
    gap: var(--space-4, 1rem);
  }

</style>
